### ISSUE TITLE
In alert screen there no alert title at very top

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#1001]
In alert screen there no alert title at very top
![image](https://user-images.githubusercontent.com/11581207/109031832-c2974980-76cd-11eb-9866-8a1e9124e388.png)
![image](https://user-images.githubusercontent.com/11581207/109032464-5c5ef680-76ce-11eb-9a09-7f42eaf6dbc2.png)

**Comment by makus82** [comment]
hm its didnt work there need something more

**Comment by makus82** [comment]
<label id="TEXT_ALERT">
        <position x="113" y="0"/>
        <size width="420" height="32"/>
        <alignment horizontal="centre" vertical="centre"/>
        <font>bigfont</font>
      </label>

in data/forms/city/alert.form dont work 
and this also when i edit game files
      <label id="ALERT">
        <position x="113" y="0"/>
        <size width="420" height="32"/>
        <alignment horizontal="centre" vertical="centre"/>
        <font>bigfont</font>
      </label>

**Comment by idshibanov** [comment]
@makus82 You have to change the label tag to `<label id="TEXT_ALERT" text="ALERT">`. Actual text is set separately from id.

**Comment by makus82** [comment]
yep, thats works, thx Ivan!
