### ISSUE TITLE
Damage to the city reverts to a previous state when loading a savegame and repairs the following day

### ISSUE THREAD

**Issue by EmperorLol** [OpenApoc/OpenApoc#1009]
Whenever reloading the game while in Geoscape the city reverts to an older, destroyed form. This is then fully and completely repaired upon the new day. 

Further, the roads destroyed in that state are treated as destroyed even after this repair, suggesting the damage to the city is still there on some level even after the appearance of repairs are made. This damage only affects XCOM vehicles, not civilian/corp cars.

Events that led up to this situation (and the subsequent state of the city it reverts to) were two raids on the Psyche slums next to the xcom main base, then a large raid on the city by ufos that caused significant damage to surrounding buildings. 

![Bug 1](https://user-images.githubusercontent.com/78159929/110706447-c491fa00-81ef-11eb-8a37-998fcfa4d0f9.png)
^ The game after the day has ticked over, rebuilding the city entirely.

![bug 2](https://user-images.githubusercontent.com/78159929/110706542-f0ad7b00-81ef-11eb-9301-3ac48b92b33a.png)
^ The game after reloading the save created of the exact moment above. Nothing has changed in game, aside from loading it.

Bugsave 1 is the city at 22:00, allowing you to load in and see it in its state and (hopefully) see it repair when it hits midnight. There are stormdogs in the newly constructed base, but they cannot enter the main base due to road damage. Use the return to base button to see them stop outside where the road was blown up. 
[save_Bugsave 1.zip](https://github.com/OpenApoc/OpenApoc/files/6119175/save_Bugsave.1.zip)

Bugsave 2 is after the new day has begun. This shows that reloading the game even after the city has just repairs reverts it to its destroyed state.
[save_Bugsave 2.zip](https://github.com/OpenApoc/OpenApoc/files/6119177/save_Bugsave.2.zip)

**Comment by kgd192** [comment]
Has been fixed by #1135
Can be closed

**Comment by FilmBoy84** [comment]
Has the stepped repair functionality according to the above also been restored by this fix?
I wasn't sure if rate of repair (and cost to parent organisation) was implemented yet?

If not I'll close this Issue and create one specifically for it

**Comment by kgd192** [comment]
> Has the stepped repair functionality according to the above also been restored by this fix? I wasn't sure if rate of repair (and cost to parent organisation) was implemented yet?
> 
> If not I'll close this Issue and create one specifically for it

As far as I see it it does not fix the stepped repair. I think it is a good Idea to track this as a sepparate issue
