### ISSUE TITLE
Engine not showing up for original 2 hover cars.

### ISSUE THREAD

**Issue by SplitMilky** [OpenApoc/OpenApoc#1022]
version. 0_386_11_gacf7b756 (compiled on my system, no errors)

Bought an SD turbo. After it arrived went into the engine equip screen and it was not showing up for the hovercar 1 and 2 but did show up for a new hovercar I bought. Hovercar 143.  

I was not able to reproduce after reloading.

**Comment by FilmBoy84** [comment]
Thanks for reporting this
There are a number of unrelated issues with starting vehicles
So catching more to look at may help with resolving the core problem

If I can replicate here, will update labels and issue accordingly

**Comment by FilmBoy84** [comment]
I can no longer replicate this issue, closing
