### ISSUE TITLE
OpenApoc fails to compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by mauricioduarte01** [OpenApoc/OpenApoc#1024]
Hello,
I am experiencing issues when I try to build OpenApoc from source (please find attached the logs from CMake), I've installed "in theory" all of the required dependencies in order to do it, I think the issue may be something more related on how my OS is configured since I didn't find much information about the building errors. 

    PC: Ryzen 3600, Ubuntu 20.04, Nvidia 1660ti.
    Build: Alpha build v0.386 (06.03.2021)

Expected behavior

CMake success and finishes building.

Actual behavior

CMake fails to build the binary in order to install OpenApoc.

After executing cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. , I get:
Configuring incomplete, errors occurred!
[CMakeOutput.log](https://github.com/OpenApoc/OpenApoc/files/6217849/CMakeOutput.log)
[CMakeError.log](https://github.com/OpenApoc/OpenApoc/files/6217848/CMakeError.log)

Thank you!
Keep up the good work

**Comment by JonnyH** [comment]
I don't think the attached files have the actual cmake error - just an "expected" failed compilation as part of cmake's configuration.

Maybe attaching the stdout of the cmake command itself would help?

**Comment by mauricioduarte01** [comment]
Hello @JonnyH , thanks for your response. 

> ~/OpenApoc/build$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
> -- The CXX compiler identification is GNU 9.3.0
> -- The C compiler identification is GNU 9.3.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> Using CD at "/home/bladerunner/OpenApoc/data/cd.iso"
> -- Performing Test CXX_COMPILER_SUPPORTS_HIDDEN_VISIBILITY
> -- Performing Test CXX_COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
> -- Performing Test C_COMPILER_SUPPORTS_HIDDEN_VISIBILITY
> -- Performing Test C_COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: locale 
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE  
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
> -- Checking for module 'libunwind'
> --   Found libunwind, version 1.21
> -- Using <filesystem>
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.50") found components: locale system program_options 
> -- Checking for module 'sdl2>=2.0'
> --   Found sdl2, version 2.0.10
> Searching for SDL2 in 
> Found SDL2 at /usr/lib/x86_64-linux-gnu/libSDL2.so
> CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
>   Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
>   available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   FindOpenGL found both a legacy GL library:
> 
>     OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
> 
>   and GLVND libraries for OpenGL and GLX:
> 
>     OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
>     OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
> 
>   OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
>   compatibility with CMake 3.10 and below the legacy GL library will be used.
> Call Stack (most recent call first):
>   framework/CMakeLists.txt:295 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")  
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options 
> CMake Error at dependencies/CMakeLists.txt:131 (add_subdirectory):
>   The source directory
> 
>     /home/bladerunner/OpenApoc/dependencies/physfs
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> CMake Error at dependencies/CMakeLists.txt:150 (add_subdirectory):
>   The source directory
> 
>     /home/bladerunner/OpenApoc/dependencies/fmt
> 
>   does not contain a CMakeLists.txt file.
> 
> 
> Found xmllint /usr/bin/xmllint
> -- Found Git: /usr/bin/git (found version "2.25.1") 
> fatal: Not a valid object name HEAD
> CMake Error at CMakeLists.txt:248 (string):
>   string sub-command REPLACE requires at least four arguments.
> 
> 
> -- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
> -- Configuring incomplete, errors occurred!
> See also "/home/bladerunner/OpenApoc/build/CMakeFiles/CMakeOutput.log".
> See also "/home/bladerunner/OpenApoc/build/CMakeFiles/CMakeError.log"

**Comment by JonnyH** [comment]
It looks like you're not running the cmake from a valid git repository. Did you download the source using "git clone"? I think github has a link that downloads a snapshot zip of the source, but that won't work - you should use git clone instead.

**Comment by mauricioduarte01** [comment]
That made the trick! (git clone) I can't believe it. I was getting the source files directly from "releases", and for some reason that didn't fetch required dependencies. 
Sorry for this rookie mistake, I managed now to run the game (finally!)
Thank you. ;)
