### ISSUE TITLE
[Tactical] CTRL clicking while trying to make pathing waypoints causes CTD

### ISSUE THREAD

**Issue by SplitMilky** [OpenApoc/OpenApoc#1025]
0_386_11_gacf7b756 Win10

Having a soldiers path set up and than holding CTRL and clicking on a new spot causes a crash.

**Comment by makus82** [comment]
Thx SplitMilky =]

**Comment by Andy51** [comment]
Same as #932. I have checked this was fixed in 7a31e4a52 (released as 0.20220126)

**Comment by FilmBoy84** [comment]
> Same as #932. I have checked this was fixed in [7a31e4a](https://github.com/OpenApoc/OpenApoc/commit/7a31e4a527f0c92f21bfa61764f6df3b945dd371) (released as 0.20220126)

Many thanks for confirming fixed
Closing 🍻
