### ISSUE TITLE
Crash when psi-controlled unit dies

### ISSUE THREAD

**Issue by zigmar** [OpenApoc/OpenApoc#1046]
When psi-controlled unit dies, the game crashes. 

To reproduce: load this [save game](https://github.com/OpenApoc/OpenApoc/files/6639770/save_psi_crash.zip), get psi-controlled unit die (e.g. suicide by grenade), observe game crash.

Seems to be caused by iterating over std::map while modifying it content at battleunit.cpp:4430 (BattleUnit::dropDown)

**Comment by FilmBoy84** [comment]
Good catch, can replicate as instructed
Elevating to High Level Bug as it crashed the game
