### ISSUE TITLE
Clicking on projectile crashes the game

### ISSUE THREAD

**Issue by gyunaev** [OpenApoc/OpenApoc#1060]
Crash happens at OpenApoc/game/ui/tileview/cityview.cpp line 3368

`LogInfo("CLICKED PROJECTILE %s at %s", projectile->damage, projectile->position);`

it crashes because projectile->damage is an int, and not passable via %s.

Fix is obvious: %s -> %d

`LogInfo("CLICKED PROJECTILE %d at %s", projectile->damage, projectile->position);`

**Comment by JonnyH** [comment]
Thanks for pointing this out - this was fallout when we changed how we format string and it became more strict - some rarely hit log may not have been noticed in the conversion.
