### ISSUE TITLE
Items in the marketplace do not replenish each week and do not adhere to min/max rules specified in economy.xml including if cheats are used to change time

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1070]
**Describe the bug**
There appears to be an issue restocking the marketplace with items each week - it does not happen - it is most noticeable when playing with mods as there are naturally more items to not be replenished - but it happens in unmodified games too

The economy.xml specifices a minimum stock level and a maximum stock level for each week - RNG influenced by supply/demand from the organisations in the city as well as relations should affect how many are produced (check OG logic) and then the results of that calculation given as the number in stock for that week

This is currently a serious issue for players as they will find, unless they have researched "recharging" weapons, they soon run out of ammunition

Craft also suffer from ammunition shortages and shortages of fuel and elerium that can stop game progression if the player has not got the research items for making their own craft (which have infinite fuel) or alien craft weapons (that recharge)

For that reason, this economy bug is GAME-BREAKING

**To Reproduce**
1. Buy some agent equipment from the marketplace - if using mods, ensure some of this equipment is from those mods - they seem worse afflicted by this bug
![image](https://user-images.githubusercontent.com/33913088/139066865-2fc8f9d8-de4a-466b-b8f6-e47845e371eb.png)
2. Play forward one week (or cheat a week forward) - playing elimates any cheat issues as the cause
3. Go to the marketplace and try to buy the same items - none will be in stock and only any remaining stock at X-COM will be available for sale. New Items appearing that week will also not be in stock
![image](https://user-images.githubusercontent.com/33913088/139067694-017b7e74-795e-4c22-bda7-c4583fbfe982.png)

**Expected behavior**
The marketplace should restock each week obeying the min/max limits and according to the logic used by the OG for economical and relationship effects on RNG between the min/max values

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 2020H2
 - OpenApoc Version : 0.386-52 - both with and without the Extended Weapons Mod (i.e. both vanilla and modded openapoc)

**Comment by Istrebitel** [comment]
Cannot reproduce on latest build:
1. Start new game
2. Do nothing, skip on fastest time for a week
3. Use F1+X to crash UFOs that spawn
4. After week elapses, economy updates appropriately

If you do manage to reproduce, please use F1 + W cheat to look @ alien dimension and see if UFOs grew (week 2 should have some purple fast attack ships appear). If they did - there is something wrong with the economy update, if they did not - the whole end of week hook is borked.

**Comment by FilmBoy84** [comment]
Many thanks, this does seem to be  a curious bug

Here's what playing through without debug reveals

Week 1
![image](https://user-images.githubusercontent.com/33913088/139534581-8e5de04a-0e19-4d35-8f53-45f99a880cc2.png)

Week 2
![image](https://user-images.githubusercontent.com/33913088/139534588-fefec3a0-4ddf-4d43-9890-277f27507b37.png)

**Comment by FilmBoy84** [comment]
Update to this issue

It appears than new games - with or without mods - will work since this PR
https://github.com/OpenApoc/OpenApoc/pull/1069

The exception is if the player cheats time forwards - in which case the end of day/week/month calcs do not seem to be applied - they need to be

Nonetheless, deescalating this to a low priority bug and renaming it

Thanks Istrebitel for checking  this out too

🍻

**Comment by JonnyH** [comment]
Were you testing on debug or release @FilmBoy84 ?

As far as I can see, #1069 on release *should* not affect anything, as the iterator destructors are effectively a NOP. If so, that may imply this issue is somehow non-deterministic, or there's some trigger we're currently missing, and may not actually be solvbed.

On debug, however, anything could happen and weird memory corruption. could break lots of things.

**Comment by FilmBoy84** [comment]
Using build 20231214B

With the following saves (before and after end of week)

Mods in use are also included in the ZIP

The error can be seen on the video here at ~01:57:34

[Market Stock Bug 20231226.zip](https://github.com/OpenApoc/OpenApoc/files/13773737/Market.Stock.Bug.20231226.zip)

https://youtu.be/A0zIrEWZB4k?t=7054

**Comment by Quickmind01** [comment]
Here is a save from the end of week 3 using build 20231214B-4-g131514ee.
[save_End of Week 3.zip](https://github.com/OpenApoc/OpenApoc/files/13774011/save_End.of.Week.3.zip)

**Comment by dethstryke01** [comment]
At roughly 1:18:00, it doesn't look like the restock has happened. 

[https://www.youtube.com/watch?v=jYKta8V-Yvc](url)

**Comment by kgd192** [comment]
Will be having a look at this over the Weekend 👌
