### ISSUE TITLE
Vehicles do not automatically replenish ammo on return to base

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1071]
**Describe the bug**
Vehicles with available ammo in the stores and at a base with free "Repair Facility" capacity do not replenish ammunition automatically after a fight

Evidence of this can be seen on Quickmind's recent OpenApoc stream here https://www.twitch.tv/videos/1184682999?t=00h57m30s (00:56:30~)

**To Reproduce**
1. Select a vehicle with a none-recharging ammunition, for example, a hoverbike's default cannon
2. Press "N" for manual command
3. Right Click on a location outside of the city to send the vehicle there
4. When in an open space, open fire by using the left click until the ammo counter (red bar next to weapon) is noticeably depleted
5. Return to base
6. Forward Time at 4x (or Ultra)
7. Observe that the ammunition does not always refill

**Expected behavior**
Vehicles parked at bases with spare ammunition and repair facility capacity should replenish their ammunition over time

Rounds recorded in the vehicle equipment screen should give a value of `xxx/<max ammo>` but currently only show the max ammo

**Comment by XCOM-HUB** [comment]
The stream on Twitch is no longer with us 😞

**Comment by FilmBoy84** [comment]
> The stream on Twitch is no longer with us 😞

No worries, it was expected, I'll update to @Quickmind01 's youtube channel for the stream once full videos are up :)

**Comment by Kurtsley** [comment]
I haven't had a vehicle not replenish ammo, is this still an issue? I did notice that in the OG, the vehicles appear to rearm at exactly 5 minute intervals. It seems to work like the infiltration check works in OpenApoc right now. If that is the case, could the rearm code be added to the function that updates every 5 minutes in the gamestate?

**Comment by Quickmind01** [comment]
I just tested, and my Valkyrie instantly reloaded when it got back to base. I don't have the opportunity to test whether parking at a different base will reload the craft. I will mention that agents still don't seem to reload and restock when getting back to base, but that may need to be something for a different issue if there isn't one.

**Comment by FilmBoy84** [comment]
If this is resolved, I shall close the issue as it was identified on a stream from 2021

If it appears again, we can update or open a new issue :)
