### ISSUE TITLE
Rumble Cannon: no shots actually fired, only shot-sounds are heard...

### ISSUE THREAD

**Issue by darkspyre** [OpenApoc/OpenApoc#1083]
Hi,

in latest version 2da848cdae46476f39a889e554dc28f5ea9c3c9f from master branch there are no shots actually fired from the Rumble Cannon. Only the shot-sound itself is heard but nothing more happens. And it "shoots" really fast, so as the range of the Rumble Cannon is reduced to zero although the values in Ufopaedia look good to me. Other Griffon weapons like the Plasma Turret Cannon and GLM arrays are working as they should.

It's easy to reproduce; just start a new campaign on medium; buy one Griffon and immediately building-attack the Marsec warehouse where it comes out of from...

Any ideas how to get the Rumble Cannon properly working again?

TIA and KR,
Nils

**Comment by darkspyre** [comment]
forget to say that I'm running OpenApoc on Ubuntu 20.04. But I've observed the same behaviour on FreeBSD 13-STABLE as well...

**Comment by FilmBoy84** [comment]
Thanks for this, I shall do some investigation, the rounds disappearing - but still causing damage (i.e. the sprites disappear) is a known issue

But I'm not aware of the damage also disappearing

As to fire rate and other odd weapons and agent stat stuff - this is all partly tied to #997

**Comment by darkspyre** [comment]
https://user-images.githubusercontent.com/96187896/146251542-451e9d1a-ee20-44bc-9131-78cc8d23d044.mp4

**Comment by darkspyre** [comment]
Thanks for looking into that. I've made a short screencap to show the issue...

And just wanted to say that you guys do a really great job for keeping X-Com Apocalypse alive... Thank you very, very much for OpenApoc... :-)

**Comment by darkspyre** [comment]
okay, regarding the fire rate of the Rumble Cannon and checking the game timer during the test I think it shoots as fast as it should: 2.57rds/s. And that's how it feels...

So, sorry for that misinterpretation of mine...

**Comment by FilmBoy84** [comment]
Tested and confirmed here today also, thanks for the report

I've been digging through the #790 PR and cannot see clearly what may have affected just the rumble cannon

@Jarskih any ideas?

**Comment by FilmBoy84** [comment]
Further investigation reveals this also to apply to other self-regenerating human weapons such as the Laser Cannon series and the Laser Defence array

**Comment by FilmBoy84** [comment]
This is now fixed in #1093 and working in the latest builds
Closing
