### ISSUE TITLE
marketplace: clicking on one of the arrows on the side of the scroller decrements/increments by two...

### ISSUE THREAD

**Issue by darkspyre** [OpenApoc/OpenApoc#1084]
Hi,

in the marketplace screen a click on one of the arrows on the side decreases/increases by two instead of one. Is that intended?

I'm running it on Ubuntu 20.04...

TIA and KR,
Nils

**Comment by FilmBoy84** [comment]
You beat me to it, making videos of the Original Game behaviour and reporting this has been on the cards for a while, thanks for report, I will label this as confirmed and update with video of the expected behaviour and what OpenApoc actually does soon

**Comment by darkspyre** [comment]
Thanks for looking into that...

**Comment by darkspyre** [comment]
Many thanks for fixing - looks good now... :+1:
