### ISSUE TITLE
[QUESTION] Is it possible to change weapon stats?

### ISSUE THREAD

**Issue by SIREN87** [OpenApoc/OpenApoc#1087]
In openxcom you can change various values of weapon dmg, weapon accuracy etc. Is something like this possible here?

Also, the original idea by gollop was to make a living city where x organization fought y organization which in paper sounded great but in game it never happened. Will this be fixed here? 

Thanks and keep up the good work

**Comment by FilmBoy84** [comment]
Welcome Siren87

Thanks for your comments

It is already possible to mod existing weapons as well as add new weapons, equipment, aliens and even vehicles

If you are a member of our discord, check out the modding channels for further details

https://discord.gg/WwDaFS9

https://discord.com/channels/142798944970211328/402616863168659456

Organisations can be modified in relation to one another and, as long as you remove a building from one on each map, you can even add new organisatons to the city

Closing this issue as, for the most part, OpenApoc already does these things
