### ISSUE TITLE
No agent matching ID "AGENT_13"

### ISSUE THREAD

**Issue by SIREN87** [OpenApoc/OpenApoc#1089]
**BEFORE POSTING, HAVE YOU SEARCHED THE TRACKER FOR EXISTING COPIES OF THE PROBLEM?**
No because i dont know what the bug name is exactly. Std?

**Describe the bug**
Game crashes after an attack on sirius cult. 

**To Reproduce**
1. Load save
2. Tell the triton to return to base
3. press the fast timer
4. game crashes

**Expected behavior**
To return to base and continue my game

**Savegame**
https://www72.zippyshare.com/v/9FkVl7Uz/file.html

**Screenshots**
https://ibb.co/T4Ms5NZ

**Desktop (please complete the following information):**
 - OS: win10 64
 - OpenApoc Version latest version

**Comment by FilmBoy84** [comment]
This is another instance of the Agent_ID error well reported on this tracker

See the list of such crashes here
https://github.com/OpenApoc/OpenApoc/issues?q=is%3Aissue+is%3Aopen+agent+label%3A%22Agent+ID+Error%22

Thanks for the savegame; you can keep track of the various related bugs via the link above

Labels for this issue updated accordingly

**Comment by FilmBoy84** [comment]
Should be resolved by recent updates to master for new game starts

To resolve the issues already in this save, decompressing the save file and searching the XML files to remove whole references to "AGENT_13"
