### ISSUE TITLE
Inconsistent versioning

### ISSUE THREAD

**Issue by AMDmi3** [OpenApoc/OpenApoc#1097]
Could openapoc please use consistent versioning? For instance, https://github.com/OpenApoc/OpenApoc/tags shows 6 different versioning schemes, and on top of that the latest one is not monotonic and differs from the release name 20220608. I'm working on FreeBSD port of openapoc, and inconsistent versioning messes things up for me.

Since project goals mention [version 1.0](https://github.com/OpenApoc/OpenApoc/issues/265), I recommend to use versions compared lesser than 1.0 for now - that is, `0.something`.

**Comment by FilmBoy84** [comment]
Yep, that's my bad

I was using date on the git releases, but realised it was changing the entire appveyor release numbering this morning

I've therefore returned it to 0.2 - and the Appveyor build number as it was before February when I started with the YYYYMMDD format

Unless we hit 2023 before version 0.3 roadmap objectives are met (reach alpha state roadmap)

**Comment by AMDmi3** [comment]
> Thoughts?

Overcomplicated, not compatible with some repositories, tied to builds as opposed to source commits.
I once again suggest to use simple numeric-only version - symver, or, if you will, YYYYMMDD.

**Comment by FilmBoy84** [comment]
Releases are now using YYYYMMDD-XX format for numbering
