### ISSUE TITLE
Bugged text / images when opening equip agent screen with no agents available

### ISSUE THREAD

**Issue by dl471** [OpenApoc/OpenApoc#1100]
**Describe the bug**
The Equip agent menu is filled with placeholder text and broken images if the player opens it while having no agents available

**To Reproduce**
1. Fire all agents
2. Let the game time advance for a few seconds
3. Click the "Equip agent" button

**Expected behavior**
In the original game the menu would refuse to open under these circumstances.

**Screenshots**
![openapoc_agent_screen](https://user-images.githubusercontent.com/32369415/185526105-f8f8aa8c-5de0-4806-a79f-1ccdea9206ce.png)

**Desktop (please complete the following information):**
OS: Ubuntu 18.04.3 LTS
OpenApoc Version: Built from master at commit f1a3ecb

**Comment by FilmBoy84** [comment]
Can confirm this error with a new save and this build https://github.com/OpenApoc/OpenApoc/releases/tag/2022-v0.2-539

1) Agents appearing normally on game start
![image](https://user-images.githubusercontent.com/33913088/185604520-c5c0dff3-90eb-4cdd-a5d7-d5a5f2c19c8f.png)

2) All Agents (not scientists) fired
![image](https://user-images.githubusercontent.com/33913088/185604622-15ac23bd-f9c9-47f0-b8aa-a99aaaee9233.png)

3) Additional Bug with Agents NOT immediately disappearing from the equip screen if time is not progressed - they should. For some reason their health appears as 0 though
![image](https://user-images.githubusercontent.com/33913088/185604796-0906a720-9820-4317-ad63-5d8be1bc0161.png)

4) Move forward time 1-2 seconds to force a gamestate update
![image](https://user-images.githubusercontent.com/33913088/185604942-a80b66e0-1434-4948-94e6-45d531515eb1.png)

5) The Agent Equip Screen is now glitched
![image](https://user-images.githubusercontent.com/33913088/185605042-70a78ec7-213f-48ab-9d81-65b512834d75.png)

**Comment by FilmBoy84** [comment]
Thanks for the report @dl471 :beers:

**Comment by FilmBoy84** [comment]
Should be resolved by #1116
