### ISSUE TITLE
Clicking an icon does not bring up the equip menu

### ISSUE THREAD

**Issue by Kurtsley** [OpenApoc/OpenApoc#1127]
In the original game, when the icon of a vehicle or player is clicked, you are taken to the equip screen. Clicking the name will highlight the vehicle or player and not open the equip menu. In OpenApoc currently, clicking either side will only highlight the vehicle or player.

For example, clicking the icon on the left opens the equip menu for the vehicle, while clicking the name highlights the vehicle.
![apocscreen](https://user-images.githubusercontent.com/73447098/221334609-1a599c4b-8eb9-4871-8626-792127c7f922.png)

**Comment by kgd192** [comment]
The Equip Screen now opens on a RIGHT Clicks, looks like quality of life feature
