### ISSUE TITLE
Long messages in the message history menu are cut off.

### ISSUE THREAD

**Issue by Kurtsley** [OpenApoc/OpenApoc#1131]
**Describe the bug**
When a message in the message history menu is long enough to require multiple lines, the message is cut off on the top and bottom.

Example:
![menucutoff](https://user-images.githubusercontent.com/73447098/224473858-69635215-153c-4f37-bb2e-ea48af293259.png)

**To Reproduce**
1. Have any of your vehicles be destroyed by a UFO.
2. Observe the message in the message history menu.

**Possible Solution**
I haven't played the original game enough to know for sure, but it seems this was not an issue because the messages were shorter. In the following example, the "Vehicle Destroyed" message prefix is not present in the original game.

Example:
![menuorig](https://user-images.githubusercontent.com/73447098/224474252-4655d615-f8db-4c51-9b2b-a38a5b5937de.png)

Perhaps the simple solution could be implemented first while a more permanent solution is worked on. I spent some time looking at changing the height of the messages, but have been unable to sort it out.

**Comment by Kurtsley** [comment]
My apologies, I just noticed this already been reported. I would still like feedback on shortening the messages though.

**Comment by FilmBoy84** [comment]
> My apologies, I just noticed this already been reported. I would still like feedback on shortening the messages though.

Agreed, mimicking the Original by culling the extra prefix is the way forward

Ideally, we should be updating the forms to allow text wrapping as a long term solution - but for now, Original functionality should be priority :)

**Comment by Kurtsley** [comment]
I have addressed the vehicle destroyed message in a PR because it is the most common. There could be a situation where a vehicle recovered message will become too long and cause issues. I think this issue should be left open until a solution like the one above is implemented.

**Comment by FilmBoy84** [comment]
Resolved by #1175
