### ISSUE TITLE
Crash when entering building for tactical mission

### ISSUE THREAD

**Issue by ArcherZett** [OpenApoc/OpenApoc#1147]
Any change from geoscape to tactical - game just closes and nothing happens.
Last log data:

I bool __cdecl OpenApoc::Vehicle::popFinishedMissions(class OpenApoc::GameState &): Vehicle Wolfhound APC 1 mission "GotoLocation {68,98,1}" finished
I bool __cdecl OpenApoc::Vehicle::popFinishedMissions(class OpenApoc::GameState &): Vehicle Wolfhound APC 1 mission "InvestigateBuilding BUILDING_THE_OZONE_BUILDING" starting
I void __cdecl OpenApoc::VehicleMission::start(class OpenApoc::GameState &,class OpenApoc::Vehicle &): Vehicle mission InvestigateBuilding BUILDING_THE_OZONE_BUILDING checking state
I void __cdecl OpenApoc::VehicleMission::start(class OpenApoc::GameState &,class OpenApoc::Vehicle &): Vehicle mission InvestigateBuilding BUILDING_THE_OZONE_BUILDING: Pathing to entrance at {68,98,1}

**Comment by FilmBoy84** [comment]
I cannot replicate this problem

Can you please provide a savegame?

Also specify the difficulty level you were on and the building attended (It looks like the Ozone Building from that log but want to check)

Finally, can you let me know what the cd.iso source is please? STEAM/GOG/Original?

**Comment by ArcherZett** [comment]
Sorry, I managed to fix it mysleft. Problem was in corrupted ISO (I did an image from my very old CD-disk).
Issue closed.

**Comment by FilmBoy84** [comment]
No worries, glad you are sorted
Enjoy the game
