### ISSUE TITLE
Tooltips only partially working

### ISSUE THREAD

**Issue by Kurtsley** [OpenApoc/OpenApoc#1148]
The tooltips for the agents and vehicles are only working when you hover on a very specific spot on the icon. 

You have to hover just on the edge of the health bar to make the tooltip appear. This is the same for the agents list.
![test](https://user-images.githubusercontent.com/73447098/228929279-866b40e7-a94f-4324-a450-2d25a4954d31.png)

Having recently watched some of quickmind's stream, I noticed he requested tooltips in the options menu for items that are too long.
Browsing the options code, I see that it is implemented, but not working. 

```
sp<Control> OptionsMenu::createOptionRow(const ConfigOption &option)
{
	auto control = mksp<Control>();

	const int HEIGHT = 21;

	auto label = control->createChild<Label>(option.getName(), ui().getFont("smalfont"));
	label->Location = {0, 0};
	label->Size = {250, HEIGHT};
	label->TextVAlign = VerticalAlignment::Centre;

	/*
	auto value = control->createChild<TextEdit>(config().getString(option.getKey()),
	                                            ui().getFont("smalfont"));
	value->Location = {0, 0};
	value->Size = {250, HEIGHT};
	value->TextVAlign = VerticalAlignment::Centre;
	*/

	control->ToolTipText = option.getDescription();
	control->ToolTipFont = ui().getFont("smallset");

	return control;
}
```
Perhaps it's a hitbox type issue like the agent and vehicle list.

**Comment by FilmBoy84** [comment]
Verified, it does indeed appear to be a hitbox issue

I notice we specify height for the size, but no width?

**Comment by Kurtsley** [comment]
Well, the problem was I was looking at the wrong options menu. That is from the worthless option menu that is being removed. I just solved this by adding tooltip text to the in game options menu. Will put up a PR shortly.

**Comment by Kurtsley** [comment]
The agent and vehicle tooltips will take more time. I think this issue is more important because some of the options were too long to be read.

**Comment by FilmBoy84** [comment]
#1152 only partially resolves this issue, for that reason. I am re-opening this issue on the tracker and adding the WIP tag until resolved
