### ISSUE TITLE
Enforce cargo limits does not apply to craft in cityscape

### ISSUE THREAD

**Issue by Kurtsley** [OpenApoc/OpenApoc#1164]
As discussed before, cargo limits are still enforced in the cityscape even with the "enforce cargo limits" option turned off. My new idea is to completely remove the max cargo number when cargo limits are not being enforced.

For example, this is what an unloaded vehicle will look like:
![item1](https://user-images.githubusercontent.com/73447098/230700864-ee7c9d3a-b12f-40a9-a633-46e9e541929e.png)

Any cargo added will simply be shown as the current cargo on board:
![item2](https://user-images.githubusercontent.com/73447098/230700834-0983d4ee-65d8-48b9-b4ab-962f3d10545f.png)

**Comment by FilmBoy84** [comment]
Yep, that's clean and doesn't use any extra symbols / strings

I'd say go with that :)
