### ISSUE TITLE
Trivial/Reminders

### ISSUE THREAD

**Issue by Nurulinde** [OpenApoc/OpenApoc#1200]
Here are a few trivial things which some I assume are temporary tweaks to aid in playtesting but which will probably need to be changed before final release.  These are all of extremely low priority and probably don't warrant a separate listings, or perhaps even being mentioned at all.

- When starting a New Game, the player is given 12 Agents, but only 10 sets of Armor/Gear (I suspect this might be because the OG only gave the player 10 Agents)
- Agent XP/Stat gains seem to be very much accelerated in comparison to the OG.
- The "Stats" (Up/Down Arrow at the top right of the Agents portrait when Equipping Agent) seems to be unimplemented at this time.
- The selection of individual organizations to be displayed on the "Alien Infiltration" line chart seems to be unimplemented at this time.
- Tons of duplicate names for Agents/Scientists.
- Vendor Buying prices for some X-Com Alien Tech items is zero, the OG had some minimal value for items such as Brainsucker Launcher, Entropy Launcher, etc.

**Comment by Kurtsley** [comment]
I believe the first one has been taken care of in recent builds.

**Comment by FilmBoy84** [comment]
@Nurulinde Many thanks for the list - though it looks like you may be using an older version.

Please check https://github.com/OpenApoc/OpenApoc/releases and always start a new game (we're at Alpha state, so cross-version compatibility is not guaranteed and can lead to weird bugs)

#1174 resolves the agents on start issue

#613 is already there for the agent training issue and it is likely entwined with #997

The Stats organisation arrow does indeed appear to be unimplemented - I shall create a separarte issue for this (all issues are best reported individually for tracking fixes and implementation)

I shall create a separate issue for the Infiltration graph screen, currently this is only on the roadmap #263

#751 currently deals with the agent names issue

The marketplace errors are part of #1070 i shall add your further observations there

As many of these issues are already here on the tracker, I shall close this and create the two that are missing as separate entitites

Again, please check the releases page regularly for OpenApoc builds and always start a new game on upgrade

Thanks for the reports 🍻
