### ISSUE TITLE
Mouse List Scrolling Issue

### ISSUE THREAD

**Issue by Nurulinde** [OpenApoc/OpenApoc#1202]
This is not really an "Addition" to the game, nor is it really a bug, but rather a humble request for a small change to a small feature of the current game.  Right now, the player can use the Mouse Wheel to scroll down lists in the game, which is awesome... but... when you reach the bottom, an INSANELY loud beeping occurs warning the player they are at the bottom.  I wear headphones and this makes me want to smash my headphones onto the floor every time I reach the bottom.  Yes, I know there are volume control sliders in the Options, but every other sound volume in the game is about right.  Do we really need to have any sound at all when the mouse scrolling reaches the bottom of the list ?  It is not like reaching the bottom is an error or something.

**Comment by Kurtsley** [comment]
Could add this as an optionional feature I suppose.

**Comment by Kurtsley** [comment]
This is a game changer, I may never turn this off now.

**Comment by makus82** [comment]
I like that sound and its not so loud not INSANELY

**Comment by FilmBoy84** [comment]
Resolved as an option in #1204 closing this issue :)
