### ISSUE TITLE
Battlescape Defaults

### ISSUE THREAD

**Issue by Nurulinde** [OpenApoc/OpenApoc#1206]
When starting combat in the Battlescape, the Agents have a number of settings such as Stand/Crouch, Agressiveness(3), Crawl/Walk/Run, Shot Type(4), etc.... that need to be set.  In lieu of having an in-game interface to change these Defaults, It would be nice if the Defaults for these settings were loaded and read from an external file, like an INI, or TXT file, where a knowledgeable Player could change them once, an not have to change them at the beginning of every single battle.

**Comment by FilmBoy84** [comment]
An option to change these defaults is already under `Options -> More Options` in the game as seen here
![image](https://user-images.githubusercontent.com/33913088/234600256-79fd6ae4-b24f-4a2f-8316-06a4ba9449fa.png)

Whilst I agree, a further extension of this would be nice (allowing to choose not just run and crouch, but combinations including lying prone and walking) it is best suited for a MUCH later time in development

For that reason I will close this issue now and we can look at things post, eventual, 1.0 release
