### ISSUE TITLE
Agent Mouseover showing Agent name like OG does

### ISSUE THREAD

**Issue by Nurulinde** [OpenApoc/OpenApoc#1209]
Mousing over an Agent in the OG Battlescape caused a small floating box to pop up showing the Agents name.  It would be more than nice if this functionality was also included in OpenApoc.  It makes it much easier to reference an Agent in a potential Save Game submittal, rather than having to say "Agent #2 in Group #3"

**Comment by Kurtsley** [comment]
The battlescape tooltip issue was fixed recently if I recall correctly. Are you using the latest release?

**Comment by Nurulinde** [comment]
I downloaded it about 2 weeks ago... Version Date is 04-01-2023.  Has a newer version been released since then ?

**Comment by Nurulinde** [comment]
I found and downloaded the newest version (04-22-2023)

**Comment by FilmBoy84** [comment]
This does appear resolved in the most recent builds

The agent / vehicle name appears in most places on hover both in cityscape and battlescape screens

There is one exception - the vehicle equip screen doesn't show name when hovering over the vehicle list to the right

![image](https://user-images.githubusercontent.com/33913088/234607573-1a819a26-c8d9-4e2c-acca-24b93425c919.png)
![image](https://user-images.githubusercontent.com/33913088/234607603-4356786b-dce7-423b-bcd3-ffe0af9e5e1e.png)
![image](https://user-images.githubusercontent.com/33913088/234607652-b01449af-2494-4967-a735-dd3cc9518d53.png)
![image](https://user-images.githubusercontent.com/33913088/234607633-c8d5d7b9-9aa7-430b-a6b1-2a9bc3ebce50.png)
![image](https://user-images.githubusercontent.com/33913088/234607670-1dec2afe-e6fa-4d65-817a-b559fcc20a01.png)
![image](https://user-images.githubusercontent.com/33913088/234607752-8e60fd78-5b69-4e05-9741-287da2f1b37f.png)

**Comment by FilmBoy84** [comment]
> Did it work in OG for the vehicle equip? I don't think the names appeared in OG for squad assignment. I can hopefully fix later if so.

All appears as OG now TBH

I have been back and checked and they do not appear in those places :)

![image](https://user-images.githubusercontent.com/33913088/234624207-4f4a01ad-8a99-4c8e-a2ce-19aa645c7057.png)
![image](https://user-images.githubusercontent.com/33913088/234624223-61a157de-3568-41d2-9f38-4dd98e728fd4.png)
