### ISSUE TITLE
Bombs and grenades that will cause OpenApoc to CRASH

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1218]
- OS: Windows 11 Pro 22H2
- OpenApoc Version: 0.0.731
- List of Mod files in use: None

If you prime a bomb or a grenade, throw it close to you, quickly pick it up before it blows up, and also kill the last enemy before it blows up. End the mission, and then go to a new Battlescape event. When you start the next Battlescape event, the bomb/grenade will detonate and crash OpenApoc. This bug is preventable if you go to your base and unequip the primed and thrown bomb/grenade before starting a new Battlescape event.

**Expected behavior**
The bomb or grenade should not remember being primed, thrown, and picked up. It should forget being primed in the first place, or at least there should be an option to unprime a bomb/grenade as soon as you pick it up. If the enemy threw the bomb/grenade, then you shouldn't be able to unprime it. But it shouldn't cause OpenApoc to crash if you killed the last enemy before the bomb/grenade goes off, and then start a new Battlescape event without unequipping the bomb/grenade in your base.

**Savegame**
You will find the primed, thrown, and picked up bomb (Marsec High Explosive) on Mattias in this save file named "Maybe bug".
https://www.dropbox.com/s/ipv50pe5fzxaxpc/save_Maybe%20bug.save?dl=0

**Copy of your OpenApoc_settings.conf**
"Explosions damage instantly" is turned off.

**Comment by FilmBoy84** [comment]
Fixed by #1220

Appveyor builds will be ready in a couple of hours for you
