### ISSUE TITLE
CTD at city map (time compression)

### ISSUE THREAD

**Issue by APoniatowski** [OpenApoc/OpenApoc#1249]
**BEFORE POSTING, HAVE YOU SEARCHED THE TRACKER FOR EXISTING COPIES OF THE PROBLEM?**
If so, please add the following details to those existing reports. Use broad phrases and keywords when searching for maximal results - not all related issues may use the same terminology as you

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - OpenApoc Version [e.g. 0.386-42 - the number attached to the AppVeyor build]

**Describe the bug**
Crashed when in city map and after assigning research projects, then speeding time up to max

**To Reproduce**
1. Assigned first research projects after first alien mission
2. Set time compression to max
3. Wait a few seconds to maybe a minute
4. Crash (Segmentation Fault)

**Expected behavior**
Continue playing

**Savegame**
Please include a copy of your .save file with the bug
Save's can be found under the appropriate directory of the route folder where you installed OpenApoc if you used a "Portable" installation, or via %APPDATA% if installed on Windows as none-portable.

**Screenshots**
If applicable, add screenshots to help explain your problem. GitHub supports direct pasting if necessary.

**Additional context**
```bash
W static OpenApoc::AdjustTargetResult OpenApoc::VehicleTargetHelper::adjustTargetToClosestFlying(OpenApoc::GameState&, OpenApoc::Vehicle&, OpenApoc::Vec3<int>&, VehicleAvoidance) Target {108,52,3} was unreachable, side-stepping to  {109,54,8}.
W static OpenApoc::AdjustTargetResult OpenApoc::VehicleTargetHelper::adjustTargetToClosestFlying(OpenApoc::GameState&, OpenApoc::Vehicle&, OpenApoc::Vec3<int>&, VehicleAvoidance) Target {108,52,3} was unreachable, side-stepping to  {108,52,4}.
Segmentation fault (core dumped)
```
If there is a log output somewhere, I will paste it in the comments below

**Copy of your OpenApoc_settings.conf**
[Framework.Audio]
GlobalGain=20
MusicGain=20
SampleGain=20
[Notifications.City]
AgentArrived=1
AgentDiedCity=1
BaseDestroyed=1
CargoArrived=1
NotEnoughAmmo=1
NotEnoughFuel=1
RecoveryArrived=1
TransferArrived=1
UfoSpotted=1
UnauthorizedVehicle=1
VehicleDestroyed=1
VehicleEscaping=1
VehicleHeavyDamage=1
VehicleLightDamage=1
VehicleLowFuel=1
VehicleModerateDamage=1
VehicleNoAmmo=1
VehicleRearmed=1
VehicleRefuelled=1
VehicleRepaired=1
[Options.Misc]
ActionMusic=1
AutoExecute=0
AutoScroll=1
ToolTipDelay=500

**Comment by FilmBoy84** [comment]
I have not been able to replicate this under the latest builds

Can you please provide a savegame and confirm which build you are using?
