### ISSUE TITLE
Add a Credits Button to main menu that links to an appropriate, scrollable, screen of project contributors

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1256]
For some time now, we have lacked an appropriate place in-game to credit contributors to the project and with things like the Internet Games Data Base (see https://www.igdb.com/games/openapoc ) requiring video submissions of an in-game credit sequence or screen to appropriately list people there, it's probably something we should resolve

This became an issue in 2020, when the OpenApoc OST project artists requested IGDB credits in return for their work and needs to be done before we can look at releasing the OST (in addition to implementing the action music mixer)

It's also important for programmers, devs and asset creators to get recognition should they want it, thus opening this as a feature request.

I propose a button is added to the main menu that links to a screen, using existing assets, that allows scrolling of any credits within.

Exiting the screen returns the user to the main menu

**Comment by Kurtsley** [comment]
Could use the save game image, too boring?
Are we not allowed to modify these assets in any way? I was thinking a slightly blurred cityscape in the background would look better.

![2023-11-26 10_19_33- SAVEGAME  (imported)-1 0 (Indexed color 8-bit gamma integer, GIMP built-in sRGB](https://github.com/OpenApoc/OpenApoc/assets/73447098/bdd3aab4-7985-4da4-808a-7639c4af06c0)

**Comment by FilmBoy84** [comment]
That blue screen would be kind of nice TBH - I was originally thinking the brown one, but that's not as nice

Has the "OK" button for exit and we know from other new forms that adding a scroll is fairly simple

Sadly asset modifying creates a whole host of problems - not only do we have to distribute the modified asset with the build, we then also enter the issue of using Original Game Assets not provided by the end user - which crosses the line for us legally in terms of takedown risk

**Comment by Kurtsley** [comment]
I see. Any particular order for contributors or sections that need to be included?

**Comment by FilmBoy84** [comment]
Certainly the Git contributors - if only by username for now, we'd have to ask permission for full-names because of GDPR in the EU

We can always add/change/update things with future updates once the form is in place

Sections wise, I can really only see Developers (as per Discord list), Programmers, Testers and Translators for now as everyone else has inherently been on the mod side of things (and mods carry their own credits in Modinfo.xml)

**Comment by FilmBoy84** [comment]
Added in #1257
