### ISSUE TITLE
Organization list on Cityscape Needs Manual Update

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#1258]
**Desktop (please complete the following information):**
 - OS: Windows 10 x64 10.0.19045 Build 19045
 - OpenApoc Version 0.0.831
 - List of Mod files in use *and their version* separated by commas: Extended Weapons Mod 9.0D, OpenAPOC Original Sound Track 1.0

**Describe the bug**
When viewing the Organizations Tab and selecting the different Views, the list doesn't update, or, at least doesn't completely update. However, if I mouse over the list, it updates immediately.

**Expected behavior**
The list should update as soon as a View button is clicked.

**Savegame**
[save_Org Relations.zip](https://github.com/OpenApoc/OpenApoc/files/13533168/save_Org.Relations.zip)

**Screenshots**
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/ef6f1989-c068-40e1-828a-bd22a8dea8ee)
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/75bb3c9c-f31a-4498-b329-3dbe74e5b8b2)
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/f439882e-6806-4d09-a7be-608416c017b9)

[OpenApoc_settings.zip](https://github.com/OpenApoc/OpenApoc/files/13533166/OpenApoc_settings.zip)

**Comment by Kurtsley** [comment]
There are still a few issues with forms not updating unless interacted with. Fortunately this looks like an easy fix. Thanks.
