### ISSUE TITLE
Hovering over an agent stat bar should give the exact stat name and value in a tooltip presentation

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1260]
**Describe the bug**
As reported on Reddit, when hovering the mouse over any agent stat bar, the name of the stat and the stat value should be shown in a tooltip as per the OG

This does not currently occur in OpenApoc as it is unimplemented

![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/d4b925ed-b709-4408-9c89-4bb1196d728d)

**To Reproduce**
1. Start a new game
2. Open any agent inventory
3. Hover over a stat bar
4. No tooltip feedback is present

**Expected behavior**
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/5cc52fb6-2e4e-4d60-9131-0fe3922a89a6)

**Comment by Kurtsley** [comment]
The tooltips work, just not in the correct place. I haven't looked too close, but I think it has to do with the stats bar labels and graphics being a subform. It looks like the game only recognizes the tooltip hover when outside the main agent profile graphic or form.
 
![tooltip](https://github.com/OpenApoc/OpenApoc/assets/73447098/14d7afe0-ba86-4978-aa85-ab59f4879fb4)
