### ISSUE TITLE
X-COM Returning from XXXX at XXXX message not shown in message / news list after finishing a battlescape mission

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1267]
**Describe the bug**

In the original game, the status of X-COM after a battlescape mission was shown in the message/news list in a manner as follows
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/0fe13fd7-a9ee-443f-afa3-b32eab99a86e)

This does not currently occur in OpenApoc

**Expected behavior**
The messages shown in the Original Game on mission completion should be shown in OpenApoc and added to the city news ticker list

This includes messages relevant to raid / live alien / alien building / dimension travel and win / lose conditions

**Comment by Kurtsley** [comment]
Strange, I am seeing these messages in my game. I'm not sure ALL the relevant information is being shown as in the OG though.

**Comment by Kurtsley** [comment]
It looks like the intro message is only added to the ticker, so that seems to check out.

https://github.com/OpenApoc/OpenApoc/blob/56812f9ca8ff45cffc365459d8dc4425c8c3f904/game/ui/tileview/cityview.cpp#L1641-L1646

I can't recreate this at all, could you show it in a video? Is the game paused or running when this happens?

**Comment by FilmBoy84** [comment]
Good call on the pause, that seems to be the problem
If the battle is left to a paused cityscape, it only gets added to the message list AFTER you unpause

So update issue that needs resolution

The welcome message is the only other outstanding part of this problem and it's minimal - we can probably leave it as is because the game always starts on the same date.

**Comment by FilmBoy84** [comment]
It appears the welcome message does not appear in either BETA2 OG or Final Release OG
So that can be ignored

The message update issue is known for other forms and functions already

So will close this issue :)

FR OG
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/efaa2748-86ea-43b7-9d3f-cf3cebc0657a)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/5e0e383b-2983-4250-b9fc-2ce83a86fbd7)

BETA OG
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/ec5c56b6-62e1-4759-b2e4-eb242579e25e)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/d558805b-fcb6-4339-81a0-05b6dde8db84)
