### ISSUE TITLE
Squad spawn in a secluded dead-end

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1284]
- OS: Windows 10 x64 2020H2
 - OpenApoc Version : 20231203
 - List of Mod files in use : none

Starting an alien clearing raid mission in a factory, one squad spawned in a tiny closed corridor with no exit.

Save
[save_SecludedSpawn.zip](https://github.com/OpenApoc/OpenApoc/files/13760386/save_SecludedSpawn.zip)

Log
[log.txt](https://github.com/OpenApoc/OpenApoc/files/13760388/log.txt)

Settings
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/13760390/settings.zip)

**Comment by FilmBoy84** [comment]
I'll reference this in #1111 and change the title of that issue to track known map spawn bugs :)
