### ISSUE TITLE
Alien dimension cannot be assaulted

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1286]
- OS: Windows 10 x64 2020H2
 - OpenApoc Version : 20231203
 - List of Mod files in use : none

After researching the first alien building, it is not possible to enter and raid it to continue the storyline.

Save
[save_First Building Cant Assault.zip](https://github.com/OpenApoc/OpenApoc/files/13760396/save_First.Building.Cant.Assault.zip)

Log
[log.txt](https://github.com/OpenApoc/OpenApoc/files/13760399/log.txt)

Settings
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/13760398/settings.zip)

**Comment by FilmBoy84** [comment]
Your Biotrans is in the last building (Dimension Gate Generators)

I can move to the first building (Sleeping Chamber) and assault it correctly

![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/9ce8422a-eeef-429c-b53b-e92e8625c9ec)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/84573118-f9ae-4667-a602-a0071e73e295)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/058c057e-9bde-4ef1-a427-99e2bc9b063c)

**Comment by FilmBoy84** [comment]
There does appear to be an issue with craft entering the dimension not defaulting to finding a path to the next available alien building for the next mission (as it does in OG) but apart from that, assaults seem to be very much possible

**Comment by BeornTB** [comment]
Oh jeez, now I feel like a dummy. Thanks! 

I was indeed bamboozled by the absence of redirection, and by the similar shape of the first vs last building
