### ISSUE TITLE
The Optional OpenApoc Feature to Crash Vehicles instead of destroy them needs to explain that modules may be lost in recovered vehicles

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1287]
- OS: Windows 10 x64 2020H2
 - OpenApoc Version : 20231222
 - List of Mod files in use : none

Vehicles crash and lose items to the evil tow company mafia. Even if you tow them yourself with a valkyrie. QM talked about it on stream, pretty sure this is already reported and everything. This example has a lost accuracy module on a Griffon.

Save
[save_Crashed Lost Weapon.zip](https://github.com/OpenApoc/OpenApoc/files/13760400/save_Crashed.Lost.Weapon.zip)

Log
https://www.dropbox.com/scl/fi/42pekg5fyp0yl8k9hohg5/log.txt?rlkey=rxfrlce3ikdbe1exkg57ny0xf&dl=0

Settings
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/13760401/settings.zip)

**Comment by FilmBoy84** [comment]
This was a "feature" of the Crash recovery system - to ensure that X-COM doesn't unnecessarily benefit from turning the option on, and to encourage marketplace investment in new modules crashed vehicles will lose various bits of equipment as "destroyed"

This probably needs explaining in the tooltip for the option but otherwise is NOT a bug or issue per-se - simply a balancing function for allowing a feature cut from the original game

**Comment by Kurtsley** [comment]
Any suggestions for wording of the tooltip?

**Comment by FilmBoy84** [comment]
I'm not sure how much text space we have - there are FOUR options affecting crashes, one for unsupported ground vehicles, one for vehicles not capable of dimension jump, one for low fuel and one for low HP

I propose appending existing tooltips with `- Weapons and Modules may be lost in crash`

Unsupported Ground Vehicles Crash - Weapons and Modules may be lost in crash
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/97d017b7-8a19-4eb1-b0ce-dfef549d8e0a)

Uncapable Vehicles Crash when entering Gates - Weapons and Modules may be lost in crash
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/5bfeb7f3-751d-4e96-87db-29402c3f8870)

Vehicles Crash on Low HP - Weapons and Modules may be lost in crash
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/2f53530b-7402-4935-84d4-21d21abf9d50)

Vehicles Crash when out of Fuel - Weapons and Modules may be lost in crash
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/ee1a72d4-e1ef-423c-8f90-504451149052)

**Comment by FilmBoy84** [comment]
Longer Term, we should probably find a way to report which modules have been lost when a vehicle has been recovered and returned to base - not everyone will read the tooltip

**Comment by Kurtsley** [comment]
That's a good idea, of course there probably isn't an existing string for that message.

**Comment by ayrtondenner** [comment]
So should this issue be closed then?
