### ISSUE TITLE
[OG Error] The UFOPaedia entries for the Griffon Rumble Cannon and Plasma Turret are mistakenly swapped

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1289]
This one dates back to the OG: the UFOpaedia images for the Griffon's Rumble cannon and Plasma turret are mixed up.

**Comment by FilmBoy84** [comment]
Confirmed, this is an Original Game error and should be a relatively simple fix by appropriately calling the correct screen in ufopaedia.xml of the base mod distributed with the standard OpenApoc compile

For the Rumble Cannon `xcom3/ufopaedi/23tank4.pcx` should be `xcom3/ufopaedi/23tank2.pcx`
For the Plasma Turret Cannon `xcom3/ufopaedi/23tank2.pcx` should be `xcom3/ufopaedi/23tank4.pcx`

**Comment by Kurtsley** [comment]
Do we have a good first issue tag? This would be a good issue for someone looking to contribute.
