### ISSUE TITLE
Craft Options Post Mission

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#1295]
With a craft selected, when a mission is completed and the player returns to the Cityscape, the craft's aggression and height selections are grayed out as if not selected, but it shouldn't be possible to deselect these options. To replicate, raid a building and then immediately abort. When the cityscape loads, these selections will be blank. I also tried switching to a different tab prior to starting the mission and the result is the same. This is with build 20231214B along with EWM mod music mod.
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/02927cf0-93ed-4f6d-b2da-f3b7cd65e69d)

**Comment by Kurtsley** [comment]
I broke this, will fix it shortly.
