### ISSUE TITLE
Items Disappearing When Dropped on Equipment

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#1296]
Certain items can "eat" other items dropped on them while in the backpack. It appears to mainly be 2x3 items. Some items, the bottom right corner would trigger the dropping item to disappear, while some of the other squares could do it as well. Please see this video: https://youtu.be/JbxlEiftqcs

Prior to recording the video, I was getting grenades to disappear on the Devastator Cannon, but the video didn't show this so I'm not sure what the difference is. Weapons that use clips seem to be resistant to this issue from what I can remember. This also may lead into another issue related to inventory handling. When attempting to place an item over another in the backpack, sometimes the item will be placed in its previous location, sometimes it'll be placed next to the item you tried to place it over, and sometimes, it just goes on the ground. It appears to be based on where the first item is placed, specifically, how far to the right. This is somewhat shown in the video as well.

This is with build 20231214B along with EWM mod music mod.

**Comment by Quickmind01** [comment]
Follow-up: the Marsec Body Unit also causes this issue with the medi-kit in the bottom right corner.

**Comment by FilmBoy84** [comment]
Oh that's super weird, thanks for report

If one of us gets a save of this, please post here :

**Comment by BeornTB** [comment]
Replicated: IIRC I had just lost a cloaking device by misplacing it atop a stun grapple.

[save_Lost Cloak Item Bug.zip](https://github.com/OpenApoc/OpenApoc/files/13796888/save_Lost.Cloak.Item.Bug.zip)
[log.txt](https://github.com/OpenApoc/OpenApoc/files/13796889/log.txt)
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/13796890/settings.zip)

**Comment by dethstryke01** [comment]
Medkits also disappear when the attempt to equip them misses slightly. 

https://youtu.be/gAMibszWYPQ?t=3408

[save_medkit disappears.zip](https://github.com/OpenApoc/OpenApoc/files/14412032/save_medkit.disappears.zip)
[save_save 179.zip](https://github.com/OpenApoc/OpenApoc/files/14412033/save_save.179.zip)

**Comment by FilmBoy84** [comment]
Should be resolved by #1360
