### ISSUE TITLE
Day Number Did Not Increment

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#1299]
The save file shows I am on Day 27. When I complete the day and save again, it still shows Day 27. The next day then shows Day 28. I don't believe I used any time advancing debug commands during this play through and then saving some time later. This is with build 20231214B along with EWM mod music mod. The Battle save is where you need to start. Complete the mission, and then complete the day to see this bug. The Date Bug save is the next day where the bug takes place.
[Day After 27 is 27.zip](https://github.com/OpenApoc/OpenApoc/files/13774482/Day.After.27.is.27.zip)

**Comment by FilmBoy84** [comment]
I cannot replicate this

Starting with the mission save, i finish the mission, send the griffons in the city home and use debug to crash all the space liners that are slowing the game (I believe this save was made before a fix was implemented)

The game proceeds past 2nd April and moves to 3rd April via the end of week as expected

![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/d19064e1-b5fb-48f7-b420-550e04bc5785)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/0af0e065-1b0b-4bf8-9c32-0bcd04aa1bf5)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/aecec085-1b66-40c6-b38c-bba59b73bcc3)

Save before midnight of 2nd - 3rd April attached

[save_Before Day End 1.zip](https://github.com/OpenApoc/OpenApoc/files/14446553/save_Before.Day.End.1.zip)

**Comment by Quickmind01** [comment]
I can check this later (getting ready to head to bed), but what I'm referring to is the in the save name information where it shows what Day you're on. It appears the number doesn't increment if you save before allowing any time to pass. I thought it was still occurring in the current version, but I could be wrong.

**Comment by Quickmind01** [comment]
Here is what I was referring to. Day 67 Test should show Day 68, but because time hasn't been allowed to pass, it still shows Day 67. This was from loading Superhuman 1.
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/f5fa8e4e-9214-4887-b0e1-d3bc363ed569)

**Comment by Kurtsley** [comment]
I see what you mean, the score screen shows the following day but the next day doesn't happen until at least one second ticks by. In OG, the new day actually starts at 00:00.

**Comment by FilmBoy84** [comment]
This appears resolved by #1368
