### ISSUE TITLE
Transfer menu graphic glitch

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1301]
- OS: Windows 10 x64 2020H2
 - OpenApoc Version 20231222
 - No mods

Sorry no save, I wasn't diligent with that one and didn't think the screenshot got recorded either. I found it after the uninstall of the last build. But here goes:

![screenshot001](https://github.com/OpenApoc/OpenApoc/assets/46300745/7dfbfc0f-37ea-49c4-b9a2-ccd5c434cd9c)

I've been getting a lot of glitchy menus with doubled-up images on the left-hand side. This has a hold-over of a personnel file (can't remember if scientist or soldier, scientist IIRC) where it should only display the stun grapple.

Edit: I'm replicating this in build 20231225-3, in the item transfer menu, after hovering over a soldier (not scientist), then all other items (not personnel) will carry on displaying the soldier's face and name on the left hand side.

**Comment by FilmBoy84** [comment]
This should be resolved by #1303 
Closing :)
