### ISSUE TITLE
Alien Containment accounting: 2x each item and Brainsucker Pod = 80%

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1302]
- OS: Windows 10 x64 2020H2
 - OpenApoc Version 20231225-3
 - No mods

**Describe the bug**
Alien containment sometimes counts items in 2 categories that each take their own separate % of space. Also, Brainsucker Pods currently count as 80% of containment space _each_.

![screenshot002](https://github.com/OpenApoc/OpenApoc/assets/46300745/c22b6f35-0d37-46a4-b22a-966f9e060234)

**Comment by FilmBoy84** [comment]
For anyone working on this issue, please see also issue:

#369 
#608 

And a potential way to improve handling overflows when implementing the OG "Alien Containment is full" screen with extras

#1203

**Comment by BeornTB** [comment]
Oh and the containment wasn't tared at 0%, once everything in it was incinerated, the balance was at -20% (or was it -19%...). So 6 brainsucker pods at 80% each (!) would be 480% space utilization, but the empty containment was below 0%, and the numbers don't add up to 480 either.
