### ISSUE TITLE
[QoL] Optional Feature to Prefix None-X-COM vehicle names with a universal symbol to set them apart from player units

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1312]
It became apparent on @quickmind01 's Stream of the 31st December 2023 that it is not always easy to differentiate X-COM Vehicles from Organisation Vehicles by name alone as the vehicles are assigned name by `<Vehicle Type> <Number>`

For this reason, a QoL option to allow NONE-X-COM craft to be prefixed with a universal character supported by the game fonts should be implemented

I propose that X-COM Craft continue to be named as normal, though none-XCOM craft are prefixed by a `*`

This will break immersion in a minimal manner and should only be presented as an optional feature under the `More Options-->Cityscape` list in game

Thus in an example where 324 is the vehicle number, the X-COM Hawk Air Warrior would appear as `Hawk Air Warrior 324` but a none-X-COM Hawk would appear as `* Hawk Air Warrior 324`

**Comment by Quickmind01** [comment]
Simply having an asterisk is a welcome improvement and would be acceptable for a first step. Unless epic battles are anticipated where you'll want to know who owns each vehicle, having more than one symbol may be unnecessary, but an option for more would be nice. Thank you for adding this request.

**Comment by BeornTB** [comment]
How about only renaming the XCom craft with the prefix : "X-COM Hawk Warrior 1" and that way none of the immersion is affected, and your ownership is emphasized?

**Comment by FilmBoy84** [comment]
> How about only renaming the XCom craft with the prefix : "X-COM Hawk Warrior 1" and that way none of the immersion is affected, and your ownership is emphasized?

The main issue is string length - text often goes out of bounds with more than a single character addition

The Original Game just numbered the craft for X-COM in the range 1-99 after the vehicle type counting from the first craft that X-COM acquired from that type and counting up

Three digit numbers were almost exclusively other organisations

So we should probably try and replicate that too

**Comment by SirPlusse** [comment]
Potential compromise between owner prefixes and string length: Triple digits don't seem to be an issue, so maybe make X-COM craft have a default designation along the lines of (craft name) X25? Like, preface the number with an X so you know it's yours? You'd probably need to strike an extremely fine balance between performance and attrition to go above 50 or so, so triple-digit X-COM craft are unlikely to be an issue here.

Though yes, just putting an asterisk (or an X, to abbreviate Beorn's alternative) at the start would probably be more eye-catching...

**Comment by FilmBoy84** [comment]
X is definitely a reasonable prefix to use and is in the game's fonts

The longest vehicle name in the OG is the `Valkyrie Interceptor ####` at 25 characters including spaces

If we take the OG approach of generally only awarding X-COM craft the first 1-99 numbers in a linear assignment according to purchase/construction per vehicle type and any other organisation is allotted in the 100-9999 range recycling destroyed vehicle numbers as necessary if, for whatever reason, we exceed 9999 then this would resolve a lot of issues

It would then also allow the option to have X-COM Craft assigned with the prefix `X` or `*` up to `*99` in normal use or `*999` if vehicle IDs need to be recycled from destroyed IDs in the unlikely event that X-COM exceed 99 vehicles of one vehicle type but still not impinge on the other orgs 3-4 number ID system

**Comment by XCOM-HUB** [comment]
I have noticed that whenever I buy a new craft, the number of the craft does not increment by 1, but instead it jumps to a seemingly random number like 91. Maybe it counts all the crafts that is in use by different organisations besides X-COM!? In the original game it should always increment by one, disregarding all other vehicles of the same type owned by other organisations.

![Skärmbild 2024-04-13 010722](https://github.com/OpenApoc/OpenApoc/assets/55395993/6b6465a6-306e-4ace-81fe-d554fd024384)

**Comment by ayrtondenner** [comment]
> I have noticed that whenever I buy a new craft, the number of the craft does not increment by 1, but instead it jumps to a seemingly random number like 91. Maybe it counts all the crafts that is in use by different organisations besides X-COM!? In the original game it should always increment by one, disregarding all other vehicles of the same type owned by other organisations.
> 
> ![Skärmbild 2024-04-13 010722](https://private-user-images.githubusercontent.com/55395993/322157815-6b6465a6-306e-4ace-81fe-d554fd024384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjE0NTIsIm5iZiI6MTcxMzAyMTE1MiwicGF0aCI6Ii81NTM5NTk5My8zMjIxNTc4MTUtNmI2NDY1YTYtMzA2ZS00YWNlLTgxZmUtZDU1NGZkMDI0Mzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1OWI5ZjExNmZmNzdmOGMxNzUxZTMzYTA4MDdiOTcyOGRhODU2NThiNjM5M2M0ZmJjMzQ5Y2UzYzYzZjUwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miF-QJvf63DOyV1w_tiBKcPLvWWtweMCpnUrH-E-DXo)

I raised issue #1404 for this bug.

**Comment by ayrtondenner** [comment]
> Thus in an example where 324 is the vehicle number, the X-COM Hawk Air Warrior would appear as Hawk Air Warrior 324 but a none-X-COM Hawk would appear as * Hawk Air Warrior 324

> For example, with the prefix enabled the highest X-COM Craft number with the longest name would be `Valkyrie Interceptor *999` or just short of 1000 interceptors of that type

So, is it going to be 1) `"* <vehicle-type> <number>"` or 2) `"<vehicle-type> *<number>"`?

**Comment by XCOM-HUB** [comment]
@ayrtondenner How do you "raise" an issue? Does it cost real money? I am not that knowledgeable about GitHub and its different functions.

**Comment by ayrtondenner** [comment]
> @ayrtondenner How do you "raise" an issue? Does it cost real money? I am not that knowledgeable about GitHub and its different functions.

Nope, you do it at no cost. Feel free to raise issues, just check if it's not already submitted before. And don't be afraid of asking questions!

**Comment by FilmBoy84** [comment]
> So, is it going to be 1) `"* <vehicle-type> <number>"` or 2) `"<vehicle-type> *<number>"`?

Definitely 1) As you can spot at a glance when scrolling a list without having to look across to the number

**Comment by XCOM-HUB** [comment]
> > So, is it going to be 1) `"* <vehicle-type> <number>"` or 2) `"<vehicle-type> *<number>"`?
> 
> Definitely 1) As you can spot at a glance when scrolling a list without having to look across to the number

I also vote for number 1.

**Comment by FilmBoy84** [comment]
**Visual element ready for merging in #1405**

It still needs a functional solution
