### ISSUE TITLE
Base 2 Research Options Show Base 1 Research Options

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#1314]
This is with build 20231228-6-g09804893 and also using EWM and music mods.

Steps to reproduce.
1. Go to Research and Manufacture screen and make sure Base 1 is selected. Close the screen.
2. Click on the QP tab and select any scientist, then click the Research and manufacture button.
3. Click the Assign Project button.
4. You will see these items available for research (not including the Retaliator as that's universal). They are only at Base 1.
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/f2cacbed-20ff-4826-a1fd-01b1e9752659)
5. Click any of the three and click OK.
6. Allow time to pass. Base 2 will begin completing research for items they don't have access to. The research will complete fine with no errors.

After further review, this seems to stem from something else. Base 1 appears to default to QP when selected. Without a QP lab, no labs are selected, and it appears to be using Base 2's lab. Even with a different lab selected in Base 2, when switching to Base 1, it defaults to QP and Base 1's researchable topics are available, but it uses Base 2's lab. Steps 1 and 2 above can be skipped, I believe, as long as you select Base 1 and don't select any facilities. However, if you do select a facility and go back to the cityscape, if you click on the Research and manufacture button under the QP tab, it will still lead to the same results.

I think when selecting Research and manufacture, either the facility should be left blank (right now, it shows QP as the lab chosen
![image](https://github.com/OpenApoc/OpenApoc/assets/51022165/1ddfb472-8911-439f-b7a8-cfcd2112ae80)
), or it should attempt to default to the first lab available if the button used in a cityscape tab doesn't have a corresponding lab available.

https://youtu.be/cTJE-msaWH0

[save_Superhuman 1.zip](https://github.com/OpenApoc/OpenApoc/files/13813120/save_Superhuman.1.zip)

Maybe related to https://github.com/OpenApoc/OpenApoc/pull/982 ?

(Side note: as I was typing this all out and making the video, the game was running in the background. After a while (maybe 15-20 minutes?), the game locked up and it appeared to cause an infinite loop of music playing attempts. I seem to see this regularly on stream. From what I remember, the game was paused. The log file quickly got up to 3.85 GB. Here is a link for the 145 MB file with the music loop mostly deleted https://drive.google.com/file/d/1HLhAxPO9OlMS2HGePslltwhWy2uNd5bU/view?usp=drive_link)

**Comment by FilmBoy84** [comment]
This should be resolved by #1305 and a number of other recent merges to allow the selected scientist to direct which base and facility is selected :)
