### ISSUE TITLE
Primed grenade that "activates now" should not explode on top of soldier rather than remaining in inventory at end of turn (resolved)

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1331]
I remember doing this plenty of times. 

https://youtu.be/Lgxlf0U-09I?t=3532

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use

[save_test 7.zip](https://github.com/OpenApoc/OpenApoc/files/14166081/save_test.7.zip)

[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14166082/settings.zip)

**Comment by Kurtsley** [comment]
Here's what I found testing this in OG and OpenApoc:

In the OG, the "Activate Now" setting acts like setting an impact trigger. If you set a grenade to activate now, it will only go off if thrown or dropped. Leaving it in the inventory or placing it on the ground will not set it off. In OpenApoc, the grenade will go off if placed on the ground. This is not correct, but could have been a QOL thing.

The "Activate end of turn" setting in OG will make the grenade go off when the end turn button is pressed. This happens even if the grenade is in the inventory. In OpenApoc, placing the grenade in the inventory will delay this action until it is placed on the ground or thrown. It seems the timer doesn't start until the grenade is removed from the inventory or hand.

When selecting "Turns before activation", the grenade will go off at the end of the alien turn that you select. Both games seem to work the same, minus the timer not starting when in the inventory for OpenApoc.

I think the wording of these options is very strange. I would think that a primed grenade should go off even if the soldier is holding it.

https://www.youtube.com/watch?v=0vW7cGPo0vs

FYI your video links aren't pointing to the actual videos, they point to this: https://github.com/OpenApoc/OpenApoc/issues/url

**Comment by dethstryke01** [comment]
I just tested it in the original and I can confirm that if the grenade is primed to "activate now" and remains in inventory until the end of the turn, it does not explode. In my test the "activates at end of turn" grenade also did not explode in the inventory. I'm not 100% sure why I remember that they did this, but it looks like the current behavior in OpenApoc is right. I'll also work on fixing those links, thanks for the heads up.
