### ISSUE TITLE
Friendly soldiers become stuck in slow motion

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1335]
https://youtu.be/U8FNmmOGJZg?t=5079

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use
[save_test 10.zip](https://github.com/OpenApoc/OpenApoc/files/14183242/save_test.10.zip)
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14183248/settings.zip)

**Comment by FilmBoy84** [comment]
I cannot see what the problem is clearly? 

Are you able to explain?

Sometimes the animation seems slow - but that's often how an agent with a heavier weight or weaker strength varies their movement speed

**Comment by dethstryke01** [comment]
I'll close this because I remembered that it is possible for that guy to move so unbelievably slowly if he has extremely low stats (stamina, I think?)
