### ISSUE TITLE
Multiworms can die and spawn zero hyperworms

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1338]
https://youtu.be/-029oEE0ynE?t=6450

Save made just after he died:
[save_zero hyperworms.zip](https://github.com/OpenApoc/OpenApoc/files/14237962/save_zero.hyperworms.zip)

In this save the multiworm is still alive, and he still dropped zero hyperworms when I replayed the situation again.
[save_38.zip](https://github.com/OpenApoc/OpenApoc/files/14238009/save_38.zip)

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use

[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14238013/settings.zip)

**Comment by FilmBoy84** [comment]
What did you kill the multiworm with?

Some weapons, such as disruptors, plasma and lasers will kill them without erupting

These weapons count as "none-violent" and are also the only ones that can kill a popper without exploding it in the OG

**Comment by FilmBoy84** [comment]
Ah, i see from your video, it's a plasma gun
Yeah, these do not erupt multiworms and are one of the few weapons that avoid doing so in the early game

Things appear working as intended and mods can already change this so will close as a none-issue unless you find a "violent" weapon that should cause worms to erupt, but does not

**Comment by dethstryke01** [comment]
No kidding, I had no idea that was the case. Issue resolved.

**Comment by XCOM-HUB** [comment]
I recently killed a Multiworm with my laser sniper rifle in OG, but it didn't prevent 4 Hyperworms from hatching. Killing Multiworms with lasers will not always prevent the little bastards from hatching. This should be replicated in OpenApoc.

**Comment by XCOM-HUB** [comment]
I can confirm that killing a Multiworm with a Disruptor Gun in the Original Game did not prevent 4 Hyperworms from hatching.

**Comment by dethstryke01** [comment]
I've seen that happen a few times with both disruptor guns and plasma guns, but it seems like the hyperworms don't drop around 3/4 of the time. Not sure what might be going on with that, but I think the way it currently works in OpenApoc is fine.

**Comment by XCOM-HUB** [comment]
I don't know exactly how it works in OpenApoc. Does the Multiworm in OpenApoc not spawn any Hyperworms when killed with Lasers, Plasma and Disruptor beams?

**Comment by dethstryke01** [comment]
I think it's plasma guns, disruptors, and devastator cannons that prevent hyperworms from dropping. Maybe others? I don't think lasers are one of them.

**Comment by XCOM-HUB** [comment]
I think that we should figure out exactly how the Original Game calculates the chances of preventing Hyperworms from spawning when using beam weapons (Lasers, Plasma and Disruptors), and when we do figure it out we should implement it in OpenApoc.
