### ISSUE TITLE
Option: Automatically reload ammo only of the same type

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1340]
This situation demonstrates why I think this feature would be nice. 

https://youtu.be/mA_C0VO3cpo?t=10196

**Comment by steveschnepp** [comment]
What's the original game behavior?

**Comment by dethstryke01** [comment]
I just ran a quick test, and it looks like the original game automatically reloads with the same type of ammo as its first preference, and then checks for any available ammo and automatically reloads that as well. I think it would be a nice quality of life feature if OpenApoc had an option that would specify that the gun should only be reloaded with the original ammo.  As a player I prefer AP ammo quite a lot over high explosive or incendiary ammo, and I also tend to prefer to rush to close range rather than sitting back and shooting. With that setting turned on I could bring all three ammo types as options without needing to worry about setting my own people on fire accidentally at close range.

**Comment by FilmBoy84** [comment]
This should be resolved in #1356

Please open new issues regarding any problems with multiple ammo types in the late game referencing both this issue ( #1340 ) and #1356
