### ISSUE TITLE
Removing the engine of a vehicle at a second base without storage causes a crash

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1350]
https://youtu.be/AFcoQnEF-Yc?t=302

[save_save 136.zip](https://github.com/OpenApoc/OpenApoc/files/14359641/save_save.136.zip)

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14359648/settings.zip)

**Comment by Kurtsley** [comment]
I found that this isn't a storage issue per se, it's a fuel issue. This can be replicated at your own base right at the start of a game. Steps from start of game:

- Sell all your fuel immediately
- Send a craft on a trip to burn fuel
- When it gets back, remove engine and re-attach
- Error is thrown

It looks like the engine has no owner, thus the failed to reload message fails.

**Comment by FilmBoy84** [comment]
This should be partially resolved by #1359 so closing

However, there remains an issue with no message being presented to the player for a lack of fuel at base we need further testing and information on as it presents - please open or append existing dedicated issues regarding this as incidents occur
