### ISSUE TITLE
Items sometimes disappear when equip attempt misses 

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1355]
https://youtu.be/gAMibszWYPQ?t=3408

[save_save 179.zip](https://github.com/OpenApoc/OpenApoc/files/14387162/save_save.179.zip)
[save_medkit disappears.zip](https://github.com/OpenApoc/OpenApoc/files/14387164/save_medkit.disappears.zip)

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14387170/settings.zip)

**Comment by Kurtsley** [comment]
Probably the same as #1296. Grenades are also able to be loaded as clips in certain weapons. This causes the game to crash of course. I think this has something to do with how the game tries to snap equipment into the nearest open slot. IIRC items only disappear when placed near the right side of another item.

**Comment by dethstryke01** [comment]
I'll merge this with #1296
