### ISSUE TITLE
APC fails to auto-return at mission completion.

### ISSUE THREAD

**Issue by icarus7234** [OpenApoc/OpenApoc#1377]
Build OpenApoc-20240306. No mods. Windows 10.

APC isn't returning after completing an 'alert' mission - the ticker says it is returning as the mission closes, but it never appears on the map after unpausing the game. Even ramping the game speed up won't see it ever leave, but it can be told to manually return to base - an order which is will immediately comply with and succeed at.

I've re-run the mission 4-5 times now, it doesn't appear to change the behaviour.

![screenshot0022](https://github.com/OpenApoc/OpenApoc/assets/5144006/6325e12e-d89e-4435-b9fd-1d5486e522dc)

Save file **[Game 3-8]** has the vehicle 'en route' to the mission, save file **[Game 3-8.5]** is taken immediately on mission complete before unpausing.

[Game 3, Saves 8 + 8.5.zip](https://github.com/OpenApoc/OpenApoc/files/14644981/Game.3.Saves.8.%2B.8.5.zip)

**Comment by FilmBoy84** [comment]
This appears resolved in #1379

Any further issues please open a new issue with a save-game and log and reference this one
