### ISSUE TITLE
Workshop Crash on Not Enough Funds

### ISSUE THREAD

**Issue by KMickle** [OpenApoc/OpenApoc#1378]
- OpenApoc Version: _20240315_0_g3273d585
 - List of Mod files: Extended Weapons Mod 8.1

**Describe the bug**
I have a Workshop at Base 5, that is about to finish their work on `Retaliator`. There are more `Retaliator`s in production queue. There is not enough money to start the next production cycle.

**To Reproduce (Scenario A)**
1. Load the enclosed save game;
2. Unpause the game;
3. At 05:00 game time, the game freezes, the sound stutters;
4. In several seconds (real time), the game crashes with no error message and nothing useful dropped in log.

**To Reproduce (Scenario B)**
1. Load the enclosed save game;
2. Go to Base 5, Large Workshop 1. Cancel the production order;
3. Unpause the game;
4. The game proceeds as expected.

**To Reproduce (Scenario C)**
1. Load the enclosed save game;
2. Go to Base 5, Large Workshop 1. Reduce the ordered amount to `1`;
3. Unpause the game;
4. There is a 'Reassign the Workshop' notification. The game proceeds as expected.

**Expected behavior**
In Scenario A, the production should halt and the warning message should appear when there is not enough funds to continue; just as it happens in Scenarios B and C. 

**Savegame**
The compressed save is included, 5 minutes (game time) before the crash. I'm also including the log file, but it seems of little use.[log.zip](https://github.com/OpenApoc/OpenApoc/files/14672971/log.zip)
[653.zip](https://github.com/OpenApoc/OpenApoc/files/14672975/653.zip)

**Additional context**
Note that this only happens to the `Retaliator` order: the other manufacturing orders fail gracefully.

**Comment by Kurtsley** [comment]
Leaving this here for future reference:

https://github.com/OpenApoc/OpenApoc/blob/b3221cb1d8298992cd3770c47365c73bd75cda13/game/ui/tileview/cityview.cpp#L4343-L4347

The game crashes at line 4347, but it is the result of the value of line 4344. Looks like some sort of access error. First look shows the item_name value getting corrupted when the itemId is swapped on the last check.

**Comment by JonnyH** [comment]
Hmm, looks like it's trying to use a MANUFACTURE ID as a RESEARCH topic ID  - log just as it fails, including asan output:

```
W void OpenApoc::StateRef<T>::resolve() const [with T = OpenApoc::ResearchTopic] ResearchTopic object has invalid prefix - expected "RESEARCH_" ID "MANUFACTURE_RETALIATOR"
W void OpenApoc::StateRef<T>::resolve() const [with T = OpenApoc::ResearchTopic] ResearchTopic object has invalid prefix - expected "RESEARCH_" ID "MANUFACTURE_SMALL_DISRUPTION_SHIELD"
W void OpenApoc::StateRef<T>::resolve() const [with T = OpenApoc::ResearchTopic] ResearchTopic object has invalid prefix - expected "RESEARCH_" ID "MANUFACTURE_MEDIUM_DISRUPTOR_BEAM"
OpenApoc/game/ui/tileview/cityview.cpp:4344:59: runtime error: member access within null pointer of type 'struct element_type'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7612==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000a8 (pc 0x7f9a6c37ad9c bp 0x7fff94dc8660 sp 0x7fff94dc5dd0 T0)
==7612==The signal is caused by a READ memory access.
==7612==Hint: address points to the zero page.
    #0 0x7f9a6c37ad9c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x162d9c) (BuildId: af223756d0758d25a2882e3ab6e4d8c81b1ab903)
    #1 0x5602d61cbe0b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/13/bits/basic_string.h:1608
    #2 0x5602d61cbe0b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/13/bits/basic_string.h:814
    #3 0x5602d61cbe0b in OpenApoc::CityView::handleGameStateEvent(OpenApoc::Event*) OpenApoc/game/ui/tileview/cityview.cpp:4344
    #4 0x5602d624b5e0 in OpenApoc::CityView::eventOccurred(OpenApoc::Event*) OpenApoc/game/ui/tileview/cityview.cpp:3413
    #5 0x5602d572f57e in OpenApoc::Framework::processEvents() 
OpenApoc/framework/framework.cpp:491
    #6 0x5602d5749ce2 in OpenApoc::Framework::run(std::shared_ptr<OpenApoc::Stage>) OpenApoc/framework/framework.cpp:343
    #7 0x5602d55e2705 in main OpenApoc/game/main.cpp:22
    #8 0x7f9a6b9051c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #9 0x7f9a6b90528a in __libc_start_main_impl ../csu/libc-start.c:360
    #10 0x5602d55e20b4 in _start (/home/jonny/build/OpenApoc/sanitize/bin/OpenApoc+0xbe520b4) (BuildId: 989f7870fc7d987b96bc6fa8934d86c70b9211fd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libstdc++.so.6+0x162d9c) (BuildId: af223756d0758d25a2882e3ab6e4d8c81b1ab903) in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
==7612==ABORTING
```

So the event topic->idemId isn't a valid MANUFACTURE ID for the GameEventType::ManufactureHalted event.

**Comment by JonnyH** [comment]
So the event's itemId is "VEHICLETYPE_RETALIATOR", but then uses that to index the instantiated vehicle array - not vehicle *types*. So this will fail, unless you happen to have a vehicle with the ID "VEHICLETYPE_RETALIATOR"

So it looks like the "manufacturing halted" message will always crash for vehicles.

So the ResearchTopic "MANUFACTURE" prefix error doesn't seem directly related to the crash, but probably an issue that we need to fix anyway. If only to verify that the MANUFACTURE_* IDs are valid for RearchTypes and removing the warning :)

**Comment by JonnyH** [comment]
Thanks for the report and save - I think the above PR should fix this specific crash

**Comment by Kurtsley** [comment]
Strangely enough, the game wasn't crashing when sending a manufacturing halted event for any other workshop besides workshop 1. Workshop 2 was also making retaliators and the manufacturing halted message worked fine
