### ISSUE TITLE
Character sheet claims I have done 2 missions despite only having done my first mission

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1394]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: 0.0.999
 - No Mods

![Skärmbild 2024-04-04 074308](https://github.com/OpenApoc/OpenApoc/assets/55395993/3b10e25f-1982-41e4-a854-479c69387b16)

Save File (before the first mission): 
[Beginning.zip](https://github.com/OpenApoc/OpenApoc/files/14862201/Beginning.zip)

Edit: I have figured it out. The mission counter on the character sheet will increment with 1 every time you load a saved game in the battlescape. Try to save and load in battlescape and see the mission counter on your agents increment with 1. The more you save and load on a mission, the more missions you will accumulate on your character sheet.

**Comment by Kurtsley** [comment]
Could not replicate on my end. I did one mission and it correctly incremented the mission count by one. Anything special happen during this first mission?

**Comment by FilmBoy84** [comment]
I too cannot replicate this

I will leave open for now, but if no further information can be provided I shall close in 1 week~ from now

**Comment by XCOM-HUB** [comment]
I played the mission in turn-based mode. Nothing special happened on the mission.

**Comment by FilmBoy84** [comment]
Ah, i only play RT, so thanks for heads up that TB may be an issue :)

**Comment by XCOM-HUB** [comment]
I have figured it out. The mission counter on the character sheet will increment with 1 every time you load a saved game in the battlescape. Try to save and load in battlescape and see the mission counter on your agents increment with 1. The more you save and load on a mission, the more missions you will accumulate on your character sheet.
