### ISSUE TITLE
Buying and selling in OpenApoc is reversed compared to original

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1399]
In the OpenApoc buying screen, if I buy something the number of things I'm buying appears on the left: 

https://youtu.be/TS0zEgBkTuk?t=30

In the original, the number of things I'm buying appears on the right: 

https://youtu.be/8B9uJud-RkA?t=25

Probably not the biggest problem in the world, just thought I'd point this out. 

OpenApoc 20240409
Extended Weapons Mod 9.01
Falcon Weapons Platform 1.4
Windows 10 22H2
[OpenApoc_settings.zip](https://github.com/OpenApoc/OpenApoc/files/14921620/OpenApoc_settings.zip)

**Comment by Kurtsley** [comment]
Unchecking this will restore the OG functionality.
![stock](https://github.com/OpenApoc/OpenApoc/assets/73447098/2161c6b2-7b89-456d-9d5e-e1723d2f3d5d)

**Comment by dethstryke01** [comment]
Ah, OK. I'll close this issue, then.
