### ISSUE TITLE
Dead Chrysalis has one square of missing texture

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1406]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1019](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49607931)
 - No Mods

![Skärmbild 2024-04-13 185217](https://github.com/OpenApoc/OpenApoc/assets/55395993/eddc6d12-dc13-4850-820b-b13e11828d49)

It should look like this: https://youtu.be/D2UUeDTgZOg?t=1701

Edit: I have found a better picture from another computer that more clearly shows the bug I was referring to in this post. Picture below: 
![Missing graphics](https://github.com/OpenApoc/OpenApoc/assets/55395993/df92852f-53a7-47ed-9c9e-c54fb86eedcb)

**Comment by XCOM-HUB** [comment]
This "bug" seems to have been "squished"/fixed properly with the latest installation [0.0.1035](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49642277)

Picture proof:
![Skärmbild 2024-04-18 171327](https://github.com/OpenApoc/OpenApoc/assets/55395993/3a673ddb-93c2-435a-9022-2138d4254b75)

Keep it up! 🎉

**Comment by XCOM-HUB** [comment]
I have found a better picture from another computer that more clearly shows the bug I was referring to in this post. Picture below: 
![Missing graphics](https://github.com/OpenApoc/OpenApoc/assets/55395993/df92852f-53a7-47ed-9c9e-c54fb86eedcb)

**Comment by FilmBoy84** [comment]
If this appears rectified I'll close @XCOM-HUB 
I remember these kind of issues in the OG also
Would be good to have them confirmed as sorted out

**Comment by XCOM-HUB** [comment]
It displayed correctly in version [0.0.1035](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49642277). I haven't tested it out in later versions yet. I will inform you when I do.

**Comment by ayrtondenner** [comment]
Just tested with main branch as well.

![image](https://github.com/OpenApoc/OpenApoc/assets/13112588/018f5e38-dffb-4478-8c37-293cf1d04913)

**Comment by XCOM-HUB** [comment]
Yep! I can also confirm that it seems to be fixed in the latest version of OpenApoc.
