### ISSUE TITLE
X-COM icons and portrait of agents disappear when two message toggles overlap

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1407]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1023](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49609258)
 - No Mods

This is a minor bug but I thought I would mention it anyway. All the icons are restored as soon as you click on the Play or Pause buttons at the bottom (also works by pressing ENTER or ESCAPE on your keyboard).

SAVE-FILE just before the minor bug (must choose Ultra Fast speed to get the two overlapping message toggles): [Beginning.zip](https://github.com/OpenApoc/OpenApoc/files/14971532/Beginning.zip)

![Skärmbild 2024-04-14 185606](https://github.com/OpenApoc/OpenApoc/assets/55395993/b78732c7-df47-428d-a1da-13c3b34709a6)

It should look like this:
![Skärmbild 2024-04-14 190350](https://github.com/OpenApoc/OpenApoc/assets/55395993/2441590e-9a5c-4611-9d0a-593fb5d2a4a5)

**Comment by Kurtsley** [comment]
I've seen that a few times, probably because multiple things have checks at 5 minute intervals. How did the OG handle this issue?

**Comment by XCOM-HUB** [comment]
I'm not exactly sure how OG handled it. Is there a way to make my save file work on the OG, or is it too much of a hassle!?
