### ISSUE TITLE
Hovering mouse cursor over Buy/Sell button does not display a tooltip prompt

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1410]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1024](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49612110)
 - No Mods

Hovering the mouse cursor over the Buy or Sell button and letting it stay there for just a second will result in a tool-tip prompt with the corresponding text to pop up just above the mouse cursor.

It should be like this picture: 
![Skärmbild 2024-04-14 210049](https://github.com/OpenApoc/OpenApoc/assets/55395993/4f35e2bc-d8df-44dd-a993-23b584bf9a34)

But instead, nothing pops up: 
![Skärmbild 2024-04-14 211445](https://github.com/OpenApoc/OpenApoc/assets/55395993/40bce140-3289-4b6a-80cf-ccfe3043ae7f)

PS: Why is the Top Speed of the Hoverbike 4 units slower in OpenApoc than in the OG?

**Comment by Kurtsley** [comment]
I have a PR ready for this but there are more options than buy and sell. I figured out that the transfer screen says "transfer" for both buttons. Do you know the what words the alien containment screen uses? I don't have a save in the OG that has aliens.

**Comment by XCOM-HUB** [comment]
> I have a PR ready for this but there are more options than buy and sell. I figured out that the transfer screen says "transfer" for both buttons. Do you know the what words the alien containment screen uses? I don't have a save in the OG that has aliens.
> 
> Never mind I found it.

It is "Contain" and "Destroy" in OG Alien Containment.
