### ISSUE TITLE
Items disappear when sold out or not in stock and the slider refuses to go all the way down

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1414]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1027](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49614347)
 - No Mods

In the original game, you could see items in the market overshadowed when sold out or not in stock. In OpenApoc, they just simply vanish. Maybe make this one an option in the More Options menu.
![Skärmbild 2024-04-16 180654](https://github.com/OpenApoc/OpenApoc/assets/55395993/4cab6143-a20e-442c-b8ea-ae933266abe5)

And the slider refuses to go down to the bottom, as seen in the picture below.
![Skärmbild 2024-04-16 225832](https://github.com/OpenApoc/OpenApoc/assets/55395993/60656a38-bbc4-4d57-a6d7-0075bd604130)

**Comment by Kurtsley** [comment]
I'm positive this used to work, must have been broken recently.

**Comment by Kurtsley** [comment]
Maybe I'm confused about this, but I just checked and it looks like it works:

![grey](https://github.com/OpenApoc/OpenApoc/assets/73447098/403fc222-f17f-4dc6-bbab-c77846b148b3)

I bought all of an item and it is grayed out. I can also scroll to the bottom of the list.
Can this be reproduced from a new game?

**Comment by XCOM-HUB** [comment]
I can't get it to work on a new game scenario. Maybe I have to do a clean install of the latest version from AppVeyor!? I usually just install over the older installations.

**Comment by ayrtondenner** [comment]
I did an updated to removed zeroed-and-grayed-out aliens from Alien Containment list: https://github.com/OpenApoc/OpenApoc/pull/1375

Are they using the same code? If yes, then it will need to update a check if its an alien or item list.

**Comment by XCOM-HUB** [comment]
The slider can sometimes go all the way down like in the 'Vehicles' section. Picture below:
![Vehicles scroll down](https://github.com/OpenApoc/OpenApoc/assets/55395993/8ca3ab69-99bd-408e-9285-f39e60a6c7af)

But not in the other sections ('Agent equipment', 'Airborne vehicle equipment/fuel' and 'Road vehicle equipment/fuel'):
![Agent equipment scroll down](https://github.com/OpenApoc/OpenApoc/assets/55395993/146dcb78-23ad-4e4b-8873-e555ce9b770d)
![Airborne vehicle equipment scroll down](https://github.com/OpenApoc/OpenApoc/assets/55395993/c4c94db5-c5ee-4be5-9bd3-3f4bfdb3925c)
![Road vehicle equipment scroll down](https://github.com/OpenApoc/OpenApoc/assets/55395993/208ebae3-6e73-41a8-a5e8-6ce551616dfe)


PS: I can see that the more items I have bought up, the more the slider wont go down. I gave myself tons of cash and bought up every ground vehicle equipment and this was the result:
![Skärmbild 2024-04-18 031942](https://github.com/OpenApoc/OpenApoc/assets/55395993/e269d884-109e-4133-8eff-b2d1a2e711ac)
