### ISSUE TITLE
[Cityscape] Vehicle icon do not appear in the 'Hostile vehicles tab' if you left-click a non-hostile vehicle

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1415]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1027](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49614347)
 - No Mods

If you left-click on a non-hostile vehicle anywhere on the Cityscape it would appear as an icon in the 'Hostile vehicles tab'. Right-clicking on the icon of the non-hostile vehicle will remove it from the 'Hostile vehicles tab' (only possible with non-hostile vehicles).
![Skärmbild 2024-04-16 222826](https://github.com/OpenApoc/OpenApoc/assets/55395993/d4ed6528-d853-4627-9eac-6fedab8a6e86)

In OpenApoc no icon will appear, only the name of the vehicle and which organization owns it.
![Skärmbild 2024-04-16 164310](https://github.com/OpenApoc/OpenApoc/assets/55395993/a90d6ddc-fcb4-4a35-9761-449c00aab451)

**Comment by XCOM-HUB** [comment]
This fix does not work properly. The first non-hostile vehicle you clicked will be stuck for a few seconds in the list after left-clicking another non-hostile vehicle. The first vehicle you clicked should disappear immediately after clicking on another non-hostile vehicle as it does in vanilla OG. If you move your mouse cursor over to the list with 2 non-hostile vehicles the first one you clicked will then disappear as if the mouse cursor triggers a check of some sort.

**Comment by Kurtsley** [comment]
This is a known form update issue. Some areas only update when the mouse enters the form. So the fix is working, the other issue needs to be fixed and it affects many different forms.
