### ISSUE TITLE
Capturing Live Aliens in a Base Attack Mission will come up as 0 in the [DEBRIEFING]

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1422]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1038](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49642396)
 - No Mods

When my base was under attack I successfully captured one living Chrysalis, but the [DEBRIEFING] states that I haven't captured any live aliens. When un-pausing in Cityscape I get four messages that I have retrieved items from tactical combat zone and I can clearly see that I have a live Chrysalis in my Alien Containment.

![Skärmbild 2024-04-18 201643](https://github.com/OpenApoc/OpenApoc/assets/55395993/4bd99a09-8051-48e6-99d6-fa3f29c39db9)
![Skärmbild 2024-04-18 172021](https://github.com/OpenApoc/OpenApoc/assets/55395993/7f2f914c-3c94-48e5-afb8-567007cb2e39)

When completing a mission elsewhere you only get one message about items arriving at your base:

![Skärmbild 2024-04-18 171528](https://github.com/OpenApoc/OpenApoc/assets/55395993/0c659698-51f8-4145-adfd-c95cf53f67fa)

SAVE-FILE in Battlescape (Just end the turn and let my Laser Turrets kill one Spitter and one Hyperworm): 
[Base Under Attack Battlescape 3.zip](https://github.com/OpenApoc/OpenApoc/files/15029387/Base.Under.Attack.Battlescape.3.zip)

**Comment by Kurtsley** [comment]
See this comment. Base defense missions need work.

https://github.com/OpenApoc/OpenApoc/issues/1333#issuecomment-2060376307

**Comment by XCOM-HUB** [comment]
Agreed Kurtsley 👍

**Comment by ayrtondenner** [comment]
Question: after finishing a BaseDefense mission, the Live Aliens capture score should be calculated for a) all aliens that are alive when battle ends, or b) only for aliens that are actually going to captured, ignoring "abandoned" live aliens?

**Comment by XCOM-HUB** [comment]
> Question: after finishing a BaseDefense mission, the Live Aliens capture score should be calculated for a) all aliens that are alive when battle ends, or b) only for aliens that are actually going to captured, ignoring "abandoned" live aliens?

Option A) for sure.

**Comment by XCOM-HUB** [comment]
The [DEBRIEFING] will not count Live Aliens you have captured during a regular city-building mission even if you have captured Live Aliens in your Bio-Transport Module. This needs to be fixed.

SAVE-FILE: [At least one Live Alien.zip](https://github.com/user-attachments/files/15805357/At.least.one.Live.Alien.zip)
After completing the mission in this SAVE-FILE you will see the [DEBRIEFING] stating you didn't capture any Live Aliens even if you did. Build an Alien Containment facility before the Valkyrie Interceptor 1 arrives at Base 1 (using F10 to complete the Alien Containment facility instantly). As soon as the Valkyrie Interceptor 1 arrives at Base 1 you will also see a full Alien Containment with both live and dead aliens. This proves that the [DEBRIEFING] lies about you not having captured any Live Aliens.
