### ISSUE TITLE
Tooltip not showing rank of Agent/Soldier when hovering mouse cursor on insignia

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1423]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1038](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49642396)
 - No Mods

In the original game you could see the name of the rank your Soldier/Agent have if hovering the mouse cursor over the insignia.
![Squaddie](https://github.com/OpenApoc/OpenApoc/assets/55395993/d98b4ae0-f402-480f-bd10-a448c0b306dd)

But not in OpenApoc:
![Rank not showing on insignia](https://github.com/OpenApoc/OpenApoc/assets/55395993/d5cff628-cd66-4616-a118-ae01523acbca)

**Comment by Kurtsley** [comment]
Good catch, will fix.
