### ISSUE TITLE
Add store space value per item at Alien Containment stats view

### ISSUE THREAD

**Issue by ayrtondenner** [OpenApoc/OpenApoc#1429]
Right now, Alien Containment view doesn't show in stats the store space used by an item. Example: Brainsucker Pod takes 1.

![image](https://github.com/OpenApoc/OpenApoc/assets/13112588/9254f18c-c7be-4c38-a8c2-2f65549b2b18)

**Comment by FilmBoy84** [comment]
Agreed, this, like the Scientist/Engineer stats, would be a useful QoL addition

I think for accessibility it should be represented as a "percentage of containment capacity" value which accounts for bases with multiple containment also

This means it will be easy to see at a glance how much a single item will consume of the available space without having to do a conversion from an opaque value like "1" for brainsucker pods and convert them in your head to what percentage space that would be
