### ISSUE TITLE
Brainsucker Launcher still being labeled as "Alien Artifact" after having researched it 100%

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1455]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: [0.0.1076](https://ci.appveyor.com/project/OpenApoc/openapoc/builds/49863777)
 - No Mods

![Brainsucker Launcher researched but not the pods](https://github.com/OpenApoc/OpenApoc/assets/55395993/8ea68847-2ca2-42ec-bf18-0b23ce94f82f)
![Fires Brainsucker pods](https://github.com/OpenApoc/OpenApoc/assets/55395993/bc67fd80-aa5a-49b0-be43-a73fcf38ae47)
(Maybe the name of the Brainsucker Launcher will be revealed after finishing researching the Brainsucker pods!?)

There are also two Alien craft weapons that has their names already revealed despite no research (Light and Medium Disruptor Beam.)
![Not yet researched](https://github.com/OpenApoc/OpenApoc/assets/55395993/51ee2ca1-eef7-4873-bcc5-a2e33d7796c0)
![Alien craft weapon name showing despite no research](https://github.com/OpenApoc/OpenApoc/assets/55395993/a590a560-789b-4d4b-b4b7-22d451657d1c)

**Comment by ayrtondenner** [comment]
Could you please provide a save file for these cases?

**Comment by XCOM-HUB** [comment]
> Could you please provide a save file for these cases?

Here you go!
[Unresearched Alien Artifacts.zip](https://github.com/OpenApoc/OpenApoc/files/15421891/Unresearched.Alien.Artifacts.zip)

**Comment by XCOM-HUB** [comment]
The name of the Brainsucker Launcher is revealed after you have researched the Brainsucker Pods as well as the Brainsucker Launcher. I think the name should first be revealed after you have only researched the Launcher, and a prompt/pop up window should warn you that you have to research the Brainsucker Pods to be able to fully use it (only when trying to equip a Brainsucker Launcher.)

![After researching Brainsucker Pods](https://github.com/OpenApoc/OpenApoc/assets/55395993/fbe94f2c-98a9-4fd3-9a40-f97d6be0b4ac)

PS: I know that the Brainsucker Launcher is useless since the Brainsuckers will only attack your agents, maybe hostile agents like the Cult of Sirius for example (I haven't tested that yet.)

**Comment by XCOM-HUB** [comment]
The name of the Small Disruption Shield is also revealed before having researched it.
![Small Disruption Shield](https://github.com/OpenApoc/OpenApoc/assets/55395993/b716e31f-b72f-4bcf-a855-e0e9ca5ea917)
