### ISSUE TITLE
Why it is necessary to have original ISO to BUILD OpenApoc?

### ISSUE THREAD

**Issue by yahuaska** [OpenApoc/OpenApoc#147]
Isn't it an error?
If I only want to build it, why I have to have original game? 
Any files from X-Com Apoc are used in the build process?

**Comment by Istrebitel** [comment]
What message exactly are you seeing?
I don't think building requires vanilla...

**Comment by sfalexrog** [comment]
Doing a CMake build does require a CD image, but IIRC it's only used for data extraction. Then again, building binaries without the data does not make much sense, since the data format might change often.

**Comment by killermosi** [comment]
IIRC, the current build system was built with the assumption that you're building the binary for immediate use, and it extracts and processes/corrects some of the original data to some extent for this purpose.

Most likely, the build process will be refined in time, and the data extraction/correction will be done on the application first execution.

But until then, the focus is on implementing the game mechanics and proper interactions.

**Comment by yahuaska** [comment]
@Istrebitel 
```
CMake Error at CMakeLists.txt:36 (message):
  CD_PATH "/home/ringo/code/OpenApoc/data/cd.iso" points at non-existant file
-- Configuring incomplete, errors occurred!
See also "/home/ringo/code/OpenApoc/build/CMakeFiles/CMakeOutput.log".
```

**Comment by yahuaska** [comment]
@sfalexrog it depends on what person, who builds, needs.
I understand that it is the lowest priority request, but it would be great if anyone can build it without having an original cd on the build machine.

**Comment by yahuaska** [comment]
@killermosi ok, I got it.
I feel satisfied, thank you guys for your answers.
