### ISSUE TITLE
Rename "Aliens Held" to "Alien Storage Capacity" for clarity

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1470]
I think it is misleading to have it say "Aliens Held" because that indicates that there are 20 Aliens currently held inside the Bio-Transport Module.

PS: If "Alien Storage Capacity" is too long, replace it with "Capacity" or "Alien Capacity".
![Aliens Held](https://github.com/OpenApoc/OpenApoc/assets/55395993/a12e1146-aa8b-4b81-86e5-bb3ad4c01a36)

**Comment by ayrtondenner** [comment]
What's the difference between "Storage" and "Aliens Held/Capacity" in this context?

**Comment by FilmBoy84** [comment]
Maybe go with `Max Lifeforms` or `Max Samples`?

Both of these should fit and are more ambiguous (for mods that allow none-alien biological items) whilst still being specific enough to know what the string refers to

**Comment by XCOM-HUB** [comment]
@ayrtondenner I believe "Storage" in this context could be storage for dead aliens, while "Aliens Held" is counting each living life form.

@FilmBoy84 I think "Max Lifeforms" is the better alternative 👍

**Comment by ayrtondenner** [comment]
@XCOM-HUB I just remembered: "Storage" is how much storage an item is occupying in base. Hope we find a better name for that in the future.

**Comment by XCOM-HUB** [comment]
> @XCOM-HUB I just remembered: "Storage" is how much storage an item is occupying in base. Hope we find a better name for that in the future.

Maybe "Storage Units" is a better alternative to just "Storage"!?
