### ISSUE TITLE
Show "No Alien Containment Facility" window when ship with alien lands in base without alien storage

### ISSUE THREAD

**Issue by ayrtondenner** [OpenApoc/OpenApoc#1481]
In original game, when a ship containing aliens landed at a base that has no alien storage, it shows to the user a window with options "Keep on board" or "Destroy".

![image](https://github.com/OpenApoc/OpenApoc/assets/13112588/63e3116f-31db-40b9-95a7-6ae2787840c0)

Video provided by @dethstryke01 showing behavior in original game: https://www.youtube.com/watch?v=dwO4-Lm-O7A&t=646s

**Comment by XCOM-HUB** [comment]
Very nice catch 👍
