### ISSUE TITLE
Nonsense code in VehicleMover::updateCrashed

### ISSUE THREAD

**Issue by JonnyH** [OpenApoc/OpenApoc#1487]
https://github.com/OpenApoc/OpenApoc/blob/d33ff384284c506f0553add7ebbdfe40bb6a7bc2/game/state/city/vehicle.cpp#L1124C1-L1137C2

```
void VehicleMover::updateCrashed(GameState &state, unsigned int ticks [[maybe_unused]])
{
	// Tile underneath us is dead?
	if (vehicle.tileObject && vehicle.tileObject->getOwningTile() &&
	    vehicle.tileObject->getOwningTile()->presentScenery)
	{
		auto presentScenery = vehicle.tileObject->getOwningTile()->presentScenery;
		if (!presentScenery)
		{
			vehicle.setCrashed(state, false);
			vehicle.startFalling(state);
		}
	}
}
```

This looks nonsense - as "presentScenery" is the same vehicle.tileObject->getOwningTile()->presentScenery as checked in the first conditional, so (outside of threading) will never == false?

**Comment by ayrtondenner** [comment]
Checking the [commit that last updated this](https://github.com/OpenApoc/OpenApoc/commit/e5fc6da130f8321a5789eea3bff9ad81e2ce8c5a#diff-3616dc8eea6e5f773f9434f708c2ac82234b86686e06fb238986ae3d8f8793f7R1126), it seems that the inner `presentScenery` check should be removed.

Any objections?
