### ISSUE TITLE
Crash when buying gear or personnel

### ISSUE THREAD

**Issue by Kothyxaan** [OpenApoc/OpenApoc#1499]
I have a crash whenever I order personnel or equipment.
Crashes at 

I have tried versions (both crashed):
OpenApoc-20240829
OpenApoc-20240903

Crashes about 15 seconds (game time) after bought.

Version:
openapoc-20240815
Is working fine for buying equipment and hiring personnel, but it crashed after the first battle (notified of victory, onto splash screen, crash).

**Comment by Kothyxaan** [comment]
Just in case it matters. 
I downloaded the windows install options for each of those builds, ran the install.

**Comment by FilmBoy84** [comment]
Hi Kothyxaan

Sorry for delayed response - I shall try and get on replicating this Thursday to see if you can work through to a solution

Is the error on a new, clean, game or a save?

**Comment by Kothyxaan** [comment]
Hey, thanks for the reply. 
I tried it on a new install with a new save.

**Comment by FilmBoy84** [comment]
Thanks for further info, will help with replication 🍻

**Comment by Kothyxaan** [comment]
Hopefully it is a simple fix and not just a problem I have. Good luck either way. Also thank you for the work you are doing, X-Com Apoc was/is one of my favourite games that I return to every few years, so cheers!

**Comment by FilmBoy84** [comment]
OK managed to replicate on `20240903`

I start a new game (Easy in this case)
I buy some High Explosives
![image](https://github.com/user-attachments/assets/0e546628-f1b5-48c8-a8f5-7e3d01b4e00a)
![image](https://github.com/user-attachments/assets/50171dc2-44ad-4ba9-bdf0-0a1506b49c83)

I locate Airtrans 1 (which is doing the transport mission) on the map
![image](https://github.com/user-attachments/assets/3b1f8f34-77b7-479a-84b0-370431abd172)
![image](https://github.com/user-attachments/assets/0b5fb9bd-45a5-4fa8-99b9-4d91ca277d92)

Now, there are TWO ways to crash this

The first is as the airtrans enters the circled warehouse for pick-up - the game will crash on entry if the vehicle is selected and followed
![image](https://github.com/user-attachments/assets/7bbed6ed-664a-4762-99d4-c0e8740267c6)

Alternatively, DO NOT follow the craft and let it enter and exit the warehouse, the game will then crash on entering the X-COM base (when the usual items delivered message would pop up)

Log, game settings and save attached
[build 20240903 cargo delivery crash and log 1.zip](https://github.com/user-attachments/files/17439304/build.20240903.cargo.delivery.crash.and.log.1.zip)

I believe this may be a destructor issue intertwined with some of the cargo and base storage stuff that @ayrtondenner was working on over the summer

Thanks for raising this issue, good catch 🍻

**Comment by Kothyxaan** [comment]
I am just glad it wasn't something I had done wrong with the install or some such. Nice detective work :)

**Comment by FilmBoy84** [comment]
@Kothyxaan thanks to Kurtsley's fix, this should be resolved now

Can you confirm with the latest release please?

All looks good from here

https://github.com/OpenApoc/OpenApoc/releases/tag/20241112

**Comment by Kothyxaan** [comment]
I just quickly tested it Recruited some agents and scientists and bought some equipment.
All worked well, no crash (on maximum speed - I assume different speed will mean no crash as well).
So good work team!
If there are any other issues, when I start to play again properly, I will let you guys know.

**Comment by FilmBoy84** [comment]
Thanks for confirming fixed, closing the issue
