### ISSUE TITLE
Toggelable full-screen or windowed mode, please.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#160]

**Comment by Istrebitel** [comment]
JonnyH, pmprog, can you do this? I'm not that familliar with our framework

**Comment by Istrebitel** [comment]
Temporary solution:
add this to config file

```
[Framework.Screen]
Width=1680
Height=1050
Fullscreen=1 
```
with appropriate numbers for screen size of course

**Comment by JonnyH** [comment]
You can also run the executable with:

openapoc.exe --Framework.Screen.Width=1920 --Framework.Screen.Height=1080 --Framework.Screen.Fullscreen=1

All options that can be set in the config file can be set on the command line. It doesn't save them though, but you could create a 'fullscreen' shortcut or something with that in the arguments list.

**Comment by Paddywhacker** [comment]
Thanks.  That resolves the issue for me.
