### ISSUE TITLE
No research topic matching ID "RESEARCH_BRAINSUCKER_POD"  at skirmish battle

### ISSUE THREAD

**Issue by Blackwolf-Kuzoku** [OpenApoc/OpenApoc#162]
Encountered a problem while playing hotseat-mode in base-defense mission. ( Alien Turn 2 ) 
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1338623/openapoc_log.txt)

**Comment by Istrebitel** [comment]
thanks, will look into it

**Comment by Istrebitel** [comment]
should be fixed in next version

**Comment by Blackwolf-Kuzoku** [comment]
sorry for let you wait. just had no time to check this. will do so soon with new version ( and still looking for new problems )
