### ISSUE TITLE
Can't start a game from git source

### ISSUE THREAD

**Issue by pmprog** [OpenApoc/OpenApoc#163]
#define OPENAPOC_VERSION "heads/master-0-g934a250" 

[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1342225/openapoc_log.txt)

**Comment by Istrebitel** [comment]
can you upload your vehicle_types.xml? it seems to contain some bogus value

**Comment by pmprog** [comment]
Hmmm, it seems I don't have a vehicle_types.xml. Where should this file come from?

**Comment by Istrebitel** [comment]
it should be in the gamestate_common archive, it should be generated by extractor from the game exes

**Comment by Istrebitel** [comment]
do you actually have all the game data extracted by not the vehicle_types.xml? Or maybe extractor didn't run at all and you don't have game data extracted?
