### ISSUE TITLE
Sign EXEs 

### ISSUE THREAD

**Issue by MeirionHughes** [OpenApoc/OpenApoc#167]
Should sign the EXEs so Windows doesn't complain about it. 

>ref https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

**Comment by Istrebitel** [comment]
I assume it complains about OpenApoc.exe?

Hmm... does OpenXCom or OpenMW or JA 2.13 or GZDoom other open source engine remakes actually do that? Could you test and tell me? I got rid of annoying popups on my system long time ago and this was one of them.  

In my opinion it's really pointless, like, yeah, you've signed an exe, it's certified to be safe, oh wait, I've injected your dlls and now you still have a virus there, what's the point of signing an exe then?

There is some merit to signing an installer, but we're not going to be using them for some time. And with very frequent updates it's unlikely we'll ever start.

Finally, at this point, when we're releasing via appveryor, there's really no reason to worry about it being compromised. It's freshly built from publicly available code! 

And even if someone would be adverse to running unchecked open source pre-built binary, he could always register on github, download visual studio 2015 and github desktop (or do it on linux using linux alternatives), clone the repo, and build it himself, and ensure he's not compromised that way.

**Comment by MeirionHughes** [comment]
It complains about all of them if you dl from AppVeyor. You're right, that will go away with a signed installer.
