### ISSUE TITLE
Lists behave strange when itemsize is set and does not match control size

### ISSUE THREAD

**Issue by Istrebitel** [OpenApoc/OpenApoc#171]
The way lists work now, when you add controls to them, they just align them one after the other. However, when updated (or rendered, whatever causes it) which most often happens when you move mouse over it then they spring into proper position. You can note that happening in my last update video. I re-implemented the form since then to work properly, but it seems there's some problem with listbox code because this shouldn't happen.

**Comment by FilmBoy84** [comment]
@redv appears to have fixed this
