### ISSUE TITLE
No item stats in Ufopaedia

### ISSUE THREAD

**Issue by ufomesh** [OpenApoc/OpenApoc#172]
No item stats in the Ufopaedia articles. All items in Equipment section don't have stats 
http://joxi.ru/KAxe9VBcMoODXr

**Comment by Istrebitel** [comment]
huh? I guess the one who originally coded ufopedia didn't finish it.

**Comment by FilmBoy84** [comment]
Item stats are now (MOSTLY) in the game as per vanilla
Where data is missing, separate issues can be registered for those cases
Closing issue as it's too far down the list to be of use

Many thanks JonnyH @Istrebitel and FranciscoDA for fixing this <3
