### ISSUE TITLE
Crash due to ground vehicles

### ISSUE THREAD

**Issue by Normandoesminecraft** [OpenApoc/OpenApoc#174]
[Openapoc log.zip](https://github.com/OpenApoc/OpenApoc/files/1360063/Openapoc.log.zip)

See log (At error message i held down the enter key to "limp along")

**Comment by JonnyH** [comment]
Ground vehicles are known broken at the minute, launching them will cause an error. This is still on our "TODO" list - it's why we've not released a beta (or even 1.0) yet :)

BTW the attached log doesn't actually seem to contain any errors, just the intro video then successful exit - if you re-run openapoc at all it'll immediately overwrite the log, so if you do get an error make sure you copy the log out first before re-running.
