### ISSUE TITLE
Include the readme_hotkeys.txt file in the distribution zip.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#178]

**Comment by Paddywhacker** [comment]
Later in development it might be useful to have it included in the UFOPEDIA, and later still have the keyboard shortcuts be assignable.

**Comment by Istrebitel** [comment]
file should be included in the next build

Re-assigning hotkeys unfortunately is not really a simple matter in strategy games. that's why you don't usually see it in other projects, for example Jagged Alliance 1.13. However, it could be done.
