### ISSUE TITLE
Should be able to change vehicle/soldier names

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#179]
Clicking on vehicle name or soldier name allows you to assign new names in vanilla.

**Comment by Istrebitel** [comment]
yes, definetly should. We don't have a text input control for now, unfortunately. Eventually it will get implemented.

**Comment by FilmBoy84** [comment]
Issue appears to be fixed by @SiemensSchuckert 's work
Many thanks
