### ISSUE TITLE
Soldier & vehicle names should show in the equipping screen.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#180]
Clicking on vehicle name or soldier name allows you to assign new names in vanilla.
![apoc1](https://user-images.githubusercontent.com/6434813/31335343-a1a8b84a-ad4e-11e7-89a0-e26a1015c155.jpg)

**Comment by Istrebitel** [comment]
As it says, form is a temporary stub. There will be a proper form like vanilla (or better) where you drag and drop items in a nested list (vehicles/agents nested in buildings)
