### ISSUE TITLE
Friendly forces should not be hostile during raids.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#181]
For example, when raiding Marsec at the start of a game to gather resources, particularly mind-shields, the Marsec personnell should not be hostile unless you start to kill them.  Raiding with non-lethal stun guns is a recognised tactic to gather weapons and gain experience.  In vanilla, sometimes the victims panic and set off an explosion, in which case you will be penalised for the deaths/damage.

**Comment by Blackwolf-Kuzoku** [comment]
But wasnt it in the vanilla game ( should be in the manual of the game ) that the organisation gets an alert if you raid them?  Otherwise: Why should you attack Marsec if they raid you? ;)

**Comment by Blackwolf-Kuzoku** [comment]
Pages 193 to 195 of Steam - Version: 

Note: if an organization is hostile to X-COM, you will have to fight the security forces of a
building you investigate as well as any Aliens present.

• If you investigate a building with no prior Alert, there will be a small diplomatic penalty
(organizations are understandably alarmed at a squad of heavily armed Agents walking
around their buildings).

• Raiding an organization will make that organization hostile to X-COM. It is also possible
that you can upset the allies of that organization. Watch out!

Note: if an organization is hostile to X-COM, you will have to fight the security forces of a
building you investigate as well as any Aliens present

**Comment by Paddywhacker** [comment]
> • Raiding an organization will make that organization hostile to X-COM. It is also possible
that you can upset the allies of that organization. Watch out!

That's not how it actually worked.  If nobody died then there was no penalty, and you could stun and loot your friends.

**Comment by yahuaska** [comment]
I confirm.

Friendly organizations don't attack X-COM until you kill somebody.

**Comment by Istrebitel** [comment]
Are they in current build? They should show as purple and should not attack you until you attack them first. But they do show as "red" as per vanilla behavior, and your units auto-attack them unless you order cease fire, as per vanilla behavior. If what I said is not correct regarding the lastest build, please provide screenshots/steps to replicate.

And there will probably be a mod that makes units react to stun negatively, or orgs reacting to act of raid negatively (turning hostile essentially). But as a mod, one you can enable/disable at your convenience.

**Comment by Paddywhacker** [comment]
'Friendlies' appear red, so are not friendly.  Should be neutral or hostile depending on relations with organisation.  If friendly or neutral then should stay friendly or neutral until one of them dies, either killed by XCOM or through panicking.

**Comment by Istrebitel** [comment]
I'm not sure I understand. 
Please launch vanilla game, start new game, and raid Megapol. You will see Megapol displayed red and your agents auto-attacking Megapol, despite Megapol not attacking you (being friendly at game start)

**Comment by Paddywhacker** [comment]
> Did I implement it improperly or do you aim to say that vanilla behavior makes no sense?

That's not what I remember, but if it is vanilla then so be it, although it doesn't make sense for mobs to be red but not hostile.

**Comment by Istrebitel** [comment]
That's why I asked you to please try it yourself. When I do on my version that's how it works. Does it work the same on yours?
