### ISSUE TITLE
Tank Griffon AFV wich Rumble Cannon shot range like 50-100 instead 250

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#184]
Tank Griffon AFV wich Rumble Cannon shot range like 50-100 instead 250

**Comment by Istrebitel** [comment]
250 is the displayed value, internal value is 500, which is measured in the ingame "voxels". Must be divided by 32 to get the range (on XY plane)
Thus the range should be ~16 in-game tiles. Is is shorter, like 4 tiles?

**Comment by makus82** [comment]
i compared with randor  plasma gun that have also 250
setup to havk and send to destroy vehicle

**Comment by Istrebitel** [comment]
Please confirm whether fixed or broken in latest release.
