### ISSUE TITLE
Retaliator self-destructed in attack on another target

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#185]
Retaliator self destoyed when i equip 2 medium disraptors and send to kill some bike 
first of i dont see but heard shots about few seconds and then selfdestraction 
[openapoc_log retaliator self destro.txt](https://github.com/OpenApoc/OpenApoc/files/1377223/openapoc_log.retaliator.self.destro.txt)

**Comment by Istrebitel** [comment]
hmm cannot reproduce. 
but if you heard shots and saw health gradually decreasing that must be because the vehicle was hitting itself. 
I've increased the time vehicle is invulnerable to its own fire, let's see if this happens in new build

**Comment by makus82** [comment]
ok he fly at level 2 low
and he start fire at max range and i saw shots in 1/4 body of interceptor before him but furter i dont see beams
then he fly close to 2 level building and aparantly destroy self beacose shot in that building and die from blast...

**Comment by makus82** [comment]
here 1 more i send hawk to destroy taxi and after some time he destroy self)
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1379629/openapoc_log.txt)

**Comment by Paddywhacker** [comment]
Is that not "destroyed by falling building"?  There should be an alert for that.

**Comment by makus82** [comment]
no in notifications was writen that hawk destroy hawk (yourself)

**Comment by Istrebitel** [comment]
Please confirm whether fixed or broken in latest release.
