### ISSUE TITLE
Crash after i start kill vehicles

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#186]
I take anihilator and 3 disraptors 2 med and 1 heavy
kill 2 vehicles and at 3 vehicles client start to think and after 10 sec crashed
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1379499/openapoc_log.txt)

**Comment by makus82** [comment]
Also all ships dont see any building before self they just shoot like as if there are no buildings between the target and the ship

**Comment by Istrebitel** [comment]
a lot of bugs fixed recently with this. after new build is released please try to kill vehicles again and see if it crashes

**Comment by makus82** [comment]
i use last release wich properly destroyed buildings

**Comment by makus82** [comment]
i can update client by overwriting releases?

**Comment by Istrebitel** [comment]
Better wipe clean as something might go wrong.
And yes, thanks for the bug with buildings being shot. Indeed vehicles didn't properly check for collision. Now they do. New release in about an hour.

**Comment by Istrebitel** [comment]
Please confirm whether fixed or broken in latest release.

**Comment by makus82** [comment]
ok so i repeat wich interceptor wich 3 disraptors med
vehicle now dont shot if before him and target some building
but its starts turn on place and wait few sec then move till next target move and all that repeats
some cars its cant shoot  and only if car at some top open view place its shoots 
then  after 4-6 cars game crashed
i just write video..
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1394641/openapoc_log.txt)
.

**Comment by Istrebitel** [comment]
Should be fixed in last build. Please try again.

**Comment by makus82** [comment]
confirmed

**Comment by FilmBoy84** [comment]
This appears to be fixed, one year near enough and no further reports. Closing. Many thanks for your efforts in sorting it Istrebitel <3
