### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by FS-21** [OpenApoc/OpenApoc#192]
I get 3 compilation errors (Debug & x64 but I tested other options) and I can't continue.
Steps I followed;
 I git clonned in the next location:
E:\proyectos\OpenApoc\
- With luck I found on the web repository where were the the github libraries used for compilate the project:
https://github.com/OpenApoc/OpenApoc/tree/master/dependencies
So finally I was able to download the libraries that the (inaccurate) installation readme instructions said that these were included:
· GLM, libsmacker, lodepng, miniz, physfs (that patched version), pugixml, tinyformat.
(please update these instructions if you guys want the project more friendly)
- I use my original ripped Spanish CD as "cd.iso" in the data folder:
E:\proyectos\OpenApoc\trunk\data\cd.iso
- After that if I open "OpenApoc.sln" and I use VS 2015 or VS 2017 I get these 3 errors almost at the end of the compilation process: 

...

14>  notificationscreen.cpp
14>e:\proyectos\openapoc\trunk\game\ui\general\messagelogscreen.cpp(54): error C2668: 'OpenApoc::BattleTileView::setScreenCenterTile': ambiguous call to overloaded function
14>  e:\proyectos\openapoc\trunk\game\ui\tileview\battletileview.h(133): note: could be 'void OpenApoc::BattleTileView::setScreenCenterTile(glm::vec<3,float,0>)' (compiling source file general\messagelogscreen.cpp)
14>  e:\proyectos\openapoc\trunk\game\ui\tileview\battletileview.h(132): note: or       'void OpenApoc::BattleTileView::setScreenCenterTile(glm::vec<2,float,0>)' (compiling source file general\messagelogscreen.cpp)
14>  e:\proyectos\openapoc\trunk\game\ui\general\messagelogscreen.cpp(54): note: while trying to match the argument list '(const glm::vec<3,int,0>)'
14>  optionsmenu.cpp

...
...

15>  extract_vehicle_equipment.cpp
14>e:\proyectos\openapoc\trunk\game\ui\tileview\battleview.cpp(4537): error C2668: 'OpenApoc::BattleTileView::setScreenCenterTile': ambiguous call to overloaded function
14>  e:\proyectos\openapoc\trunk\game\ui\tileview\battletileview.h(133): note: could be 'void OpenApoc::BattleTileView::setScreenCenterTile(glm::vec<3,float,0>)' (compiling source file tileview\battleview.cpp)
14>  e:\proyectos\openapoc\trunk\game\ui\tileview\battletileview.h(132): note: or       'void OpenApoc::BattleTileView::setScreenCenterTile(glm::vec<2,float,0>)' (compiling source file tileview\battleview.cpp)
14>  e:\proyectos\openapoc\trunk\game\ui\tileview\battleview.cpp(4537): note: while trying to match the argument list '(glm::vec<3,int,0>)'
14>  citytileview.cpp

...
...

18>------ Rebuild All started: Project: data, Configuration: Debug x64 ------
17>  main.cpp
18>  I 5494366462 bool __cdecl OpenApoc::ConfigFileImpl::parseOptions(int,char *[]): portable mode set
18>  W 5535613884 int __cdecl SDL_main(int,char *[]): Running all extractors
18>  W 24271243132 void *__cdecl `anonymous-namespace'::CueArchiver::cueOpenArchive(struct PHYSFS_Io *,const char *,int): Opening "E:\proyectos\OpenApoc\trunk\\data\cd.iso"
18>  E 25882492607 void *__cdecl `anonymous-namespace'::CueArchiver::cueOpenArchive(struct PHYSFS_Io *,const char *,int): Could not parse file "E:\proyectos\OpenApoc\trunk\\data\cd.iso"
18>    0x0000000140D21112 +0x140d21112
18>    0x0000000141A84363 +0x141a84363
18>    0x0000000141A83A36 +0x141a83a36
18>    0x0000000141A80705 +0x141a80705
18>    0x0000000141A81972 +0x141a81972
18>    0x0000000141A7D045 +0x141a7d045
18>    0x0000000140C5E322 +0x140c5e322
18>    0x0000000140D6A84D +0x140d6a84d
18>    0x0000000140D6A92C +0x140d6a92c
18>    0x0000000140DAADDC +0x140daaddc
18>    0x0000000140C7A1CD +0x140c7a1cd
18>    0x0000000140C3E7B5 +0x140c3e7b5
18>    0x0000000141A79540 +0x141a79540
18>    0x0000000141A7956B +0x141a7956b
18>    0x0000000141A76814 +0x141a76814
18>    0x0000000141A766D7 +0x141a766d7
18>    0x0000000141A7659E +0x141a7659e
18>    0x0000000141A76839 +0x141a76839
18>    0x0000000076FC59CD BaseThreadInitThunk+0xd
18>    0x00000000770FA561 RtlUserThreadStart+0x21
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: The command "cd /D "E:\proyectos\OpenApoc\trunk\"
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: "E:\proyectos\OpenApoc\trunk\\bin\x64\Debug\extractor.exe" --Framework.CD="E:\proyectos\OpenApoc\trunk\\data\cd.iso" --Framework.Data="E:\proyectos\OpenApoc\trunk\\data"
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: :VCEnd" exited with code 1.
17>LINK : fatal error LNK1104: cannot open file 'E:\proyectos\OpenApoc\trunk\bin\intermediates\x64\Debug\gameui\gameui.lib'
========== Rebuild All: 15 succeeded, 3 failed, 0 skipped ==========

Everything in the compilation looks right so I can't continue :-(

**Comment by JonnyH** [comment]
"With luck I found on the web repository where were the the github libraries used for compilate the project:
https://github.com/OpenApoc/OpenApoc/tree/master/dependencies
So finally I was able to download the libraries that the (inaccurate) installation readme instructions said that these were included:
· GLM, libsmacker, lodepng, miniz, physfs (that patched version), pugixml, tinyformat.
(please update these instructions if you guys want the project more friendly)"

Did you follow the "Building on windows" instructions and the "git submodule" commands not work? Or is the github GUI no longer cloning submodules by default?

You should never need to manually download any dependencies, and that error looks like you're using a slightly different version of GLM than the one in the submodule?

**Comment by FS-21** [comment]
Regarding that part of the install instructions I don't understand how works the "git submodule init" and "git submodule update -f" explained in the instructions (I mean, have I to replace the "submodule" word by one of those dependencies I mentioned before? and where exactly?) commands.
To get the files structure locally I used the TortoiseGit contextual menu command called "git clone..." on Windows 7 file manager with the URL "https://github.com/OpenApoc/OpenApoc.git".

After that, in "dependencies" folder I had to repeat the last step ("git clone..." contextual command) with the other URL to download all the dependencies because that folder had no subfolders with the respective libraries.

Once I had the modules in the right place was able to compile until that part I posted before.
If there is a different way I would like to follow it but the guide doesn't help to git newbies :-)

**Comment by JonnyH** [comment]
They're raw git commands, to be typed into a command line while in the cloned folder.

We can't realistically have instructions for _every_ GUI that wrapps git, but https://tortoisegit.org/docs/tortoisegit/tgit-dug-submodules.html suggests there should be an 'submodule update' context menu for tortoisegit?

Manually cloning the dependency repositories will likely end up pulling down the wrong version (ie the "master" development head of each at the time you happened to clone them), and that may be buggy/incompatible with our use. Like what I suspect is happening here.

**Comment by FS-21** [comment]
I don't know why but I repeated the same steps I did and this time the submodules were downloaded automatically when I cloned the OpenApoc github project (so this part of my bug report was fixed without doing anything). 
Moreover, the compilation was fully successful except in this last step:

...
18>------ Rebuild All started: Project: data, Configuration: Debug x64 ------
17>  OpenApoc.vcxproj -> E:\proyectos\Apoc\bin\x64\Debug\OpenApoc.exe
17>  OpenApoc.vcxproj -> E:\proyectos\Apoc\bin\x64\Debug\OpenApoc.pdb (Partial PDB)
18>  I 454346013 bool __cdecl OpenApoc::ConfigFileImpl::parseOptions(int,char *[]): portable mode set
18>  W 1672249685 int __cdecl SDL_main(int,char *[]): Running all extractors
18>  E 25251023803 __cdecl OpenApoc::UFO2P::UFO2P(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >): File "xcom3/ufoexe/ufo2p.exe"" has an unknown crc32 value of 0x1f4519fc - expected 0x4749ffc1
18>    0x0000000140C11E3F +0x140c11e3f
18>    0x000000014109E543 +0x14109e543
18>    0x00000001410B3222 +0x1410b3222
18>    0x0000000141F0A330 +0x141f0a330
18>    0x0000000141F0A35B +0x141f0a35b
18>    0x0000000141F07604 +0x141f07604
18>    0x0000000141F074C7 +0x141f074c7
18>    0x0000000141F0738E +0x141f0738e
18>    0x0000000141F07629 +0x141f07629
18>    0x0000000076FC59CD BaseThreadInitThunk+0xd
18>    0x00000000770FA561 RtlUserThreadStart+0x21
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: The command "cd /D "E:\proyectos\Apoc\"
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: "E:\proyectos\Apoc\\bin\x64\Debug\extractor.exe" --Framework.CD="E:\proyectos\Apoc\\data\cd.iso" --Framework.Data="E:\proyectos\Apoc\\data"
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: :VCEnd" exited with code 1.
========== Rebuild All: 17 succeeded, 1 failed, 0 skipped ==========


Maybe I need a different cd.iso because the extractor doesn't understand how to read my file? 
I'm using it in the alpha playtests without problems but here in the compilation I get this error.

**Comment by FranciscoDA** [comment]
If the CRC32 checksum of your disk files don't match the values that OpenApoc expects, then the extraction will fail this is probably because you have a different version. The steam version of X-Com includes a cd.iso file that should work. The GOG version bundles a .bin file that needs to be converted to ISO but it should work as well

**Comment by JonnyH** [comment]
Unfortunately, a lot of the data structures are packed into the executable, and we need to read them in order to "extract" that into our own format at build time.

Naturally, if the executable changes, the locations of these tables may change as well.

Doubly unfortunately, it seems the different language ports of Apocalypse have different executables, with different table locations.

So either you need to use a copy of Apoc that we already have the table locations setup for (IE the English one, tested with both gog.com and steam's versions), or someone needs to dig through the files every time we see a different executable to get the new table locations, which may be a fair bit of work.

The checksum failing here likely means the data the extractor tried to read will be junk, and probably cause all kinds of crazy problems.

BTW @FranciscoDA  you can use the .bin / .cue files directly from gog.com - just copy them both into the same folder, and point the Framework.CD config at the .cue file - e.g. 
`openxcom.exe --Framework.CD="file.cue"`
Or just rename the .cue file 'cd.iso' - the cue file contains the .bin filename, so you can't change that quite as easily.

**Comment by FS-21** [comment]
As everyone posted here the last problem was the cd.iso I ripped  from my original game. I bought from GOG the English edition (this will be the 3º time I buy this game) and renamed the XCOM.cue to cd.iso and it compiled without errors. 
Then I copied the data folder in \bin\x64\Debug and it ran. Thanks for all guys.
