### ISSUE TITLE
We should throttle similar sounds 

### ISSUE THREAD

**Issue by Istrebitel** [OpenApoc/OpenApoc#197]
Basically if you collapse a building then hundreds of same sample are played at once and it's bonkers. There should be some throttle, or maybe just volume multiplier for subsequent sounds or something, but it shouldn't just keep adding same sample to the playing queue

**Comment by makus82** [comment]
Buildings now strache  a little in air when fall 
so we get a great acelerated sound series

**Comment by Paddywhacker** [comment]
I vote no throttling.  Collapsing buildings *are* loud, and chains of explosions are even louder.  The loudness aids in immersion.

**Comment by makus82** [comment]
Its should be loud =] because it's loud in real life
besides how many time in your vanilla sessions you collapse whole building? or buildings at once=]
