### ISSUE TITLE
Crash under ridiculous load, v0.1-7-g7df1722

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#203]
Left it running overnight with a dozen road lesions and the spaceport destroyed. It would have been a better test if we had some faction-faction conflict. 

Dozens of spaceplanes built up. Was extremely laggy when switched to maximum speed and was unresponsive to button clicks.  Crashed shortly after midnight game time. 

Log file is 11 gig, too big to zip.
![apoc v0 1-7](https://user-images.githubusercontent.com/6434813/31866535-82d01212-b7dd-11e7-9d64-21d67d834333.jpg)

**Comment by makus82** [comment]
11 gig 0o wow

**Comment by Istrebitel** [comment]
Oh I see. Makes sense. There is no spaceport check, if there is a spaceport then shuttle is spawned, but if the spaceport is dead then shuttle will keep being spawned. And if you're playing on an older version, with no fuel system implemented yet, then they remain indefinitely and yes, game will die.

I will fix this.

**Comment by Istrebitel** [comment]
They would die eventually.
Orgs scavenge allied or owned stuff. So Transtellar would send a rescue vehicle to recover thier crashed vehicles.
And you can rescue non-hostile vehicles by attack-clicking it (should work for some time now)
