### ISSUE TITLE
time speed 5 heavily loads the CPU and the game starts to slow down strongly

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#204]
time speed 5 heavily loads the CPU and the game starts to slow down strongly

**Comment by Istrebitel** [comment]
It did slow down, yes, and also hang up sometimes. I believe that is now fixed.

Please try the latest build. 

I've implemented a fast pathfinding for road units and also implemented road units giving up when they can't reach target building. I've also increased iterations for flying vehicles close to destination so they can get out of tight dead ends like the slab which is the wall of the leftmost spaceport on superhuman (was the major hang up reason when space shuttle got stuck there).

In latest build it should run smoothly and should not slow down significantly over time.

Additionally, there's now an option to skip checks during turbo, that increases it even further. Basically, in this mode units move tiles just by checking that they can hop from one to another, without actually moving gradually by spending alloted time. This should in practice produce no difference (aside from time saved) but still if you have time please test that mode as well (like, will a vehicle "jump" over a dead road when it shouldn't, or would a vehicle reach some place it shouldn't).

**Comment by Istrebitel** [comment]
If you confirm there's no more slow downs close this issue.
