### ISSUE TITLE
ufopedia and interface bugs

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#205]
![screenshot](https://user-images.githubusercontent.com/11581207/31869278-9866b546-b7af-11e7-8bdf-395ae04ca795.png)
here where alien infiltration on russian its cut both words

also when i alt at building in city to get pedia page its otput error
![openapoc error](https://user-images.githubusercontent.com/11581207/31869321-db10dbe2-b7af-11e7-9bb0-2e2ec5d62d98.jpg)
![screenshot](https://user-images.githubusercontent.com/11581207/31869602-c24a03e8-b7b1-11e7-9b69-6dff2c16042b.png)
in center array of rocket like green constractions

**Comment by Istrebitel** [comment]
ufopaedia will be fixed sometime in the future, there are multiple display bugs like weapons and grenades not showing stats and so on.
as for hydro farm that's fixed now, thanks.
