### ISSUE TITLE
The overhead cityscape view doesn't ajust to screen size.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#206]
Full-screen cityscape shows a part of the city in full screen.  Switching to overhead view shows the whole of the city but occupying only a fraction of the screen.  It should fill the whole screen and optionally be zoomable.

The same is true of the top-down display during combat.  It is just too small to see the icons for dropped gear.  Zooming would fix everything, I think.

**Comment by Istrebitel** [comment]
Can you please explain what you think is wrong with it? 
I've tried 1920x1080 resolution and everything is as intended.
City is shown full screen. Strategic map fits the screen since it's too small for that resoultion.
I see everything working as intended (just looking not in a usual way, with such high resolution, as the game was made for 640x480)

**Comment by Paddywhacker** [comment]
Photo of monitor with full-screen cityscape, plus photo with too-small top-down view.  Zooming would fix.
![apoc 1](https://user-images.githubusercontent.com/6434813/31972055-365cd2a4-b97b-11e7-9c40-b3ef9916e136.JPG)
![apoc 2](https://user-images.githubusercontent.com/6434813/31972063-46af81e2-b97b-11e7-920a-275b2c95afc6.JPG)

**Comment by Paddywhacker** [comment]
Same problem with combat.
![apoc 3](https://user-images.githubusercontent.com/6434813/31972459-69df3278-b97d-11e7-9f08-071b244f79fe.JPG)

**Comment by Istrebitel** [comment]
I see.
This is intended. There was no zoom function planned originally, as it's not in vanilla. 
However, it makes sense for someone to mod that in, since map tiles become very small on large monitors, as you noticed. 
For now though, this is not an issue, but rather a possible future feature.

**Comment by Paddywhacker** [comment]
Please have another look at vanilla.  The screens that I have complained about are rendered at the same scale as the cityscape.  Currently in openapoc the cityscape is rendered large, probably obeying the command-line parameters.  The other screens are not.  This isn't a feature.  It is a bug.
