### ISSUE TITLE
Still being shot at by 'friendly' Marsec when raiding building with unarmed troops.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#207]
Looking for items lying around in the building, not necessarily stunning and stealing.  Friendly forces should not be hostile.  Sometimes they panic and fire their weapons, even rockets, but that is from panic.  Otherwise they just run around.  This is from vanilla.

**Comment by Istrebitel** [comment]
Do I get you correctly? they're panicking without you killing them? Do they actually have red faces over their heads? That's a sign unit is in panic.

**Comment by Paddywhacker** [comment]
No.  I was talking about in vanilla.  The friendlies won't attack except accidentally if they panic.  You have to stun many of them before they start to panic.

In the current build they act hostile, so I cannot walk up to them and stun them for no penalty.

**Comment by Istrebitel** [comment]
I have right now started superhuman and attacked megapol and they didn't fire at me.
1) Do you set your guys to cease fire so they don't provoke enemy?
2) Do you have "Initiating raid hurts relationships" OpenApoc mod set?
3) Can you film what you're doing on the latest build?

**Comment by Paddywhacker** [comment]
Retested with OpenApoc-v0.1-14-g647aaec3 and everything works as expected, thanks.
