### ISSUE TITLE
Build fails on Linux Mint

### ISSUE THREAD

**Issue by tsunamistate** [OpenApoc/OpenApoc#214]
Build stops on file ogles_3_0_renderer_v2.cpp with the following error:
`In file included from /home/natasha/OpenApoc/framework/render/gles30_v2/ogles_3_0_renderer_v2.cpp:12:0:
/home/natasha/OpenApoc/framework/render/gles30_v2/gleswrap.h:19:25: error: conflicting declaration ‘typedef long int ssize_t’
 typedef signed long int ssize_t;`
* Linux Mint 17.3
* GCC 6.3.0
* CMake 3.8.1

**Comment by Istrebitel** [comment]
Hopefully JonnyH can help

**Comment by Paddywhacker** [comment]
Can't you just change the declaration to be signed?  or maybe there is a compiler option to ignore trivial conflicts like this.  Such things were SOP back in the day when nothing ever compiled out of the box until it had been fiddled with for a couple of hours.

**Comment by FranciscoDA** [comment]
Can you tell us where was ssize_t previously defined? GCC usually drops a message like the following:
```
path-to-previous-declaration-file.h:line:col note: previous declaration as 'typedef ...'
typedef ...
```
It will probably be a gcc library, though. Maybe you could try compiling with clang and see if the problem persists?

**Comment by JonnyH** [comment]
I think *all* posix systems should have ssize_t in <sys/types.h> - so we could use that for "anything but windows", and only have the typedef on windows.

Bypasses the problem by removing unnecessary code seems like a good solution to me.

**Comment by tsunamistate** [comment]
Thank you, game builds without problems now!
