### ISSUE TITLE
onHover for child controls (transaction screen)

### ISSUE THREAD

**Issue by Istrebitel** [OpenApoc/OpenApoc#216]
Basically in transactiion screen when you hover over a complex control it should display the item.
But the onhover event only fires if you hover over the control itelsef, not its children

- Either we subscribe to control and all its children
- Or make controls pass their events up, which makes more sense I think? 

JonnyH, I need your ideas here

**Comment by redv** [comment]
I added the class MultilistBox to the project #238 
This class allow build hierarchical tree, use "hover" for each item and child separately and can resolve described issue.

**Comment by makus82** [comment]
moved to Issue #941
