### ISSUE TITLE
Normalise the zoom on various screens.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#222]
The main cityscape screen obeys command line or config file parameters such as "OpenApoc.exe --Framework.Screen.Width=1920 --Framework.Screen.Height=1200" but other screens do not, making them difficult to play on large modern monitors.

See the photos, and sorry about the blurring.
![apoc 1](https://user-images.githubusercontent.com/6434813/32101408-9a8c5c68-bb74-11e7-9eeb-651e33760eb0.jpg)
![apoc 2](https://user-images.githubusercontent.com/6434813/32101410-9abd92ba-bb74-11e7-8fd7-cbd5ac25906c.jpg)
![apoc 3](https://user-images.githubusercontent.com/6434813/32101411-9afdbb74-bb74-11e7-85ab-255bd4c89794.jpg)
![apoc 4](https://user-images.githubusercontent.com/6434813/32101413-9b7c1ed8-bb74-11e7-94e4-0d374fd021a2.jpg)
![apoc 5](https://user-images.githubusercontent.com/6434813/32101414-9ba822a8-bb74-11e7-8171-ecca335c3080.jpg)
![apoc 6](https://user-images.githubusercontent.com/6434813/32101415-9bd28e26-bb74-11e7-8dfb-a4412acad498.jpg)
![apoc 7](https://user-images.githubusercontent.com/6434813/32101416-9bfcb890-bb74-11e7-9ed0-7f2f9e5b2431.jpg)
![apoc 8](https://user-images.githubusercontent.com/6434813/32101418-9c3a8850-bb74-11e7-8194-3b7f5d4a52ff.jpg)

**Comment by makus82** [comment]
its noutbook?
what diagonal of this monitor?

**Comment by Paddywhacker** [comment]
This is not a high end monitor.  It is a Dell 1907FP at 1280x1025 resolution.  At higher resolution the size discrepancy would be greater.  It is unplayable.

**Comment by makus82** [comment]
Viewable Size 19"
Image Aspect Ratio 5:4
Native Resolution 1280 x 1024 at 60 Hz

**Comment by JonnyH** [comment]
We currently don't do *any* scaling - if a sprite is 10 pixels wide, it'll be 10 pixels at 640x480 (the original resolution), so 1/64th of the width of the screen. It'll also be 10 pixels wide at 1920x1080, 1/192nd of the screen.

The render backend supports the scaling, we could even add fancier shaders in the future, but currently the mouse code doesn't work properly with that - making it kinda useless.

**Comment by Paddywhacker** [comment]
oops, that is the wrong monitor.  The main monitor, pictured here is a generic non-PnP monitor, a TV used as a monitor, at 1920 x 1200 resolution, as specified in the command line parameters.

**Comment by Paddywhacker** [comment]
... although Alexei managed to do so for the cityscape screen, enabled by command line parameters.

**Comment by makus82** [comment]
Patrick so you try change resolution by commands
and also using config file where wich 
[Framework.Screen]
Fullscreen=1
Height=1200
Width=1920
?

**Comment by JonnyH** [comment]
There's the options:

Framework.Screen.ScaleX and Framework.Screen.ScaleY that can be used to do the renderer scaling for the whole surface.

They take an integer percentage - IE the default is "100", "50" would make things twice the size on-screen (IE it renders internally at half the resolution of the display window).

But I believe this screws up the mouse input events, as they aren't scaled in the same way, so it's not really useful right now as it means the interactive areas are as if it wasn't scaled at all, so where the game thinks you 'clicked' isn't the same place where the mouse cursor is drawn...

But as this just uses the default linear blending, it's no different to just setting the Framework.Screen.Height/Width to a lower resolution and using your window systems window scale instead...

**Comment by Paddywhacker** [comment]
OK, I see there is a ticket for mouse behaviour with scaling.  Does that replace this ticket?

**Comment by Istrebitel** [comment]
So, basically, the issue for you is that while zoomed out city looks good and makes sense, zoomed out battlescape looks tiny and is not comfortable to play. Do I understand you properly now?

If, as you say, it's really unplayable for many people (I dunno, for me it's no problem to play battlescape in 1080p, but maybe I'm just used to it over the time spend developing it) that means we should implement separate scaling settings somewhere along the road to OpenApoc 1.0. Because if we just implement scaling, then people would have to constantly switch from low scale factor in city to high scale in battle.

Mouse ticket does not replace this ticket, it's about what JonnyH described above, the fact that we don't support scaling properly yet even though we have it.

**Comment by JonnyH** [comment]
Separate scaling for each of {Cityscape isometric, Cityscape map, Battlescape isometric, Battlescale map} may make sense.

And on top of that I feel that UI scaling within them may make sense if possible - having a 640x480 equip screen (for example) in the middle of a 4k display would look pretty silly IMHO...

I'd see that as a "post 1.0" feature though. Arguably, anything but a single "global" scale could be considered post-1.0 - as I suspect a global 1.5x/2x scale would be fine for "most" use cases. And people who want the "vanilla" experience can just leave it as 640x480 and use their windowing system scaler.

**Comment by Paddywhacker** [comment]
"--Framework.Screen.Width=1024 --Framework.Screen.Height=480 --Framework.Screen.Fullscreen=1" is a workable compromise with the current build, but I look forward to not having to do this because it causes my existing apps to be redistributed about my 3 monitors.  So let's flag this for "post 1.0".

**Comment by FilmBoy84** [comment]
#1040 resolves this issue (autoclosing #222)
Please raise any future issues with scaling in a new issue
