### ISSUE TITLE
The required number of movement points for a shot is too high

### ISSUE THREAD

**Issue by gonder1** [OpenApoc/OpenApoc#223]
The required number of movement points for a shot is too high
![screenshot3](https://user-images.githubusercontent.com/33162746/32120181-53d3e85e-bb60-11e7-91d6-f456febdfc92.png)
![screenshot4](https://user-images.githubusercontent.com/33162746/32120190-56cdfeaa-bb60-11e7-94c2-cd1173597ea8.png)

**Comment by gonder1** [comment]
The required number of movement points for a shot is too high
![screenshot3](https://user-images.githubusercontent.com/33162746/32120262-9bba3e8e-bb60-11e7-8a15-e73870a95cd7.png)
![screenshot4](https://user-images.githubusercontent.com/33162746/32120265-a06921ca-bb60-11e7-8786-149c58c860bc.png)

**Comment by Istrebitel** [comment]
Thanks for noticing, we went from vanilla ticks to openapoc ticks in game files, and this screwed up the TU costs which depend on those ticks. As openapoc functions on 4x as much ticks as vanilla, TU's rose 4x. Will fix now.

**Comment by Istrebitel** [comment]
okay, fixed, will be available in next build
