### ISSUE TITLE
Mouse event locations are incorrect when setting non-default Framework.Screen.ScaleX/ScaleY

### ISSUE THREAD

**Issue by JonnyH** [OpenApoc/OpenApoc#225]
The render is scaled, but the event coords are not, so all the locations for event handling would be inconsistent with where the cursor is drawn.

**Comment by FilmBoy84** [comment]
This appears to be resolved in #1040 however, there are still issues with ScaleX and ScaleY values and the method we record them in the .conf via an integer in relation to a value of 1.0

This will warrant a separate pull to change.
