### ISSUE TITLE
Add pls icon to Openapoc.exe file

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#227]
Add pls icon to Openapoc.exe file to highlight a file in the list
![favicon](https://user-images.githubusercontent.com/11581207/32136098-254abf00-bc12-11e7-8601-234b8fa7f95c.png)
here 16px png or if need ico i will make it 
tell me

**Comment by makus82** [comment]
![favicon33](https://user-images.githubusercontent.com/11581207/32136292-bb3b768e-bc13-11e7-86c5-33dd63b5db69.png)
![favicon22](https://user-images.githubusercontent.com/11581207/32136293-bb5898c2-bc13-11e7-85c8-b41bb05e456f.png)

**Comment by Istrebitel** [comment]
This is actually a great idea. JonnyH, do you know how to do this, so that appveyor ships exes with icons assigned to them?

**Comment by JonnyH** [comment]
I believe windows .exe files can have icons embedded in them at build time - I assume there's some option to add it in msbuild somewhere...
