### ISSUE TITLE
When buy vehicles game double order so i buy 2 instead 1

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#234]
#When buy vehicles game double order so i buy 2 instead 1
and 1 vehicle already at base and second start fly from manufacturer
even when i turn of put market stock on the right side =]
also 2 vehicles deducted from the market when i buy 1
wich vehicle equipment all good

**Comment by Paddywhacker** [comment]
Seems to be fixed in 0.0.147 (OpenApoc-v0.1-70-gaee5b702)
