### ISSUE TITLE
Purchased Griffin APC no path to base

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#237]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1443036/openapoc_log.txt)

[save_Griffin no path.zip](https://github.com/OpenApoc/OpenApoc/files/1443037/save_Griffin.no.path.zip)

In 0.0.147 (OpenApoc-v0.1-70-gaee5b702)

**Comment by makus82** [comment]
strange buy Griffon its arrive and when i send soewhere and click back to base its back to base..

**Comment by Paddywhacker** [comment]
Load the saved game and see the APC dithering about the same spot, unable to find a path.

Strangely, though, I crash when I start the timer on that saved game.  Log file attached:- 
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1443696/openapoc_log.txt)

**Comment by Paddywhacker** [comment]
Reproducible on 0.0.148 (OpenApoc-v0.1-70-gaee5b702) too.

Start a new game on hard.  Sell all of your vehicles.  Buy three Griffins.  Start the timer.  See them confused.

**Comment by AndreyCreator** [comment]
I also noticed this thing. But there is something strange in it. Because:

IF (I purchase multiple Griffons) AND (the game is on pause) AND (I command one Griffon to move somewhere while on pause) THEN (other Griffons stop and don't move to base).

**Comment by FilmBoy84** [comment]
Can no longer replicate this issue
Closing until a current example is found
