### ISSUE TITLE
Time speed accelerates wich time speeds 1-4 but vehicles not (vehicle lot slower then in vanila)

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#243]
Time speed accelerates wich time speeds 1-4 but vehicles not (vehicle lot slower then in vanila)

**Comment by makus82** [comment]
i think all time indicators need to be doubled...

**Comment by makus82** [comment]
https://youtu.be/GB54cYHpyRE

**Comment by redv** [comment]
It's an engine issue (I mean the game's engine :)
The engine's rendering isn't optimized and much slower than vanilla what affect to vehicles. I tested optimized version #247 (strategy view mode only). In that version, vehicles behave like vanilla.

**Comment by makus82** [comment]
Strange beacose i use last build before appveyor down
and there vehicles slower then in vanilla
in openapoc speed 4 its like speed between 2-3 of vanilla 

redv могу инвайт кинуть в слак нужен твой email

**Comment by redv** [comment]
No, I mean the my test build of OpenApoc #247 . In this build the strategy view mode works much faster and speed of vehicles is close to vanilla. Thus I believe that this issue because the game's engine itself but not because vehicle's code improperly designed.

Мой емайл должен быть виден в аккаунте: https://github.com/redv

**Comment by JonnyH** [comment]
The update() look *should* be doing a fixed time increment every rendered frame - so if the device it's running on can't keep up, it should slow down consistently. The same amount of time should pass per rendered frame, not wall clock time, so everything should slow down at the same rate - vehicle movement, in-game clock time, any other time related stuff.

The most interesting thing to measure would be the difference in openapoc between the different speeds - if the vehicles (and clock time) don't move 2x faster between speed 2 and 3, for example, that's a bug. If they are proportionally correct, then it's likely a scale issue with the values stored as the vehicle speed (We already scale the values slightly differently, as the original ran at much lower than 60fps :)

**Comment by makus82** [comment]
ok so i will close this when it will be in last build)

**Comment by JonnyH** [comment]
No, don't close it - unless you've proven the scale between the different speeds (1/2x, 1x, 2x, 4x etc) is correct relative to each other in-game - and then we likely need to tune the global scale so it's all approximately the same speed as the original (in real-time)

**Comment by makus82** [comment]
I said so =P
if in last build will be correct speeds
but about global speed (speed 5) i dont know how to observe that they correct)

**Comment by JonnyH** [comment]
You could run the original for (say) 1 minute real time at normal speed, and record how far the in-game clock progressed.

Then do the same for openapoc, and see if/how much of a difference there is between the two ingame clocks.

**Comment by makus82** [comment]
clocks ye its easy 
but i create issue mainly beacose of vehicles move speed )
but i hear ya

**Comment by makus82** [comment]
damn i dont link it when create 
https://www.youtube.com/watch?v=GB54cYHpyRE

**Comment by makus82** [comment]
its still slower then in vanilla from 1-4 speed

**Comment by makus82** [comment]
speed is little different but i guess we can say that its fixed more or less
