### ISSUE TITLE
Game crash after few days on 5 time speed

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#246]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1468214/openapoc_log.txt)
Game crash after few days on 5 time speed
also i ordered to fly out and hang in Valkyrie and Phoenix near the base - wanted to see how they run out of fuel and will fall

after few days game start lagging at 5 speed
and after few more crash

also i use window 720p resolution and not full screen 
win7 , CPU i7 3770k, RAM 8Gb

**Comment by makus82** [comment]
[openapoc_log.zip](https://github.com/OpenApoc/OpenApoc/files/1468316/openapoc_log.zip)
second crash

**Comment by makus82** [comment]
OK i found that if game in window mode
and second window for logging is visible 
game starts lagging hard if its under game window all good
or if game in fullscreen

**Comment by FranciscoDA** [comment]
This is probably caused by a bug in the base defend screen:
```
(gdb) info stack
#0  0x00005555556cd326 in std::operator==<char> (
    __rhs=<error reading variable: Cannot access memory at address 0x120>, 
    __lhs="") at /usr/include/c++/7.2.0/bits/basic_string.h:5818
#1  OpenApoc::UString::operator== (this=this@entry=0x55555697edd0, other=...)
    at /home/francisco/OpenApoc/library/strings.cpp:118
#2  0x0000555555778499 in OpenApoc::Label::setText (
    this=this@entry=0x55555697eca0, Text=...)
    at /home/francisco/OpenApoc/forms/label.cpp:59
#3  0x000055555588bc45 in OpenApoc::BaseDefenseScreen::begin (
    this=0x55555754e3e0)
    at /home/francisco/OpenApoc/game/ui/city/basedefensescreen.cpp:59
#4  0x00005555556e1f89 in OpenApoc::Framework::run (this=0x555556068b40, 
    initialStage=...) at /home/francisco/OpenApoc/framework/framework.cpp:570
#5  0x00005555556be357 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/francisco/OpenApoc/game/main.cpp:26
```
I'll investigate into it

**Comment by makus82** [comment]
well will test but doubt that is only this coz =]

**Comment by FranciscoDA** [comment]
Try this build: https://ci.appveyor.com/project/FranciscoDA/openapoc

**Comment by makus82** [comment]
Hm when i hide logging window its goes stable
and no crashes except whe i use F1 + X and want to speed 5 right after
also in some cases game start like ... freez but like 1 big  freez then go normal

**Comment by makus82** [comment]
Now wich visible hidden window 
use F1 + X and want to speed 5 right after  its give me 
![image](https://user-images.githubusercontent.com/11581207/33116064-f4dcf122-cf6b-11e7-9ff9-30c2417c8e1f.png)

**Comment by FranciscoDA** [comment]
Strange. I can't reproduce this under linux. Neither the error message nor the slowdown :/
BTW, it seems the fuel consumption is bugged. Speed 5x certainly does not consume fuel faster than 3x

**Comment by JonnyH** [comment]
I know on windows logging to console can be *extremely* slow - perhaps there's something causing excess log output?

Or a memory/resource leak that either due to a driver bug/interaction, or just larger on windows?

There's a number of issues that the "sanitize" build and/or valgrind notice - I hope to sit down and try to fix them in the next few days. Perhaps that will highlight some issue.

**Comment by makus82** [comment]
i check i think all good in fullscrn and window

**Comment by FilmBoy84** [comment]
Not sure if this is related to issue #261 
As @JonnyH points out the log slows things greatly
Either way, still crashing here after a couple of days on ultra-speed
