### ISSUE TITLE
Passenger Module does not add additional passengers to craft

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#253]
Tested with the Valkyrie and one passenger module, the capacity of the craft does not raise to 12 as it should, instead staying at 8.
The passenger module should add four passengers per module

**Comment by FranciscoDA** [comment]
Whoops, I screwed up in a previous commit. Will fix ASAP

**Comment by FilmBoy84** [comment]
This still appears bugged under 0.1-83.

Now any number of agents can be added to a craft, regardless of number of passenger modules!
For example i can currently fit all 15 of my agents in the Valkyrie with no extra modules.
Passengers are listed as 15/8! :D

**Comment by redv** [comment]
Whoops! It will be fixed.

**Comment by FilmBoy84** [comment]
Issue fixed by @redv
Closing
