### ISSUE TITLE
Player does not start with correct vehicle equipment

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#254]
The Valkyrie should already have a cargo module and a passenger module at the start of play.
Currently this is not the case under OpenApoc.
Will add further vehicle specs to this as i find them.

Valkyrie In OpenApoc; missing Cargo Module and Passenger Module
![image](https://user-images.githubusercontent.com/33913088/33224503-ec1de8f0-d161-11e7-8fd0-ddb254bf18a4.png)

**Comment by makus82** [comment]
check all good =]

**Comment by FilmBoy84** [comment]
Excellent, Valkyrie does have a passenger module and cargo module now. Thanks @makus82 and @FranciscoDA

**Comment by makus82** [comment]
So we should close this ?)

**Comment by FilmBoy84** [comment]
Yep, close it, everything appears to start with the correct modules at the moment.
