### ISSUE TITLE
Emergency Vehicles do not pick up crashed road vehicles

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#255]
Experiencing a problem with a CoS bike not being picked up by a flying emergency vehicle when it crashed. The emergency vehicle flies around the bike aimlessly diving and rising.
Tested on "Easy" Map.

**Comment by makus82** [comment]
Alex say early that we need finish some ground vechicles mechanics  .. somthing like that

**Comment by FilmBoy84** [comment]
Hopefully this issue will be fixed soon.
After a day or two of things building up, so many recovery missions are underway the game slows to a crawl and crashes...

[save_Medium 1.zip](https://github.com/OpenApoc/OpenApoc/files/1528061/save_Medium.1.zip)

**Comment by FilmBoy84** [comment]
This issue seems to cause MASSIVE slow-down in the cityscape, possibly linked to the performance issues referenced in #247 . Can it be fixed promptly please? Many games are doomed to slowing to a crawl or CTD with the sheer number of unrecovered vehicles on the cityscape after a couple of days.

**Comment by FilmBoy84** [comment]
Between 2345 and 2355 this CTD seems to occur...

![image](https://user-images.githubusercontent.com/33913088/34469901-0751e8f8-ef1f-11e7-9d08-1c53e348fec2.png)
![image](https://user-images.githubusercontent.com/33913088/34469903-0de4d89c-ef1f-11e7-9062-ccde1d3ade1d.png)

**Comment by FilmBoy84** [comment]
Vehicles are cleared at last :) Thanks @redv 
However, for some reason smoke from their crash remains in the game, this probably needs fixing too

![image](https://user-images.githubusercontent.com/33913088/34538380-10d86dd8-f0c4-11e7-8b8b-5a011897a408.png)

**Comment by redv** [comment]
Fixed smoke issue. The fix will work for newly crashed vehicles or a new game.

**Comment by FilmBoy84** [comment]
@redv resolved this issue
can no longer replicate
Closing
