### ISSUE TITLE
RUSSIAN LANGUAGE: some strings not picked up translated words

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#259]
Some string dont pick up translated strings from file like 
(if checked string tranlated at transifex and picked up in game)
(? - this string not found at transifex)

**In main menu options**  

- [ ] Message Toggles  > Контроль оповещений
- [x] Vehicle moderately damaged  > Корабль умеренно поврежден
- [x] Agent has died  > Агент умер
- [x] (Auto-scroll at transifex) Auto scroll  > Автопрокрутка
- [ ] Skirmish Mode
- [ ] Exit Battle
![image](https://user-images.githubusercontent.com/11581207/54752653-99b7d100-4be7-11e9-9c79-6d08c06e3708.png)

**In select project screen**

- [x] Select Biochemistry Project  > ВЫБРАТЬ ПРОЕКТ ПО БИОХИМИИ
- [x] Select Physics Project > ВЫБРАТЬ ПРОЕКТ ПО ФИЗИКЕ
- [x] Select Manufacturing Project > ВЫБРАТЬ ПРОЕКТ ДЛЯ ПРОИЗВОДСТВА
- [ ] Lab Size Needed  > Размер
- [ ] All Projects names in list of research

![image](https://user-images.githubusercontent.com/11581207/54752680-ad633780-4be7-11e9-843b-6d13c167a2e7.png)

- [x] Psi-defence  > Пси-защита

![image](https://user-images.githubusercontent.com/11581207/54752718-c1a73480-4be7-11e9-91bd-85400fb8a448.png)

- [ ] all types of ammo like: Explosives, Laser Beam, Armor Piercing etc
- [ ] all equipment names like: Megapol Smoke Grenade, Megapol Lawpistol etc

...

**Comment by AndreyCreator** [comment]
Вот мой вариант:
"Максимальная скорость" -> "Скорость"
"Кол-во патронов" -> "Боезапас"
"Скорострельность" -> "Темп стрельбы" (это не моя выдумка, а технический термин, если что)
"Стоимость постройки" -> "Цена"
"Расходы на содержание" -> "Содержание"
"Время строительства, дней" -> "Дни на постройку"
"Грузоподъемность" -> "Вместимость"
"Lab Size Needed" -> "Требуемая лаборатория"

**Comment by makus82** [comment]
also in russian language window that pops up when press at rearerched project or else
there ok button have wrong translation "Нормально"

**Comment by makus82** [comment]
- [ ] COMMENCE INVESTIGATION
- [ ] All selected units and crafts have arrived at Angel Heart Heights. Proceed with investigation? (4 units)

![image](https://user-images.githubusercontent.com/11581207/54835958-e4ab1480-4ccb-11e9-80dc-7cd1b230ab9e.png)

**Comment by FilmBoy84** [comment]
JonnyH is currently working through how OpenApoc translates strings
So the information in this article is likely to become invalid/change
For that reason closing
We can reference this issue if it is still a problem after the new implementation
