### ISSUE TITLE
Cargo Transport Stuck in Building (Stopping other Transports)

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#283]
Under 0.1-117 i appear to have stuck cargo transport. This stops other vehicles entering/exiting warehouse 2 on Easy Map... Savegame Attached...

EDIT: Loading the game also causes issue #260 interestingly, despite this being a fresh game...

![image](https://user-images.githubusercontent.com/33913088/33433100-3d18f618-d5d2-11e7-8a18-021a39b64899.png)

[save_Stuck Transport 1.zip](https://github.com/OpenApoc/OpenApoc/files/1517920/save_Stuck.Transport.1.zip)

**Comment by emptyVoid** [comment]
The save game is corrupted -- the base building houses a vehicle which is not present in `vehicles.xml`:
```xml
	<entry>
		<key>BUILDING_WAREHOUSE_TWO</key>
		<value>
			<name>Warehouse Two</name>
			<city>CITYMAP_HUMAN</city>
			<function>BUILDINGFUNCTION_WAREHOUSE</function>
			<owner>ORG_X-COM</owner>
			...
			<base_layout>BASELAYOUT_5</base_layout>
			<base>BASE_1</base>
			<battle_map>BATTLEMAP_30ware</battle_map>
			...
			<currentVehicles>
				...
				<entry>VEHICLE_794</entry>
				...
			</currentVehicles>
			...
		</value>
	</entry>
```

**Comment by FilmBoy84** [comment]
I haven't seen this issue in a long, long, time
Also, as emptyvoid points out, the save is corrupted
Closing
If the problem returns, please create a new issue and reference this as appropriate
