### ISSUE TITLE
Raiding a destroyed building should be prohibited.

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#285]
In Vanilla, X-COM cannot raid a destroyed building. A message appears accordingly (See Screenshot).
In OpenApoc you can raid a destroyed building so this should be changed as OpenApoc makes it easy to abuse raids for resources even when the building being raided is not there.

![ufo2p_000](https://user-images.githubusercontent.com/33913088/33439470-68da329a-d5e5-11e7-83fc-48708822cc9c.png)

**Comment by Darkestaxe1** [comment]
I think this makes a lot of sense and seemed more like unfinished behavior in the original. Perhaps add it to the list of toggleable changes like invulnerable roads.

**Comment by FilmBoy84** [comment]
@Darkestaxe1 It should not be an Optional Function IMHO, this behaviour was as in the screenshot i made above in vanilla, you cannot raid a destroyed building, full-stop. After-all if the building is destroyed what is there to raid???

Currently, you can raid destroyed buildings in OpenApoc, the point of this issue is to ask for this "bug" to be fixed as raiding destroyed buildings allows the player to get lots more resources through raids when in normal vanilla play the player can not raid a destroyed building until it is rebuilt... That slows down raid spamming by the player for resources... Something i can freely abuse in OpenApoc...

**Comment by FilmBoy84** [comment]
This was fixed and merged nearly a year ago
Closing :)
Thanks for fix @redv <3
