### ISSUE TITLE
Destroyed Buildings are Rebuilt Completely next day...

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#286]
Currently OpenApoc appears to replace the entire destroyed building the next day.
In Vanilla buildings are rebuilt a handful of tiles at a time, sometimes taking weeks to fully rebuild.

Needs some testing to see how many tiles are rebuilt each day and how much they cost the parent organisation before we can implement.

1. Is the cost of the tile a uniform cost?
2. Does the cost of a tile vary according to building/tile type?
3. How does vanilla choose which tiles are replaced each day?
4. When is a building classed as destroyed?
5. When is a building classed as built enough to raid/investigate?
6. Can UFOs drop Aliens in Destroyed Buildings? (They should not)
7. Does Micronoid Rain affect Destroyed Buildings? (It should not)

**Comment by FilmBoy84** [comment]
This should be resolved once #916 is merged
Closing for now (we can always reopen)

**Comment by idshibanov** [comment]
"If building is destroyed" check will be handled properly now, for sure. Let's keep this issue closed and create a new one just for the rebuilding part. Speed is available right now, but we have to change the logic around it.
1. Refactor rebuild code - it shouldn't be global (done by the city) and should start from the bottom layer to the top
2. Use the variable to limit how much can be done in one day.
3. Rebuilding costs organization money (if no one owns it then Government pays for rebuild).
