### ISSUE TITLE
Enable unit tests in windows build

### ISSUE THREAD

**Issue by JonnyH** [OpenApoc/OpenApoc#287]
There are a number of unit tests (under the tests/ directory, funnily enough) that are currently hooked to the CMake build system, and run automatically under travis, but are currently ignored in the msbuild/visual studio build on windows.

Hopefully it wouldn't be a massive task to enable them - there's already 3 built - but they're rarely run so integrating them into the visual studio 'test' functionality would be useful - especially if they get picked up in the appveyor auto builds.

I don't think much code would be required, it's mostly a knowledge / willingness to explore visual studio's project and build options than anything. Perhaps wrapping the main() function, if that is required.

**Comment by SupSuper** [comment]
Fixed by #527 as Appveyor and VS2017 support CTests now.
