### ISSUE TITLE
FreeBSD: generates bus error as soon as it goes to ultra speed

### ISSUE THREAD

**Issue by nbe-renzel-net** [OpenApoc/OpenApoc#290]
Trying to get OpenApoc running under FreeBSD. Compilation works so far (with some patches) - resource extraction must be done manually.

Game starts, but crashes with a bus error as soon as you go ultra-speed. Please see bug report here:
[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223769](url)

In short, it crahses somewhere in `OpenApoc::FlyingVehicleMover::update(OpenApoc::GameState&, unsigned int) ()`

Perhaps someone of you has got an idea how to fix that...

**Comment by JonnyH** [comment]
Possibly the same as issue #274 ?

**Comment by nbe-renzel-net** [comment]
Confirmed - after applying the workaround mentioned there I am able to proceed in time and get to the first mission...

**Comment by FilmBoy84** [comment]
I can no longer replicate this issue
It appears fixed some time ago
Closing for now
