### ISSUE TITLE
Random vehicles will not move after issuing command

### ISSUE THREAD

**Issue by gaudium007** [OpenApoc/OpenApoc#291]
Hello, i've been testing out this build OpenApoc-x64-v0.1-124-g7dd8174b on stream.
First issue i had is a crash when i tried to outfit a vehicle.
You click on the icon with the vehicle and the + sign at the UI menu at the bottom and from that screen click on the top right vehicle with the missile and it crashes.

Another problem that i had is random vehicles will stop responding to commands.
Sometimes it happens as soon as you start the game, sometimes right after you buy new ones, sometimes after they moved to one place and won't move elsewhere.

I have a save where i had a few vehicles in a building and when a UFO appeared the game just crashed.
The save is crashing as soon as i load it, i hope it can help you identify the problem.

https://www.sendspace.com/file/gjv1pa

**Comment by makus82** [comment]
Hey gaudium007 =]
ty for submit crash 
but here little guide

If you find a bug:
1) Visit https://github.com/OpenApoc/OpenApoc/
2) Click "Issues"
3) Click "New issue"
4) Create an account if you don't have one yet
5) Describe the bug, if you can, describe how to reproduce the bug reliably
6) Attach the "openapoc_log.txt" file from OpenApoc folder​* Note that this file is re-written every time you launch OpenApoc, so attach it after you have encountered the bug and closed the game, before you run the game again.

**Comment by gaudium007** [comment]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1522568/openapoc_log.txt)

This is the vehicle equipment crash log.

[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1522571/openapoc_log.txt)

This is the save game crash log.

Yeah i forgot to attach them from the beginning 💃

**Comment by SirShoorph** [comment]
Sorry for necroposting but I have the same problem.

> Another problem that i had is random vehicles will stop responding to commands.
Sometimes it happens as soon as you start the game, sometimes right after you buy new ones, sometimes after they moved to one place and won't move elsewhere.
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/2536146/openapoc_log.txt)

**Comment by FilmBoy84** [comment]
@SirShoorph Don't worry about necroing the bug tracker; it helps us know which issues are still present, so we're always grateful

I've been able to recreate this myself, so will try to look into it for you

Many thanks for the report

**Comment by FilmBoy84** [comment]
Can no longer recreate this issue
Closing unless there is another occurrence
