### ISSUE TITLE
Vehicles out of fuel? Stuck on the road.

### ISSUE THREAD

**Issue by gaudium007** [OpenApoc/OpenApoc#299]
Hello again, i am not sure how you are supposed to overcome this issue.
History log in game just says "Vehicle X is out of fuel and the vehicle just sits still on the road.

Here is the save
https://www.sendspace.com/file/2065b0

Here is the log
https://www.sendspace.com/file/728urm

Also a note that it seems that half of the vehicles just show "0/14k" fuel but can fly with no problems.

The log is quite large that is why i uploaded it externally.
Another problem that keeps appearing is the time laps of the fastest speed becomes a slideshow where it just jumps 5 minutes instead of fluidly go faster.
Maybe you can reproduce it with the save because i saved it when it started.
Hope it helps.

**Comment by makus82** [comment]
Just upload all to this message)

**Comment by FilmBoy84** [comment]
@gaudium007 
Can stuck road vehicles be picked up by aircraft from the parent organisation?
(Like other recoveries in OpenApoc)
It would be good to know if this is a way around the problem

**Comment by makus82** [comment]
its seems that all vehicles in city cant pick up damaged one and bring it to base
they just swarm over it and cant pick up

**Comment by FilmBoy84** [comment]
Ah yes, a slight variant of issue #255 but with player vehicles instead of city ones, i remember now :)

**Comment by gaudium007** [comment]
It doesn't allow to upload a file size bigger than 10mb :)

I was the parent organisation, and tried clicking on it or using other vehicles. I have no idea if you have such an option or need to have a special vehicle?
My cars were on the road, they just ran out of fuel while driving i guess.
No emergency vehicles were flying around them at all.

Oh so it is a known issue, ok. :)

**Comment by makus82** [comment]
RMB >send > ZIP

**Comment by FilmBoy84** [comment]
Issue no longer possible to replicate
Closing
