### ISSUE TITLE
Multiworm Eggs and Chrysalis Recovery

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#304]
If all other aliens are dead or unconscious, tac mission should end and automatically and recover ANY dead or alive eggs and Chrysalis (As per vanilla)

Currently, you have to kill or stun Chrysalis and Eggs to end a tac mission.

![wp_20171124_003_mod1a](https://user-images.githubusercontent.com/33913088/33563884-ffdc84b2-d910-11e7-8579-917af0a23ead.jpg)

**Comment by AndreyCreator** [comment]
Fixed.

**Comment by FilmBoy84** [comment]
Thanks Andrey

**Comment by FilmBoy84** [comment]
I fixed this based on Andrey's work the other week
There is a potential link with bug #418 but i cannot see anything that would cause that yet
In either case, recovery now happens for missions where there are eggs or chrysallis
Closing issue
