### ISSUE TITLE
Vehicle ID Mismatch and CTD after selling manufactured craft and save/load

### ISSUE THREAD

**Issue by Darkestaxe1** [OpenApoc/OpenApoc#314]
To reproduce:
Create a new game
Make a vehicle
 -Save and reload game
 -Sell vehicle
or
 -Sell vehicle
 -Save and reload
pass time in cityscape, game will crash with error: No vehicle matching ID "VEHICLE_808"
Limp along gives: No Vehicle object matching ID "VEHICLE_808" found
Limp along again and game CTDs

**Comment by makus82** [comment]
Hey Darkestaxe1 =]
ty for submit crash
but here little guide

If you find a bug:

Visit https://github.com/OpenApoc/OpenApoc/
Click "Issues"
Click "New issue"
Create an account if you don't have one yet
Describe the bug, if you can, describe how to reproduce the bug reliably
Attach the "openapoc_log.txt" file from OpenApoc folder​* Note that this file is re-written every time you launch OpenApoc, so attach it after you have encountered the bug and closed the game, before you run the game again.

**Comment by Darkestaxe1** [comment]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1557626/openapoc_log.txt)
E 98617718405 class std::shared_ptr<class OpenApoc::Vehicle> __cdecl OpenApoc::Vehicle::get(const class OpenApoc::GameState &,const class OpenApoc::UString &): No vehicle matching ID "VEHICLE_808"
