### ISSUE TITLE
Another Vehicle ID based CTD

### ISSUE THREAD

**Issue by Darkestaxe1** [OpenApoc/OpenApoc#317]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1557735/openapoc_log.txt)

[save_DKX.zip](https://github.com/OpenApoc/OpenApoc/files/1557738/save_DKX.zip)

Not sure what exactly what does or doesn't cause this one, but I got it by:
-Made new game (medium)
-Investigated first infested building (preemptively) with Valkyrie
-Sold all my starting craft
-Built a bunch of workshops (debug F10)
-Started construction on an annihilator and two retaliaters (debug F10)
Passing time then caused CTD: No vehicle matching ID "VEHICLE_793"

Using build OpenApoc-v0.1-150-gef071d58

**Comment by redv** [comment]
Its looks like the same bug as two previous. This bug happens after selling vehicles.
You can try build which contains fix #316 
https://ci.appveyor.com/project/OpenApoc/openapoc/build/0.0.45

**Comment by Darkestaxe1** [comment]
https://ci.appveyor.com/project/OpenApoc/openapoc/build/0.0.45/job/h2f3xhnmd9i83fni/artifacts

If you look at the filenames you will see that they are OpenApoc-v0.1-150-gef071d58. Maybe I should have called it build 0.0.45? At any rate it's a clean new game start-to-crash in gef071d58/0.0.45.

I don't know if it's related to the old crashes or if it was introduced by your fix, but my money is on the former. I crashed out of several games with these errors before I got frustrated and started making bug reports, and a lot of the crashes I was getting were in cases like this one.

I started another game after it and was able to manufacture up some craft just fine when I didn't sell off my starting craft first. However I started getting errors when saving after sending an Annihilator through a portal and selling off my vehicles. The errors said something about a mission state and I was able to limp through. Those saves CTD on loading. 

Serialization failed: "Invalid enum value for enum OpenApoc::VehicleMission::MissionType:"" vehicles.xml:/vehicles/entry/entry/entry/entry/entry/entry/entry/entry/entry/entry/entry/entry/entry

I suspect you squashed a worker ant and we're looking for the queen.

**Comment by FilmBoy84** [comment]
It appears this is related to issue #260 as @redv has pointed out this relates to the parts of the code dealing with sales/transactions being a complete mess and most likely needing a refactoring before a fix can be made...

Can this report be merged with Issue #260 ?

**Comment by redv** [comment]
I mean was written the fix for this issue (but not merged yet): https://github.com/OpenApoc/OpenApoc/pull/316

It possible to test this fix before it will be merged into master:
https://ci.appveyor.com/project/OpenApoc/openapoc/build/0.0.45

I think that the fix does not fixes the #260 at least should not be.

**Comment by FilmBoy84** [comment]
@redv you are correct, it does not fix #260 however, it does appear to reduce the instances of it occurring until the player enters the alien dimension and either sells a vehicle (as @Darkestaxe1 has pointed out) or has it destroyed following entering the alien dimension - basically any act that removes the vehicle from player ownership will create the error sooner or later which is odd, as looking at your build, and testing it, the issue should be fixed.

I'll try the build with a new save and run it until i get a crash before reporting back

**Comment by CraigVA** [comment]
I'm still getting this error, in this save it crashes right after unpausing saying there's no vehicle matching ID 794.  It's day 1 and I had bought, chopped, and sold all the available stormdogs for cash, along with the starting wolfhound.

[save_1.zip](https://github.com/OpenApoc/OpenApoc/files/1570401/save_1.zip)
[openapoc_log.zip](https://github.com/OpenApoc/OpenApoc/files/1570402/openapoc_log.zip)

**Comment by FilmBoy84** [comment]
Issue appears fixed by both @redv and my own PRs
Closing for now
