### ISSUE TITLE
Game cannot start for error Failed to open "music" from the CD

### ISSUE THREAD

**Issue by meepeek** [OpenApoc/OpenApoc#319]
Hi,

I successfully compiled yesterday and trying to run the binary in build/bin, I did get the cd.iso from steam and placed it in data as instructed, but it returns me an error as follow:

```
thee@joke-PC:~/games/OpenApoc/build/bin$ ./OpenApoc
E 392951885 OpenApoc::Framework::Framework(OpenApoc::UString, bool): Failed to open "music" from the CD - likely the cd couldn't be loaded or paths are incorrect if using an extracted CD image
  called by:
  0x5579fa9b2c14 _ZN8OpenApoc3LogENS_8LogLevelENS_7UStringERKS1_+0x314 (./OpenApoc)
  0x5579fa9ab2f7 _ZN8OpenApoc9FrameworkC1ENS_7UStringEb+0xba7 (./OpenApoc)
  0x5579fa9857de main+0x48e (./OpenApoc)
  0x7f1c322632b1 __libc_start_main+0xf1 (/lib/x86_64-linux-gnu/libc.so.6)
  0x5579fa992d3a _start+0x2a (./OpenApoc)
```

The system was Deepin linux, debian based.

**Comment by JonnyH** [comment]
By default it searches in the current working directory for the "./data" directory and the "./data/cd.iso" file. You can either run OpenApoc from the root of.the git repository, symlink the "data" directory from the root of the repository to the build output directory and run it from there, or set the "Framework.Data" and "Framework.CD" options to the paths to the data directory and CD file respectively (They can be set on the command line like "./OpenApoc --Framework.Data=/path/to/data --Framework.CD=/path/to/cd.iso".

**Comment by meepeek** [comment]
It works, thanks a lot.
