### ISSUE TITLE
Aliens invading new base with no soldiers causes CTD

### ISSUE THREAD

**Issue by Darkestaxe1** [OpenApoc/OpenApoc#320]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1564123/openapoc_log.txt)
to reproduce, make a new game on medium, 
buy the $4800 slums base in the upper-right of the map, (I started building stores and living quarters)
pass time until aliens invade it on day 2

**Comment by FilmBoy84** [comment]
Merged as Issue #446 
Closing this iteration
