### ISSUE TITLE
Cannot fill living quarters on new bases

### ISSUE THREAD

**Issue by Darkestaxe1** [OpenApoc/OpenApoc#322]
If you start a new game and build a second base with a living quarters, you will not be able to hire 10 people. The game will tell you that transfer is limited by available living space.

How many people you can hire is inconsistent and seems to change with the accommodations available in your main base (not sure), and the indicator in the upper right will show that hireing 6 people will fill 61% of your living space, although 4 5 or 7 correctly shows 40% 50% or 70%.

**Comment by FilmBoy84** [comment]
RedV fixed this issue in December 2017
There are still some problems, as reported in #370 
But to all intents, this specific issue is fixed
Many thanks @redv
