### ISSUE TITLE
Can't rename soldiers or craft in their equip screens

### ISSUE THREAD

**Issue by Darkestaxe1** [OpenApoc/OpenApoc#323]
In xcom apoc if you click a soldier or crafts name in the equip screen it allows you to edit their name. You cannot edit the name in OpenApoc in this way, yet. 

The interface is the same as for renaming bases which does seem to work correctly.

**Comment by FilmBoy84** [comment]
Issue appears to be fixed
Many thanks @SiemensSchuckert
