### ISSUE TITLE
Crash in the cityscape while building is collapsing

### ISSUE THREAD

**Issue by CraigVA** [OpenApoc/OpenApoc#324]
[openapoc_log.zip](https://github.com/OpenApoc/OpenApoc/files/1566289/openapoc_log.zip)

I had just finished a cult raid (with the option to destroy buildings after raids turned off), and upon return to the cityscape I heard the sound of vehicle weapons fire.  It wasn't my own ship (its weapons were turned off), and after a quick glance around the map I couldn't see where it was coming from.  So I ignored it and unpaused time, then I heard more weapons fire and the sound of a building collapsing, and right at that moment the game crashed.

It could just be the same issue as #261 because the log file was 101 MiB.  I'm running Windows 10 64-bit with a GTX 1070 graphics card, and the game was running in 1080p fullscreen.

**Comment by FilmBoy84** [comment]
Could you check the list of "hostile vehicles" in your savegame, click on each one, and see if the vehicle is located inside the "roadway"/"garage" portion of the destroyed building. This is usually where vehicles are hidden away and may explain why you heard gun noises (sometimes other vehicles will target hostiles as the building collapses on them)

If your log is greater than 82MB you are correct, this may also be an issue linked to #261 as i have just been able to replicate your building crash with a large log file...

**Comment by FilmBoy84** [comment]
Can no longer replicate
Closing
