### ISSUE TITLE
scrollbars loose postions

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#330]
scrollbars loose postions
when open trade windows

![screenshot - 3](https://user-images.githubusercontent.com/11581207/34486236-77cf25ba-efd7-11e7-93b4-8d4b99138c67.png)
![screenshot](https://user-images.githubusercontent.com/11581207/34486237-7819b116-efd7-11e7-8add-e3b08fb35692.png)

**Comment by redv** [comment]
Attach please the settings file.

**Comment by makus82** [comment]
[OpenApoc_settings.zip](https://github.com/OpenApoc/OpenApoc/files/1598067/OpenApoc_settings.zip)

**Comment by makus82** [comment]
also this bug disappear after list moves

**Comment by redv** [comment]
It can be fixed by removing
```
[Framework.Screen]
Fullscreen=0
Height=480
Width=640
```
Something wrong with scaling.

**Comment by makus82** [comment]
yes other resolution good but 
Height=480
Width=640
output this bug

**Comment by JonnyH** [comment]
Scaling is known-broken at this point - it's handled inconsistently between the input events and control "position" - you can end up being unable to click buttons on screen, or it thinks the cursor is in a different place to where it is drawn.

**Comment by makus82** [comment]
yes its redraw after some moves and its not critical

**Comment by AndreyCreator** [comment]
Fixed. Close it.
