### ISSUE TITLE
"No vehicle matching pointer" Crash

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#332]
![image](https://user-images.githubusercontent.com/33913088/34538439-4c1595e2-f0c4-11e7-99d6-df410671af38.png)
![image](https://user-images.githubusercontent.com/33913088/34538443-5146f01a-f0c4-11e7-8f72-5113e9b36d1e.png)
![image](https://user-images.githubusercontent.com/33913088/34538447-5560f484-f0c4-11e7-973a-f046e0917e95.png)

**Comment by Quickmind01** [comment]
Here is a reproducible way to do this. Load the save file and before unpausing, make the stuck Hawk Air Warrior crash with debug ctrl+alt+shift+left click. Diablo will come to the rescue, but before we make it back to base, Diablo and Megapol will fight. The Hawk Air Warrior will get destroyed and Diablo will continue going after Megapol. I believe the road getting taken out may be part of the issue, or assisting with our recovery and a second Hawk Air Warrior is the issue. But I was able to get this to happen two times in a row automatically.

This is using the Weapons Mods.

![image](https://user-images.githubusercontent.com/51022165/64079223-c8fc5f00-ccaa-11e9-98fb-787a1823e7be.png)


[save_Superhuman Stream 1 - Cityscape.zip](https://github.com/OpenApoc/OpenApoc/files/3563687/save_Superhuman.Stream.1.-.Cityscape.zip)

**Comment by Quickmind01** [comment]
I believe I have confirmed that a second Hawk Air Warrior from Diablo comes out after my HAW is destroyed. For some reason, this second one goes into my base and that error window pops up. This should be reproducible.

**Comment by emptyVoid** [comment]
Cannot reproduce with the provided save game (could be already fixed).

**Comment by FilmBoy84** [comment]
No probs, will close the issue
If it happens again, we can make an updated issue :)

Many thanks @emptyVoid
