### ISSUE TITLE
City Organisations recover UFOs before X-COM

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#333]
Since the fixing of #255 it appears that the city/organisations will now move to recover UFOs before X-COM does.

Sometimes, the city will return these to X-COM if they are not manned such as UFO1 and UFO2 types (Which is a GREAT feature - this SHOULD be in OpenApoc), but other times the UFOs are returned to other organisations (Such as CoS; again this is cool as X-COM and CoS craft fight to grab the UFO first, but it's not Vanilla)

Not sure if this is intentional or not, but it is markedly different from Vanilla (Maybe changed to an [M] Feature in the options)

**Comment by redv** [comment]
Yes, its Cult of Sirius rescue UFO because they allied. Really! O_o

**Comment by FilmBoy84** [comment]
Ha ha, it's certainly a wonderful side effect of them being allied, it appears CoS create a mission to recover the UFO.

Here's the ensuing battle with CoS...
![image](https://user-images.githubusercontent.com/33913088/34539732-a687b17c-f0c9-11e7-98b8-d97f7af58da9.png)

**Comment by makus82** [comment]
This can be great mode where criminal or not only criminal can steal ufos
as expencive and not claimed and unowned object

**Comment by FilmBoy84** [comment]
@makus82 It would also give organisations another reason to come into conflict with X-COM, personally i love this effect of the recovery side of things but it was rather... unexpected... :)

**Comment by makus82** [comment]
unexpected you say? like in real life? =)

**Comment by FilmBoy84** [comment]
Whilst it would make a cool mod to have every organisation scramble to collect UFOs
This bug is now fixed
Closing Issue
