### ISSUE TITLE
Craft can become stuck when "crashing"...

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#334]
This Hoverbike appears to be stuck, constantly exploding but never reaching the ground... It's possible it's weight is not great enough to smash the tile of the gravball park allowing it to crash as intended... Or at the very least, drop to the nearest bit of open ground as UFOs do in vanilla.

![image](https://user-images.githubusercontent.com/33913088/34539675-65dad690-f0c9-11e7-812a-ea56c5b718fd.png)

**Comment by emptyVoid** [comment]
Should be fixed in #860.

**Comment by FilmBoy84** [comment]
Can confirm fixed with 860
Many thanks emptyvoid
Closing
