### ISSUE TITLE
999% Store level with odd Autocannon AP Ammo bug...

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#336]
For some reason, selecting agent/aircraft/ground equipment screen when X-COM has some Autocannon AP rounds in it's stores automatically makes the stores 999% full and appears to say it is both selling and receiving the ammo at the same time

This in turn gives X-COM a HUGE number of the ammo in its stores

Selecting the vehicle store type resets the store level back to normal but from the moment that extra ammo appears in X-COM equip screen the game is not going to let you do anything with the stores...

![image](https://user-images.githubusercontent.com/33913088/34541926-1f97135c-f0d2-11e7-8848-b48e063ea42a.png)
![image](https://user-images.githubusercontent.com/33913088/34541950-3cb648ae-f0d2-11e7-99b5-d4a89312a26f.png)
![image](https://user-images.githubusercontent.com/33913088/34542051-bcd816f2-f0d2-11e7-80f3-e98932e4b850.png)

**Comment by FilmBoy84** [comment]
It appears to be related to the Agent Equip screen when using preset agent equipment... In making an autocannon agent, setting it as preset 3, after a few agents of pressing "3" to equip, suddenly the ammo level goes up on the "on ground"/"stores" part of the screen IF you do not have enough items in the stores... (I.E. a negative value)

**Comment by FilmBoy84** [comment]
I have uploaded a video of this behaviour here:
https://youtu.be/QUwhEAxogcQ

Note that the bug occurs with NO AP ammo stored at base

**Comment by Atrosha** [comment]
I meet the same bug, but with HE ammo.

![Screenshot from 2019-03-18 00-08-20](https://user-images.githubusercontent.com/37053399/54498047-047cba00-4913-11e9-89cc-78843daaceab.png)

I just sell all HE ammo clips.

**Comment by JonnyH** [comment]
Does this still repro? I suspect it's a dup of #639
