### ISSUE TITLE
Destroyed buildings often trap vehicles in their basement causing performance issues and eventual CTD.

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#339]
In the attached screens, vehicles have been spawned at two destroyed CoS Temples, their attempts to run a mission that cannot be completed (because the path out of the garage is destroyed) slows the game down and fills the log with repeated mission attempts... This may be relevant to issue #247 as well.

Also note, Construction Vehicle 34 is trying to recover a vehicle stuck in a small hangar... If you destroy that vehicle to clear mission, another is spawned (Vehicle 35) and does the same, plus the vehicle sent to destroy Vehicle 34 will not close its mission on returning to base either (Hoverbike 3)...

@redv There appears to be a problem with clearing vehicle missions

![image](https://user-images.githubusercontent.com/33913088/34785441-15e43b94-f629-11e7-8412-3fa32cc05214.png)
![image](https://user-images.githubusercontent.com/33913088/34785670-b643d64e-f629-11e7-9714-ce3536b91deb.png)

![image](https://user-images.githubusercontent.com/33913088/34782625-3b736266-f621-11e7-8689-08c20f01d0da.png)
![image](https://user-images.githubusercontent.com/33913088/34782652-510fdeec-f621-11e7-9cbd-62753148385a.png)
![image](https://user-images.githubusercontent.com/33913088/34782691-63302f96-f621-11e7-8a42-10e5413f59a9.png)

**Comment by redv** [comment]
Could you attach the save?

**Comment by FilmBoy84** [comment]
@redv Here you go :) The Construction vehicle is just to the north of Base 2

[save_Medium Test 1.zip](https://github.com/OpenApoc/OpenApoc/files/1620875/save_Medium.Test.1.zip)

**Comment by redv** [comment]
It's a difficult case in the Megapols "Flayer Two" factory. Inside the factory the CoS's hoverbike 3 tries to get out on the road. But a police car vehicle crashed exactly in front of doors. The construction vehicle 34 tries to rescue the police car but cannot approach.

The hoverbike 3 tries to get out every 30 sec (in-game time). The time out is the same as for ground and for hover vehicles. I.e. for a single lift tube, battle vehicles can lift off every 30 sec to intercept UFOs. So, the time out is OK.

Possible to check: is the vehicle crashed, and if yes, then will be a good idea to increase time out to get out.

The police car should be self-destroyed after 12 hours. Thus the issue will be solved.

The same 12 hours time out is used to self-destruct UFOs. In the vanilla X-Com (as I tested) a crashed UFO disapears after 25 in-game mins. So, I think the time out of self-destruction should be decreased.

Could you test a vanilla behaviour of crashed UFOs?
Is it true that crashed UFO disappears after 25 mins?

**Comment by FilmBoy84** [comment]
Depending on the Class of UFO it appears from testing to take 3-12 hours of in-game time for a UFO to disappear. Larger UFOs (UFO 8 and UFO9) take the longest. Unmanned UFOs (UFO 1 and UFO2 disappear the fastest).

I will try and get some firm figures together for you tomorrow.

**Comment by redv** [comment]
Another test:
UFO1 disappeared after 15 mins.
First UFO2 disappeared after 15 mins.
Second UFO2 disappeared after 20 mins.

Looks like a random time out.

**Comment by FilmBoy84** [comment]
@redv 

Have tested myself and can confirm the same; the removal is random with minor influence according to UFO type (presumably to allow X-COM to get its act together after some of the more powerful UFOs start to damage the city in mid-late game causing deaths of agents in building collapses - this would make sense, loss of agents is very common on the harder maps).

UFO 1 appears to be 10 to 90 minutes (in game clock)
UFO 2 appears to be 10 to 90 minutes (in game clock)
UFO 3, 4 and 5 appear to be 15 to 120 minutes (in game clock)
UFO 6 appears to be 15 to 180 minutes (in game clock)
UFO 7 appears to be 10 to 120 minutes (in game clock)
UFO 8 appears to be 60 to 240 minutes (in game clock)
UFO 9 appears to be 60 to 240 minutes (in game clock)

I stand corrected on there being as many as 12 hours, the most appears to be 6 hours for Type 8 and Type 9 :)

**Comment by redv** [comment]
Is that values from the game data?
May be from the VehicleData structure: https://github.com/OpenApoc/OpenApoc/blob/master/tools/extractors/common/vehicle.h#L47
At least it contains unknown fields.

**Comment by FilmBoy84** [comment]
Values were from running a new savegame under vanilla (CD-ROM original release version) and logging each UFO crash last night, tried to get 20 crashes for each UFO type and record the times till they disappeared on 4x speed.

As to those unknown fields and their location in the inventory code for vehicles it is possible they are remnants of the "Flying Skill" and "Driving Skill" abilities of agents.

In early versions of the game you assigned pilots/drivers to vehicles; the current skill level of the vehicle was shown in the inventory/equip screen where those fields appear to be located glancing at that code.

You would assign agents to craft (appearing in green text) and the craft abilities were based on the agent flying/driving ability for that craft. This added another decision when recruiting agents. In vanilla vehicles simply perform to the best ability of the vehicle based on speed/armour/mobility/fuel/etc,

**Comment by FilmBoy84** [comment]
Closing Issue as #847 resolves this for roads
If we get any more examples with air or road, we can create a more up to date version of the issue and reference if needed
