### ISSUE TITLE
Problem with "Out of Fuel" Road Vehicle Recovery

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#341]
( Reported on the forums by @Creator )

> "When ground vehicle stays on the street for a long time then it gets out of fuel. When fuel has ended, an air crane comes and evacuates vehicle back to X-Com base. And then a message says that vehicle is "Unrepairable" and it disappears. It should be fixed."

**Comment by FilmBoy84** [comment]
This should probably be referenced in Issue #255 as well :)

**Comment by redv** [comment]
It's actually not a bug because it by design: https://github.com/OpenApoc/OpenApoc/blob/master/game/state/city/vehicle.cpp#L1457
But I don't know why :)

The FV_CHANCE_TO_RECOVER_VEHICLE is 66 %: https://github.com/OpenApoc/OpenApoc/blob/master/game/state/city/vehicle.h#L48

**Comment by FilmBoy84** [comment]
Can that design be extended to count vehicles disabled due to fuel loss as a 100% chance of recovery?

66% for other reasons is still fine as it's a relatively safe value to be "realistic" :)

**Comment by redv** [comment]
Sure.
I think it was a part of unfinished work.
I.e. possible to balance a vehicles park of the city.
Anyway i will do a pull request.

**Comment by FilmBoy84** [comment]
@redv resolved this issue
No longer replicatable
