### ISSUE TITLE
Ground vechicles destroyed because road collapses underneath

### ISSUE THREAD

**Issue by Solex87** [OpenApoc/OpenApoc#348]
Hi!

I haven't yet tried Open Apoc but I'm as hardcore Xcom veteran already thrilled. Keep up the good work!

The original game which I have played through many times was relatively in unpolished state in it's original release. Lots of clunkiness, half-finished features and couple of balance issues. Still the core gameplay was solid gold. On of the biggest issues in the original game is the mechanics of terrain destruction and it's effect on road vehicles. I would have loved to try setting ambushes with APC:s near the dimension gates but their impressive armor is useless because the UFOs can destroy them just by blowing up the road underneath them. 

I know nothing about how the game mechanics work or how difficult it would be to make on option for undestroyable road or fix this issue by any reasonable means cause otherwise you really cant't use ground vehicles or lot's of expensive gear which the game has.

If this has been already noted I apologize for being lazy and not figuring it out from forums or trying yet the game.

**Comment by FilmBoy84** [comment]
Welcome @Solex87 ; the issue with ground-vehicles being destroyed with the ground underneath has been fixed.

If you want armoured roads (+20 armour) see the More Options tab from the game menu and scroll to the mod before enabling it

If you want invulnerable roads we have an option for that too

Finally, some vehicles are now all-terrain and this too can be activated according to user preference

Options with an (M) are Mods
Options with an (N) are not yet implemented

Welcome to OpenApoc

**Comment by makus82** [comment]
we need speek wich Jonny if there option here in github  group 
that he give us and some1 else rights to test issues and if its solved we can close it

**Comment by FilmBoy84** [comment]
Issue is already resolved to work as per original game
There are armoured roads and invulnerable road options added also
