### ISSUE TITLE
Some new agents can't arrive to base

### ISSUE THREAD

**Issue by SiemensSchuckert** [OpenApoc/OpenApoc#350]
If a newly hired agent will receive order to "Go to building" or "Return to base" during travel in taxi - that agent will never leave taxi.

**Comment by makus82** [comment]
upload save or changelog?

**Comment by SiemensSchuckert** [comment]
(version OpenApoc-x64-v0.1-173-g0c9bbd01)

Two recently hired agents in Airtaxi 1
Peter Williams - just ordered to go to nearest Temple of the Apocalypse
Alice Smith - no orders

taxi lands at base, and then only Alice Smith arrives to base

[save_agent_stuck_in_taxi.zip](https://github.com/OpenApoc/OpenApoc/files/1673060/save_agent_stuck_in_taxi.zip)

**Comment by FilmBoy84** [comment]
It's even stranger than first appears...
Peter Smith arrives
Alice Smith arrives

![image](https://user-images.githubusercontent.com/33913088/37244705-e9c83788-2484-11e8-887b-b72c065505e8.png)

Peter Williams is then taken from the X-COM base to some apartments by the same taxi that supplied the other two agents...

![image](https://user-images.githubusercontent.com/33913088/37244717-10540ff8-2485-11e8-9e66-22d2f3b93cad.png)

**Comment by FilmBoy84** [comment]
Have not seen this on any new game for months
Replicatable ONLY with the savegame above
Can assume it's fixed in master branch
Closing
