### ISSUE TITLE
No aequipement type matching ID "VEQUIPMENTTYPE_BOLTER_4000_LASER_GUN"

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#353]
After selling off my lasers and going to equip agent after an Alien alert, the game CTDs with the following messages and log

Please also note a number of typo-errors!
"aequipement" should be "equipment"

![image](https://user-images.githubusercontent.com/33913088/37101823-5d0fdd18-221e-11e8-91f3-6b3a724c444a.png)
![image](https://user-images.githubusercontent.com/33913088/37101834-618bb2b8-221e-11e8-8217-ccdec82db21b.png)
![image](https://user-images.githubusercontent.com/33913088/37101838-679ba74e-221e-11e8-9c92-4ecf3f6b359c.png)

Clicking Limp-Along responds with the following error
![image](https://user-images.githubusercontent.com/33913088/37102084-edd236c0-221e-11e8-84cd-5515ac1f20b6.png)
![image](https://user-images.githubusercontent.com/33913088/37102090-f27f0c20-221e-11e8-96c2-4ae935a303e9.png)

Clicking Limp-Along again responds with a further error
![image](https://user-images.githubusercontent.com/33913088/37102107-05c297f2-221f-11e8-9515-05784c19c11e.png)
![image](https://user-images.githubusercontent.com/33913088/37102114-0ae9dc4a-221f-11e8-8902-9f7007df2b63.png)

**Comment by AndreyCreator** [comment]
Those "typo-errors" are not errors. Aequipment should stay as is because there is class "AEquipmentType" in the code and this message is related to it.

And it seems that the game tried to arm an agent with Bolter 4000 laser gun, but did not find proper data for this weapon.

**Comment by FilmBoy84** [comment]
@AndreyCreator Many thanks for looking into this.

I believe there is still a typo there "aequipement" should be "aequipment".
I also believe that the term "aequipment" refers to "Agent Equipment"
The Bolter 4000 Laser gun is NOT agent equipment, so should not appear in the agent equip code.
https://www.ufopaedia.org/index.php/Bolter_4000_Laser_Gun_(Apocalypse)

Additionally, there is no Bolter 4000 at the base, the two provided on game start were sold off immediately to generate money; so it is unclear as to why the game is calling for this item when accessing the agent equipment screen for the following reasons:

1) Neither weapon exists in X-COM inventory
2) The weapon is not Agent Equipment
3) Because of the above, the weapon should not be checked for on accessing agent inventory

**Comment by Jarskih** [comment]
@FilmBoy84 and @JonnyH this should be fixed.

**Comment by FilmBoy84** [comment]
Testing on OpenApoc-x64-v0.1-251-g8cd7a0db confirms this as fixed
Great work Jarskih <3 and JonnyH for merging so quickly
Closing it now
