### ISSUE TITLE
no aequipement type matching ID "VEHICLE_794"

### ISSUE THREAD

**Issue by cookins** [OpenApoc/OpenApoc#358]
Got new game and first alert about alien location - pressed button with soldiers equipment and got this.
![apoc3](https://user-images.githubusercontent.com/7893051/37254692-f8e20f62-2549-11e8-8af4-572b9c4c868e.png)

**Comment by FilmBoy84** [comment]
Ah yes, this occurs if you sold a vehicle from your base
It's a clone of issue #260 
https://github.com/OpenApoc/OpenApoc/issues/260

**Comment by cookins** [comment]
ok yeah.
now i have another one.
i bought phoenix and sold it back later, with buying some additional items.
![apoc4](https://user-images.githubusercontent.com/7893051/37255075-cf699fbe-254f-11e8-8ee9-e31a7691ed64.png)
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1800486/openapoc_log.txt)

**Comment by Jarskih** [comment]
@FilmBoy84 and @JonnyH this should be fixed.

**Comment by FilmBoy84** [comment]
Testing on OpenApoc-x64-v0.1-251-g8cd7a0db confirms this as fixed
Great work Jarskih <3 and JonnyH for merging so quickly
Closing it now
