### ISSUE TITLE
'Large' UFOs clip through buildings on their bottom/right sides

### ISSUE THREAD

**Issue by JonnyH** [OpenApoc/OpenApoc#36]
All vehicles are only considered 1x1, but large UFOs should be bigger (2x2? Not sure if they're centered on a tile, or their top left)

**Comment by ShadowDancer** [comment]
If there support for 2x2 vehiviles in pathfinder?

**Comment by JonnyH** [comment]
Not right now,

I guess one possible solution is to have a VehicleCanEnterTileHelper that checks a 2x2 block around the source/dest and it should still work?

Not sure how to 'block' impossible targets/source locations though. Probably not a big deal if the only large units are the big UFOs, as they always stayed high and couldn't 'land' anyway

**Comment by idshibanov** [comment]
Large UFOs are 2x2x2. I was planning to extend canEnterTile() to support them, but there's so much in TODO that I left it out for now.

However ground (crash) landing is already implemented and it should check for bigger vehicles when selecting a spot to land on.

**Comment by ShadowDancer** [comment]
Maybe just precompute spacing for vehicile and support any kind (even cubic)?

**Comment by Istrebitel** [comment]
There is no reason to make situation more difficult that it is for large ufos. It's not battle where units have to occupy tiles exactly. For now they are implemented like small ones but with bigger icon and collision models. 

I doubt anyone will ever notice the difference. Yeah, landing a large UFO into building will look stupid but that's not possible. Nothing else would really show they're implemented differently. So I suppose that's fine for now
