### ISSUE TITLE
Dimension Probe crashes when attempting to enter Dimension Gate

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#363]
The dimension probe does not appear to be able to go through dimension gates; instead it just crashes to the ground.

![image](https://user-images.githubusercontent.com/33913088/38027140-aaaf73f8-3286-11e8-9483-48159106e3be.png)
![image](https://user-images.githubusercontent.com/33913088/38027164-bbf5ebe2-3286-11e8-9c7a-ccbf475812e8.png)

**Comment by Quickmind01** [comment]
I can confirm this on stream. I tried entering all 3 gates and the probe just crashed with (approximately) 8 constitution left.

**Comment by FilmBoy84** [comment]
_vehicle_types.xml_ does have the probe able to enter dimension gates

@Quickmind01 do the other X-COM trans-dimensional craft also crash?

These are also specified as <canEnterDimensionGate>true</canEnterDimensionGate>

**Comment by Quickmind01** [comment]
I will review after work, but if I recall correctly, the others can make it
through.

**Comment by Quickmind01** [comment]
I just verified that all dimension craft but the Dimension Probe can make it through the gate.

**Comment by FilmBoy84** [comment]
This bug has stopped the OpenApoc being complete-able without all-research cheat

Because the probe crashes, the game never allows research of the first alien building

This needs fixing as a top priority

We can no longer claim OpenApoc is able to go start to end, pending bug navigation, without it sorted

**Comment by emptyVoid** [comment]
Please close -- #834 fixes the issue.

**Comment by makus82** [comment]
done
