### ISSUE TITLE
Restarting Self Destruct CTD (Vehicle Issue?)

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#364]
![image](https://user-images.githubusercontent.com/33913088/38027464-a7d27486-3287-11e8-8038-4b3a6e63dd8a.png)
![image](https://user-images.githubusercontent.com/33913088/38027473-ad2a2f64-3287-11e8-896d-93caec04faa5.png)
![image](https://user-images.githubusercontent.com/33913088/38027479-b3e72654-3287-11e8-9ce4-5423b5e5b8dc.png)

**Comment by FilmBoy84** [comment]
Seems to be created on spawn of a insta-crashed construction vehicle at Warehouse 6... Nothing appears to cause crash, mission is just spawned and vehicle appears in landing tube already down...

![image](https://user-images.githubusercontent.com/33913088/38028051-9986fe86-3289-11e8-9881-dd0dc61559bc.png)
![image](https://user-images.githubusercontent.com/33913088/38028067-a5864ade-3289-11e8-9a91-510642ed7456.png)
![image](https://user-images.githubusercontent.com/33913088/38028081-af140dde-3289-11e8-9c0e-daf140e43db5.png)
![image](https://user-images.githubusercontent.com/33913088/38028101-ba3b77ba-3289-11e8-9849-0bd8159f000d.png)
![image](https://user-images.githubusercontent.com/33913088/38028109-c344c032-3289-11e8-8d1f-47d057972a94.png)

**Comment by FilmBoy84** [comment]
The plot thickens, there is another construction vehicle in the tube (not crashed) before the new one spawns and crashes... The uncrashed vehicle is static and simply stays in the tube. Anything spawning from that point on crashes the uncrashed vehicle and itself ultimately leading to a CTD...

![image](https://user-images.githubusercontent.com/33913088/38028790-dc5fee46-328b-11e8-9b0d-c8f762f72579.png)
![image](https://user-images.githubusercontent.com/33913088/38028812-f069c3da-328b-11e8-91b3-4d776c0a2595.png)
![image](https://user-images.githubusercontent.com/33913088/38028826-fdc7fe52-328b-11e8-8aab-99a33d68ba8f.png)

**Comment by FilmBoy84** [comment]
Savegames
[saves.zip](https://github.com/OpenApoc/OpenApoc/files/1855948/saves.zip)

**Comment by Quickmind01** [comment]
I have just ran into this issue as well. I have the game running at full speed when it suddenly shows this error. The save has to run for a few in-game hours before it occurs.

[save_Stream Test.zip](https://github.com/OpenApoc/OpenApoc/files/3413733/save_Stream.Test.zip)
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/3413734/openapoc_log.txt)
![Restart Self Destruct](https://user-images.githubusercontent.com/51022165/61580300-0085c200-aad6-11e9-8c80-52e716e9cd49.png)

**Comment by Quickmind01** [comment]
I will update more when I can, but I learned that there was a vehicle in a vehicle tub attempting to recover another vehicle. I had to debug and destroy terrain for them to escape, and that prevented the crash. I don't know how the vehicles got that way to begin with. I will work on getting a highlight made of my stream to show the testing I did.

**Comment by Quickmind01** [comment]
Here is a (long) highlight of working on this bug. Unfortunately, I don't know what caused the vehicle to crash. https://www.twitch.tv/videos/456126555

**Comment by FilmBoy84** [comment]
Appears to be fixed by #838 
Closing

**Comment by gyunaev** [comment]
It is not fixed. Here is the save on latest Git which has the Construction Vehicle 23 at {95.5,75.5,1.99379} stuck in port in a strange state. Pressing X in debug mode doesn't remove it (but Ctrl-Alt-Shift+right click does). The vehicle also clogs the port, preventing any craft from leaving (but not from entering).

[save_progress-3.zip](https://github.com/OpenApoc/OpenApoc/files/7272918/save_progress-3.zip)
