### ISSUE TITLE
Attack Orders "stuck" when UFO returns to Alien Dimension

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#365]
Vehicles Ordered to Attack a UFO that then returns to the alien dimension have "stuck" orders on Map
![image](https://user-images.githubusercontent.com/33913088/38035245-e5b3dec0-329b-11e8-9946-5c4727914b15.png)

**Comment by FilmBoy84** [comment]
This also forces vehicles to attack "nothing" in the cityscape...
![image](https://user-images.githubusercontent.com/33913088/38104872-7088c128-3382-11e8-8596-868828195971.png)

**Comment by FilmBoy84** [comment]
Can no longer replicate this in the savegame i have for it
Closing

**Comment by emptyVoid** [comment]
The issue was still around just a month ago.

**Comment by FilmBoy84** [comment]
Thanks for heads-up @emptyVoid have you got a save with it happening still?
I tried to replicate but failed
Will re-open

**Comment by emptyVoid** [comment]
No, didn't thought of that since the issue is easy to reproduce.
The funny thing about it is that the attacking craft keeps shooting at the empty spot after ufo warps to alien dimension.

**Comment by FilmBoy84** [comment]
Ah, managed to replicate
Sent one craft against a UFO on the other side of the city
Because UFO was able to complete mission BEFORE first shots fired, it left, and the X-COM craft continued to the point at which it began to fire indefinitely
Agreed, easy to replicate
Thanks emptyVoid

**Comment by FilmBoy84** [comment]
As reported by Makus, a variation on this bug still exists leaving X-COM craft to potentially target buildings when the UFO leaves.

See issue #942

**Comment by FilmBoy84** [comment]
Resolved in #1506
