### ISSUE TITLE
VEHICLE (VAmmoType) Errors throughout log when on AGENT equipment

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#367]
For some reason, we're getting Vehicle Ammo Type errors when accessing the Agent equip screens...

![image](https://user-images.githubusercontent.com/33913088/38549022-1de7772a-3cab-11e8-9e7e-a8c8b1b08c0d.png)

**Comment by Jarskih** [comment]
This should be fixed now.

**Comment by Jarskih** [comment]
@FilmBoy84 and @JonnyH this should be fixed.

**Comment by FilmBoy84** [comment]
Testing on OpenApoc-x64-v0.1-251-g8cd7a0db confirms this as fixed
Great work Jarskih <3 and JonnyH for merging so quickly
Closing it now
