### ISSUE TITLE
Transferring Agents with a Full Alien Containment refuses the transfer

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#370]
For some reason if you are transferring agents from one base to another and either the sending or receiving base has a full alien containment, the transfer is refused even if living space is available

Agents DONT use Alien Containment to live in ;)

https://youtu.be/j3oZRBJoI94

**Comment by FilmBoy84** [comment]
The issue also appears to apply to store items and equipment transfers as well!

**Comment by FilmBoy84** [comment]
Problem persists as of 11th/10/2018
Alien containment not even full!

![image](https://user-images.githubusercontent.com/33913088/46806791-6b90b400-cd60-11e8-9007-4c73ff99b8f8.png)

**Comment by MurphyDavid** [comment]
From a quick look at the code....

When any transfer is done it checks *everything* even if it's not affected by the transfer.


`
if (vecChanged[i] || forceLimits)

			{

				crewOverLimit = b.second->getUsage(*state, FacilityType::Capacity::Quarters,
				                                   vecCrewDelta[i]) > 100;

				cargoOverLimit = b.second->getUsage(*state, FacilityType::Capacity::Stores,
				                                    vecCargoDelta[i]) > 100;

				alienOverLimit = b.second->getUsage(*state, FacilityType::Capacity::Aliens,
				                                    vecBioDelta[i]) > 100;

				if (crewOverLimit || cargoOverLimit || alienOverLimit)

				{

					bad_base = b.second->building->base;

					break;

				}

			}
`


So it could either check if the usage of each type has actually changed in the transfer screen or it could set flags for whether there's been any transfer of a particular type to the base to ignore over-full alien containment at the destination if no aliens are actually being transferred.

**Comment by FilmBoy84** [comment]
Logically, we only want to do checks for what is transferred with regards to space/money/effect on organisations/etc.

This should be updated every-time an item or item type is modified by the user

Not sure if that's easy to work your magic on though?

**Comment by FilmBoy84** [comment]
See also #505
