### ISSUE TITLE
Agent Armour Equip Box Offset

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#371]
For some reason, the armour equip box when dropping and dragging armour on to an agent is offset, this is most noticeable with Megapol Armour and the agents left arm (right of screen) to drag and drop armour on to the agent, the cursor must be placed to the right of the left arm...

Other hitboxes are also offset and need correction...

https://youtu.be/-pWI_hDzW7o

**Comment by FranciscoDA** [comment]
Care to try my branch?
Github: https://github.com/FranciscoDA/OpenApoc/tree/change-agent-layout
Appveyor: https://ci.appveyor.com/project/FranciscoDA/openapoc
I made the arms and the chest piece thinner (chest now has width=3, arms width=1), so the left hand armour should fit correctly

**Comment by J-casal** [comment]
Though its more of a quality of life thing and taking into account the game not having everything implemented, I would note that in the vanilla version one could drag a piece armor anywhere on the body and it would snap on to the right spot automatically. Just something I noticed as I've been playing between the two games a little.

**Comment by makus82** [comment]
fixed
