### ISSUE TITLE
Parked Road Vehicles run out of fuel and crash!

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#372]
For some reason, immobile (parked) vehicles such as Griffon Tanks will consume fuel when not moving and parked on the cityscape

When they run out of fuel they "crash" and must be recovered

Sometimes they are lost in the crash

This should not happen...

**Comment by FranciscoDA** [comment]
Can you confirm wether this bug is still present after merging #445?

**Comment by JohnSmith25** [comment]
I'm using 9d93056 and so far this bug does not appear, at least not for the APC which I did used this vehicle to park at some buildings, with some additional driving of the same APC I did not noticed a fuel usage though it didn't drive for very long either.  I haven't used the Griffon much but the brief period I did used it seems to work fine didn't tested the parking with that one though.

**Comment by FilmBoy84** [comment]
Can confirm that @FranciscoDA has fixed this issue
Closing accordingly
Thanks for the fix!
