### ISSUE TITLE
lot of bugs

### ISSUE THREAD

**Issue by derrikgort** [OpenApoc/OpenApoc#378]
I dont know how to attach save files so please tell me what I am to do.
1. at the 8th day after air battle any attempt to make a raid or to seek aliens crashes the game (on the last step when you are clicking the realtime button with the clock)
2. the medikit not working or I dont know how to. anyway.
3. last 2 ships staying at the base, you are clicking them at the enemy, and a line appears but they dont attack.
4. before the first bug a tactical battle was ok, but when after you send your ship with a squad it arrived but the screen with the notification didnt appeared. you were to send them into battle with a clicking at the building manually. (yes I had played the vanilla game).
5. on my first attempt to play (saves arent saved) after some time of gaming when a squad entered into the tactical battle they began to shoot civilians (not guards) from the first second though it was not a gang faction, it wasnt captured by aliens, wasnt hostile to, so there were no reason to shoot.
6. sometimes after the message of a detecting an enemy and you clickiing the centring button the map is trying to make a sort of "autocntering" and returning all the time there again.
7. an attempt to investigate the aliens reduces relations with a factions. I dont remember how it was in vanilla. anyway.
I forgot a pair of issues, I will get them lately, so it does after approximately 4 hours of playing...

**Comment by derrikgort** [comment]
8. ah, before issue 1. it began to crach during an air battle, when I clicked at one of ufos.

**Comment by derrikgort** [comment]
[saves.zip](https://github.com/OpenApoc/OpenApoc/files/2085584/saves.zip)
here are the saves

**Comment by JonnyH** [comment]
Hey - thanks for your interest, but for the most part reporting "bugs" isn't really that useful right now - openapoc is simply unfinished and we know there are gaping holes and missing functionality all over the place.

It's certainly not expected to be "playable" at this point.

**Comment by derrikgort** [comment]
cool

**Comment by Legacy55** [comment]
For #7, that's how it works in vanilla. If you investigate a faction's building and there is no alien presence there, you take a hit to relations.

**Comment by FilmBoy84** [comment]
Most of these issues are referenced elsewhere or no longer experienced
Closing
Thanks for the reports all <3
