### ISSUE TITLE
Unfinished features in Vanilla + more challenging game.

### ISSUE THREAD

**Issue by RAGUS30** [OpenApoc/OpenApoc#379]
Will you be working on the previously unfinished features from the original game? For example tracking bullet for special missions, better ending(in the odd black egg alien building) like in previous games where you had to find the source of evil even after completing research and destroying all. It would be nice that the game did not finish by destroying alien dimensional gate buildins and you had to invent own teleportation technology not dependent on aliens to find their last hidden outpost. And more psi devices and missions based on corrupted corporation city fractions relations would be good too. There is also not properly working personel psi-defense device in the game, lot of guns and something looking like advanced aircraft computers and even something that looks like matter-antimatter warhead. I appresiate your work.I hated that Hasbro lost the source code and there were no good option for modding the game by community. Hope you make it more challenging. Only thing I missed was 2-part missions from tftd(e.g. attaking alien base)﻿. Could you also implement that multi level missions from TFTD? ﻿

**Comment by JonnyH** [comment]
We've still got a long way to go "just" implementing the original's features - but we're certainly trying to do so in a way that allows further modification later and mods and stuff, and trying to fix things that are clearly "bugs" in the original at the same time.

So my goal is we won't extend the game much for the 1.0 release, but hopefully the modding hooks should allow interested people to add many things to the game, and leave the possibility open of more in-depth changes once the original's features are all implemented correctly.
