### ISSUE TITLE
Game crash within first day

### ISSUE THREAD

**Issue by Legacy55** [OpenApoc/OpenApoc#380]
I'm unable to play past the first day, playing hard with a fresh install and the game crashes at 23:10. I've tried the other difficulties but they crash within the first day too, usually close to midnight. It crashes regardless of what speed it's on. 

[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/2144367/openapoc_log.txt)

**Comment by killermosi** [comment]
Please take a look at #378.

**Comment by FilmBoy84** [comment]
This seems to have been tied to the equipment not being correctly cleared when sold bug that plagued us until recently
Ive been unable to recreate this error
I believe it is now fixed
Closing issue as there's no point in leaving open with no reports since June
