### ISSUE TITLE
Crediting Contributors

### ISSUE THREAD

**Issue by pmprog** [OpenApoc/OpenApoc#39]
We really need to make a list of contributors so we don't miss anyone.

Don't know if it needs to be in the game, in a text file, or just on the OpenApoc site; but we should have one

**Comment by JonnyH** [comment]
git log --format='%aN'|sort -u

**Comment by JonnyH** [comment]
5thAvenue
Jonathan Hamilton
kkmic
Marq Watkin
pmprog
SolariusScorch
Sonicelo
sparkstar
Xracer

Something to start with

**Comment by steveschnepp** [comment]
👍 as it forces everyone to have sane email commit addresses 😃

**Comment by makus82** [comment]
moved to Issue #941
