### ISSUE TITLE
"Failed to find base in XXX" Error

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#400]
When searching a building for alien activity, the following crash occurs (if aliens not found? - Unsure, craft dropped them in this building moments earlier)

![image](https://user-images.githubusercontent.com/33913088/46910404-2c6a8a80-cf3b-11e8-847b-b820af5f72a1.png)
![image](https://user-images.githubusercontent.com/33913088/46910405-312f3e80-cf3b-11e8-9efb-b882c7b34d75.png)
![image](https://user-images.githubusercontent.com/33913088/46910408-368c8900-cf3b-11e8-9ddc-e80956fc76b4.png)

**Comment by FilmBoy84** [comment]
Another instance
![image](https://user-images.githubusercontent.com/33913088/46916788-40ec6880-cfb7-11e8-8dd4-98e3579f691a.png)

**Comment by Jarskih** [comment]
Looks like same building in both cases?

**Comment by FilmBoy84** [comment]
It is, recyclotorium 2 on superhuman

Seems to happen on other cityscapes too though

**Comment by Jarskih** [comment]
That building has wrong owner (X-com) so it will try to generate base for it. Which organization is it supposed to belong to?

**Comment by FilmBoy84** [comment]
Seems to be a bug carried over from vanilla - X-COM is the owner for the Superhuman Map for some reason

**Owner should be Evonet However**

See article here:
https://www.ufopaedia.org/index.php/Recyclotorium_(Apocalypse)

**Comment by Jarskih** [comment]
That's interesting. If the owner is X-com mission type will be base defense which crashes the game.

**Comment by FilmBoy84** [comment]
:) Ah well, it's something that should hopefully be easy to fix

As the game no longer has a real-estate mechanism, there's no reason for anyone but **Evonet** to have ownership

**Comment by Jarskih** [comment]
Can you upload the save?

**Comment by FilmBoy84** [comment]
@Jarskih Sure, please find attached, wait for the hawk to land and then try to start the mission.
[save_SuperHuman 1.zip](https://github.com/OpenApoc/OpenApoc/files/2482226/save_SuperHuman.1.zip)
