### ISSUE TITLE
Chrysalis Autopsy Research Project shows Megaspawn Alien

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#402]
The chrysalis autopsy project uses the wrong artwork
![image](https://user-images.githubusercontent.com/33913088/46911131-c71e9580-cf4a-11e8-8844-0300ce3c1bad.png)

**Comment by makus82** [comment]
Also can add that next researches dont have pictures
in bio:

- The alien genetic structure
- The alien life cyrcle
- the real alien threat
- Biological warfare
- Toxin Type B
- Toxin Type C
- (there no Type A in list?)
- Alien Gas
- All alien buildings

in Phisics:

- Dimention gates 
- The Alien Dimentions
- Alien propulsion system
- Alien control system
- Alien energy source
- All Ufo types

**Comment by makus82** [comment]
i can look

**Comment by makus82** [comment]
hmm actually in original same probplem!

**Comment by makus82** [comment]
xcom3\ufodata\contico 
here bio images and there no needed ready to use images

**Comment by makus82** [comment]
i have idea can we make map of extracted gamefiles where and what rest

**Comment by makus82** [comment]
**i have idea can we make text map of extracted gamefiles where and what rest**
_coz openapoc not all files and pictures store in usual conditions
also this will be useful for mod creators i think_

for exmpl
xcom3\ufodata\agntico - agents and psicaptures icons
xcom3\ufodata\alien - alien dimention and buildings interior tiles
xcom3\ufodata\contico - aliens pics from alien containment
xcom3\ufodata\city - humans city and buildings tiles
...
