### ISSUE TITLE
Drag-Drop replacement of items in an inventory

### ISSUE THREAD

**Issue by DisDis** [OpenApoc/OpenApoc#416]
Current behavior:
1. Manually remove the item from the cell.
2. Place a new item in the cell.

Expected behavior:
1. A new item replaces an old one.

P.S.: I'm start game and I want completed all company. Wait for the issues ;)

**Comment by FilmBoy84** [comment]
Holding shift and clicking should auto-remove from cell
Holding shift and clicking on an item in storage should auto-equip to an optimal cell on the agent

Is this working for you @DisDis ?

**Comment by FranciscoDA** [comment]
I think this is a good suggestion. Dragging a new item over the old one to replace it is more intuitive than removing first, equipping second. Plus there's also the case where the item you're replacing is not in the optimal cell

**Comment by makus82** [comment]
So is it hard ti implement?)

**Comment by FilmBoy84** [comment]
This feature is not in the Original Game
It's therefore a Quality of Life feature
I also support this being done
Lablels updated accordingly

**Comment by makus82** [comment]
moved to Issue #941
