### ISSUE TITLE
Workshop: setting production count

### ISSUE THREAD

**Issue by DisDis** [OpenApoc/OpenApoc#417]
there is no possibility to increase or decrease the number of products
[link](http://i67.tinypic.com/20kase1.png)
[alt link](https://ibb.co/kHCDAf)

**Comment by makus82** [comment]
![image](https://user-images.githubusercontent.com/11581207/47286624-25f1a800-d5f8-11e8-8ca5-d5381ceff32e.png)

**Comment by makus82** [comment]
Ty for report @DisDis  and pls be more specific
also upload images here u can just copy image and select post form and paste and image will upload
![image](https://user-images.githubusercontent.com/11581207/47286812-e6778b80-d5f8-11e8-9e81-58cae9c899b5.png)

**Comment by FilmBoy84** [comment]
Production of items is set by sliding the bar or clicking the arrows
It's working as per vanilla in openapoc
The only exception is regarding some issues with cursor binding to the slider as reported already

![image](https://user-images.githubusercontent.com/33913088/47566724-73398680-d924-11e8-901f-12a15ba22ccd.png)

Closing issue as you can set production amounts
