### ISSUE TITLE
Attack on xcom base, immediate end and crash

### ISSUE THREAD

**Issue by DisDis** [OpenApoc/OpenApoc#418]
At the 0 move. That is, immediately after the start. The message "Opponent killed or unconscious" was displayed.
After that game is crash.

Log and save:
https://github.com/DisDis/OpenApocBugfiles/tree/master/1

**Comment by DisDis** [comment]
@FilmBoy84 it was aliens. medium diff level. i don't remember location. But it looks like #320 . The soldiers was not there either.

**Comment by FilmBoy84** [comment]
Merged as Issue #446 
Closing this iteration
