### ISSUE TITLE
[Feature request] Auto save after game crash

### ISSUE THREAD

**Issue by DisDis** [OpenApoc/OpenApoc#419]
I would like the game to save its state in case of any crash.
For the fight "autosave_battle", for the city "autosave_city"

**Comment by FranciscoDA** [comment]
This would be pointless most of the time. A corrupted game state will produce a corrupted save file :/

**Comment by FilmBoy84** [comment]
Agreed, the only way this could be implemented would be if a running auto save every XXX ticks of game time is made. Even then only the last successful save BEFORE the crash would be readable.

Other than a few specific cases of trying to recreate bugs, it's only going to slow the game, use CPU cycles, and increase disk read/writes

I propose that if such a thing was to be implemented it's done as a debug option and well hidden from the end user
