### ISSUE TITLE
[WIP] [New Feature] Adding a new OPTIONAL name pool for agent generation

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#427]
As discussed on discord, the option to add new names to the pool by which OpenApoc can generate agent names would be a nice little feature to implement

We could for example add name components from developers and supporters of the project as well as allow modders to add their own on a mod-by-mod basis

I'm going to look at how this could be implemented over the coming weeks; but would like input from any of your comments below:

* Any New Names must be OPTIONAL and be set by activating the appropriate flag under "More Options"
* To keep OG functionality, new names should be OFF by default
* Any names system must be modular to allow modders to add their own name files to the game
* Any system should be really simple and humanly readable in form. For example, a comma separated file with two columns of names (First, Last) should suffice. This allows for easy modification by users.
* Multiple names files, in a format as described above, should be recognised and read as one by the game (Selection of specific name files is something we can look at later)
* The only names added to any list and shipped with OpenApoc should be those of developers and supporters who give permission to do so. All other names must be added, separately, by mod developers at their own discretion. This means that the OpenApoc devs retain control of name submissions and decrease any liabilities that lack of moderation may present as only those approved in commits/pull-requests get added to master branch

**Comment by makus82** [comment]
Great idea J )
also i think about names those who donate money
and also other option to add they portraits or avatars as agent avatars
(that maybe canbe optionally off in settings)

**Comment by FilmBoy84** [comment]
This is already possible via mods through a different implementation to the above
There is argument for allowing masculine/feminine surnames also
But that's probably best dealt with in another issue
Closing
