### ISSUE TITLE
When mouseover on it its fully unequipe agent

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#430]
When mouseover on it its fully unequipe agent
this place where mouse cursor on screenshot and to left from cursor
![screenshot](https://user-images.githubusercontent.com/11581207/47577243-12737380-d94f-11e8-9bb2-f9ccedc09fac.png)

**Comment by FilmBoy84** [comment]
Can you please make a video of this bug makus?
It'd help to see where and how the cursor jumps

**Comment by FilmBoy84** [comment]
Cannot replicate this at all
No video of the problem
I can hover the mouse over the agent with no jumping or snapping to the location shown in OP
Closing
![image](https://user-images.githubusercontent.com/33913088/88903626-e71c6780-d24b-11ea-9f5a-7fc6862dd988.png)

**Comment by makus82** [comment]
cant reproduce... lol im only check it and u close it
