### ISSUE TITLE
[Bug / Enhancement / Feature Request] Unlock the Alien Life Cycle

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#434]
This is a difficult problem to correctly fix as it was partially broken in vanilla too

The aliens should drop an assortment of early life-cycle creatures into the city, such as brain-suckers (carried by anthropods with launchers), Alien Eggs, and Multiworms

**If left unchecked in the city,** 

1. Alien Eggs will become multiworms
2. Multiworms become hyperworms
3. Hyperworms become Chrysallis
4. Chrysallis become the other "higher" forms of alien life

This means that once a UFO drops it's payload of aliens, and if X-COM does not discover the cache of eggs attached to the group, the amount of high-end aliens encountered in missions after a few days should GO UP.

For example, a UFO drops 4 multiworm eggs, 2 Anthropods with 3 brainsucker pods EACH, 1 multiworm and 1 spitter.

If unchecked, a couple of days later the multiworm eggs should have turned into 4 more multiworms, the lone multiworm dropped by the UFO will have burst into 4 hyperworms, the ammunition of the anthropods should have produced some hostile building security or rogue brainsuckers, the spitter will be getting old

A day or so later again, the 4 multiworms have now produced 16 Hyperworms, the 4 existing hyperworms will have produced 4 chrysallis, the anthropods will still be taking out things with brainsuckers, the spitter will have most likely died

If unchecked, by the end of the week, we would be facing those 16 hyperworms and the 4 chrysallis having spawned TWENTY aliens between them, plus the remaining anthropods and spitter and captured security forces. All from a UFO drop of just 8 alien life forms.

Those 20 post-chrysallis aliens could be anything from poppers, to new alien species such as Skeletoids or even Megaspawn

In the OG game this does happen to an extent, but the effects of time on the aliens are somewhat muted to earlier beta versions of the game (where we can see larger numbers of aliens due to the higher multiplier values as well as the unlocked life-cycle)

### OpenApoc should probably look at restoring the growth and movement of aliens as per vanilla, but also consider unlocking the full alien life cycle behaviour from Beta where alien numbers can grow exponentially if left unchecked.

**Comment by idshibanov** [comment]
I think you can close this ticket. Alien life cycle is already implemented strictly following the OG logic.

As per "improving growth" we have to test the values before fully adjusting them. All variables are there, you should be able to change both growth rates and growth unit options in XML as a mod. Look up `extract_agent_types.cpp`.

**Comment by FilmBoy84** [comment]
It's currently left open as whilst the OG lifecycle is implemented

The unlocked, full cycle, as described above, from the Betas is not (which allowed for more variance in alien deployment on missions according to what was hatching in the city)

It would only ever be implemented as an option however

**Comment by FilmBoy84** [comment]
Have removed the bug label as the OG behaviour is currently working

**Comment by idshibanov** [comment]
> The unlocked, full cycle, as described above, from the Betas is not (which allowed for more variance in alien deployment on missions according to what was hatching in the city)

That's what I am saying - everything you describe is done and working already.
1. You would never see 20 aliens at the same time, but they will spawn precisely as you described. They die rather quickly and don't spawn at the same time, that why you feel "TWENTY" should be more impressive in-game.
2. You can add more variants to chrysalid hatching new units in XML mod, it's all configurable. Chance of spawn is there too (so Megaspawns can be 5% for example).
3. It's hard for me to imagine Brainsucker spawning any units (even in a mod), but they do increase alien infiltration very significantly when dying.

**Comment by makus82** [comment]
In OpenApoc we can separate this as per difficult levels 
beacose Julian i think limited life-cycle beacose difficults that can scare newbies

**Comment by FilmBoy84** [comment]
After speaking to ShellStorm on discord i'm closing this issue
The OG behaviour is now implemented in OpenApoc
Whilst it would be great to have the lifecycle implementations from early development
There are other features that need to be implemented to compliment it and keep it fun (like tracking of aliens)

I'll move discussion to the forums and close here (referencing this page)
