### ISSUE TITLE
Building on FreeBSD, data extractor fails

### ISSUE THREAD

**Issue by emc2** [OpenApoc/OpenApoc#437]
I'm trying to get this building on FreeBSD.  Managed to get through most of the build, but it fails when extracting data with the following error:

`/root/OpenApoc/bin/OpenApoc_DataExtractor --Framework.CD=/root/OpenApoc/data/cd.iso --Framework.Data=/root/OpenApoc/data --Extractor.extract=difficulty1
I 568680 bool OpenApoc::ConfigFileImpl::parseOptions(int, char **): portable mode set
W 49247397 static void *(anonymous namespace)::CueArchiver::cueOpenArchive(PHYSFS_Io *, const char *, int, int *): Opening "/root/OpenApoc/data/cd.iso"
E 33777601580 static void *(anonymous namespace)::CueArchiver::cueOpenArchive(PHYSFS_Io *, const char *, int, int *): Could not parse file "/root/OpenApoc/data/cd.iso"
  called by:
  0x6f309e _ZN5boost10filesystem16filesystem_errorD0Ev+0x2d06e (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x7c387b _ZN5boost10filesystem16filesystem_errorD0Ev+0xfd84b (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x10150d6 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertIPKcEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr38__libcpp_string_gets_noexcept_iteratorISA_EE5valueENS_11__wrap_iterIPcEEE4typeENSB_IS8_EESA_SA_+0xf4696 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x1014ef7 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertIPKcEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr38__libcpp_string_gets_noexcept_iteratorISA_EE5valueENS_11__wrap_iterIPcEEE4typeENSB_IS8_EESA_SA_+0xf44b7 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x100fb64 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertIPKcEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr38__libcpp_string_gets_noexcept_iteratorISA_EE5valueENS_11__wrap_iterIPcEEE4typeENSB_IS8_EESA_SA_+0xef124 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x100feb2 _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertIPKcEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr38__libcpp_string_gets_noexcept_iteratorISA_EE5valueENS_11__wrap_iterIPcEEE4typeENSB_IS8_EESA_SA_+0xef472 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x101022d _ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertIPKcEENS_9enable_ifIXaasr21__is_forward_iteratorIT_EE5valuesr38__libcpp_string_gets_noexcept_iteratorISA_EE5valueENS_11__wrap_iterIPcEEE4typeENSB_IS8_EESA_SA_+0xef7ed (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x6f6555 _ZN5boost10filesystem16filesystem_errorD0Ev+0x30525 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x6bc06f _ZNSt9exceptionC2ERKS_+0x6a7af (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x6a1020 _ZNSt9exceptionC2ERKS_+0x4f760 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x6a0f59 _ZNSt9exceptionC2ERKS_+0x4f699 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x67a313 _ZNSt9exceptionC2ERKS_+0x28a53 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x61a945 _ZTSNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE+0x3e6a75 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x3b2095 _ZTSNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE+0x17e1c5 (/root/OpenApoc/bin/OpenApoc_DataExtractor)
  0x80104e000 _ZTSNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE+0x800e1a130 (/root/OpenApoc/bin/OpenApoc_DataExtractor)`

**Comment by JonnyH** [comment]
Interesting - it seems to be failing to read the cd filesystem headers.

Does the file /root/OpenApoc/data/cd.iso contain a valid iso9660 filesystem? What's the md5sum of it? Does it mount correctly using a loopback mount?

Plus the obligatory condemnation of running as root :)

**Comment by emc2** [comment]
I have to run as root to get `make install` working.

It looks like my cd.iso might have been truncated somehow.

**Comment by emc2** [comment]
Ok, my ISO had been corrupted somehow.  I got through the build, but it's got some runtime issues.  I'll deal with those in a separate patch.
