### ISSUE TITLE
Bug on "Bay and sell"

### ISSUE THREAD

**Issue by aap4ixx** [OpenApoc/OpenApoc#440]
Привет, нашёл такой баг.
Пытаюсь продать вещи в окне "Buy and sell". При перемещение ползунка (Продать/купить) сумма не меняется, меняется только тогда когда я переключаюсь между закладками.

English:
I am trying to sell things in the "Buy and sell" window. When moving the slider (Sell / buy) the amount does not change, it changes only when I switch between the tabs.

**Comment by FranciscoDA** [comment]
This has been fixed in #457

**Comment by FilmBoy84** [comment]
Issue appears to be fixed by FranciscoDA's work
Many thanks
