### ISSUE TITLE
Game crashed when "Valkyrie" try to fly

### ISSUE THREAD

**Issue by aap4ixx** [OpenApoc/OpenApoc#441]
Привет.

После первого задание по зачистки здание он пришельцев, происходит вылет из игры.
Как всё происходит: Солдаты смерти последнего пришельца, появляется сообщение с поздравлением. OK -> OK и появляется карта мира (игра стоит на паузе, это важно). Как только я убираю паузу то игра сразу падает. Такое случается если я просто выйти из сражение, и при убирание паузы игра также вылетает.

Но если при появление карты города оставить игра на паузу и сохранить -> загрузить. То игра игра продолжает работать в штатном режиме.

Файлы:
1) Файл логов
2) Файл сохранение, там если
 не чего не делать то через 2 секунды солдаты убивают последнего монстра и победа, или просто выйти из сражение и при нажатие пуска игра падает.

[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/2611046/openapoc_log.txt)
[save_xxx-1.save.log](https://github.com/OpenApoc/OpenApoc/files/2611047/save_xxx-1.save.log)

**Comment by Atrosha** [comment]
I think we should close this issue. Flacko solved it with Beorn's help.

**Comment by makus82** [comment]
Добро пожаловать aap4ixx =] и спасибо за репорт и тестирование
