### ISSUE TITLE
Base Invasion (Alien or Org) at an X-COM Base with no agents causes CTD

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#446]
I'm merging issue #320 and issue #418 into this bug report as it's still current

If an organisation, or the aliens, invades an X-COM base that has no agents present, even if that base has security stations (and therefore can protect itself), the game will first state that no X-COM agents are alive or conscious, then crash as it attempts to end the mission as a lose for X-COM

To facilitate OG functionality the base should be "lost" without starting a mission. It's facilities destroyed and X-COM losing the building (though they can re-purchase later)

A better proposal for OpenApoc would be that if security stations are present, start a tactical mission. This allows the player the opportunity to see the invaders mown down by security station fire and maybe save the base.

If the player aborts the mission having not killed the invaders then the base is lost

If there are NO security stations, then the base is lost as normal for the OG

Original Report by @Darkestaxe1 Issue 320
_"to reproduce, make a new game on medium,
buy the $4800 slums base in the upper-right of the map, (I started building stores and living quarters)
pass time until aliens invade it on day 2"_

Original Report by @DisDis Issue 418
_"At the 0 move. That is, immediately after the start. The message "Opponent killed or unconscious" was displayed.
After that game is crash.
Log and save:
https://github.com/DisDis/OpenApocBugfiles/tree/master/1"_

**Comment by FilmBoy84** [comment]
Another iteration of this bug, a base attack has started with NO HOSTILES generated
The game reports that all hostile units are dead, unconscious or left and crashes
Save attached
[save_SuperHuman 1.zip](https://github.com/OpenApoc/OpenApoc/files/2723609/save_SuperHuman.1.zip)

**Comment by FilmBoy84** [comment]
From@BeornTB

`Sorry, no save or log.

RT base defense, 2 androids 2 defense towers vs no opponents. Instant victory, CTD.`

**Comment by BeornTB** [comment]
Working base defense save:
https://www.dropbox.com/s/qexunozphx3wtfz/save_336%20TB%20Base%20D.save?dl=0

**Comment by Jarskih** [comment]
I think this crash is caused by base defense turrets. They are trying to go back to base after battle. I am puzzled though why base defense starts without enemies?

**Comment by FilmBoy84** [comment]
This issue is no longer replicatable
It appears @FranciscoDA fixed it
Great job sir!
