### ISSUE TITLE
Make a new release for new year before it's too late

### ISSUE THREAD

**Issue by FranciscoDA** [OpenApoc/OpenApoc#451]
The last official release of OpenApoc was in October 2017. We've done a lot of work since then (see the list of commits: https://github.com/OpenApoc/OpenApoc/compare/v0.1...master) and the fans have been very patient. Here's my proposed message for the changelog (suggestions and edits are accepted, of course)

## UI:
 * Fixed track selected lab in each base
 * Fixed buttons in research screen
 * Fixed vehicles being bought twice in transaction screen
 * Fixed deleting labs
 * Fixed listbox rendering
 * Fixed ordering a vehicle to attack a building
 * Fixed a bug where different transaction controls could become desynchronized in the transaction screen
 * Fixed vehicle weapon range is now scaled correctly in the vehicle equipment screens
 * Fixed alien equipment now correctly displayed as "Alien Artifact" if unresearched
 * Fixed crash when selling vehicle equipment or ammo
 * Fixed agent/vehicle equipment screen would open from assignment screen when clicked. Now opens only with right click, like in vanilla Apocalypse
 * Fixed displayed value for fire rates
 * Changed agent assignment screen completely (now supports drag and drop and dragging multiple agents!)
 * Added hotkeys to Ufopaedia
 * Added bribe screen
 * Added score screen (for alien investigations and ufo incursions)
 * Added editable names for agents and crafts
 * Added messages for vehicle rearmed, refuelled, not enough ammo, not enough fuel

## General gameplay:
 * Fixed agent training and healing while assigned to a vehicle parked inside base
 * Fixed base defense-related crash triggered by alien movement
 * Fixed destroying facilities. Also refunds money when destroying unfinished facilities
 * Fixed initial equipment for vehicles to match vanilla Apocalypse
 * Fixed crashes related to vehicles being destroyed
 * Fixed living quarters
 * Fixed hirable agents could spawn from buildings with Xcom bases
 * Added agent healing
 * Added agent training
 * Added option to automatically seed the RNG on game start (enabled by default)
 * Added a cheat menu and several cheat options (disabled by default)

## Cityscape:
 * Fixed "live alien spotted" red circle
 * Fixed vehicle recovery missions
 * Fixed a bug preventing vehicles from other organizations to attack hostile vehicles
 * Fixed ground vehicles consuming fuel when idle
 * Fixed UFOs can now fire in 360° arc
 * Fixed vehicles are now clickable through buildings
 * Fixed spaceliners would still spawn with airport destroyed
 * Changed idle vehicles now turn automatically towards closest enemy
 * Improved pathfinding for road vehicles
 * Improved algorithm for collapsing buildings
 * Added option to make the Wolfhound APC all-terrain (disabled by default)
 * Added aliens coming out from portals and going back into them
 * Added alien UFO missions (destroy building, infiltrate, subvert, escort)
 * Added vehicles are now able to enter dimension gate
 * Added scenery repair

## Battlescape:
 * Fixed crash when entering battle with empty autocannon
 * Fixed turn-based UI wouldn't display TU cost to fire when hovering an enemy
 * Fixed range checks
 * Fixed calculation of TU cost to fire
 * Added option for automatic run-and-kneel at the start of battle (disabled by default)
 * Added auto recovery of live chrysallis and alien eggs
 * Added agent equipment adjusts to reflect their score
 * Added stun and multishot weapons

## Code:
 * Removed cotire from cmake builds (default to ccache instead)
 * Added support for C++14 and C++17
 * Updated dependencies (physfs, glm, boost)
 * Fixed a buffer overrun bug when playing sounds under some audio configurations

## Contributors for this release:
 * AndreyCreator
 * Filmboy84
 * FranciscoDA
 * Istrebitel
 * Jarskih
 * JonnyH
 * makus82
 * redv
 * Roger
 * SiemensSchuckert
 * Skin36
 * solbu
 * SupSuper

## Other milestones:
 * **+2500 commits!**
 * **+100 closed issues!**

**Comment by makus82** [comment]
Great work wich this proposed message @FranciscoDA 
...
