### ISSUE TITLE
Clicking on Cityscape Map causes CTD

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#460]
Please load attached game and click on the map
Game will CTD without writing to log!
[save_SuperHuman 1.zip](https://github.com/OpenApoc/OpenApoc/files/2723463/save_SuperHuman.1.zip)

**Comment by FilmBoy84** [comment]
Interesting fix to this
Load the save
Press F1 (for debug)
Press F4 (to show all aliens on map)
Click the map icon
Game won't crash

If you do anything with the map before following the above, it CTDs

**Comment by JonnyH** [comment]
Quickly ran this through a debugger:

It's crashing at citytileview.cpp:745

In the save, it seems that "VEHICLE_3864" has somehow ended up with an AttackVehicle mission with a null targetVehicle

**Comment by FilmBoy84** [comment]
@JonnyH Ah, many thanks, then it's also related to issue #456 
Those vehicles are stuck in the building on both save games
I just realised that they became stuck when the UFO they were attacking left the city and back to alien dimension or were among the UFOs destroyed before they left the building

It seems that there is a bug in dealing with how vehicles clear their orders when the target entity either leaves the dimension that it's in, or is destroyed

Will update #456 accordingly :)

**Comment by FranciscoDA** [comment]
I think this is a rendering issue. It seems it's possible for a vehicle to have a mission with a null target vehicle, but the mission is popped almost immediately.
In this case a bunch of vehicles are stuck in a takeoff mission (as in #456) so there's no way to pop the attack vehicle mission

**Comment by FilmBoy84** [comment]
Issue appears to be fixed by FranciscoDA's work
Many thanks
