### ISSUE TITLE
Vehicles target escaped UFO

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#475]
https://i.imgur.com/hY4GehE.gif

Vehicles target a bogus map point when their UFO enemy has fled through the gate. See the red crosshairs at the top of the screenshot, bit left of center.

[330-VehiclesTargetEscapedUFO.zip](https://github.com/OpenApoc/OpenApoc/files/2742138/330-VehiclesTargetEscapedUFO.zip)

**Comment by FilmBoy84** [comment]
This is also related to the earlier report issue #365 
Both need fixing

**Comment by BeornTB** [comment]
New sighting in 339
[339 Bogus Target UFO left.zip](https://github.com/OpenApoc/OpenApoc/files/2771268/339.Bogus.Target.UFO.left.zip)

**Comment by BeornTB** [comment]
Wait what no I shouldn't have the power to close an issue :O

**Comment by FilmBoy84** [comment]
As discussed, this is related to #365 
Closing as further discussion can be taken there
Thanks for report though BeornTB
