### ISSUE TITLE
CTD: Weekly review

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#501]
Upon ending day 7, when the weekly review and income should pop-up, CTD.
[343 Vehicles dont repair.zip](https://github.com/OpenApoc/OpenApoc/files/2793306/343.Vehicles.dont.repair.zip)

(same files as the last bug report, only save D7-2 is relevant here)

**Comment by FranciscoDA** [comment]
It seems this is because of a bug in the economy update algorithm. Should fix itself when we merge #491

**Comment by FilmBoy84** [comment]
Log from this crash
![image](https://user-images.githubusercontent.com/33913088/51744647-6863ce80-2098-11e9-8b11-e1f2805d25d7.png)

**Comment by BeornTB** [comment]
Repeat bug in 345:
[345 CTD Week review.zip](https://github.com/OpenApoc/OpenApoc/files/2797577/345.CTD.Week.review.zip)

**Comment by FilmBoy84** [comment]
Fixed in latest build
We are still awaiting a weekly review and payments to be implemented though

![image](https://user-images.githubusercontent.com/33913088/52001622-c852de80-24b7-11e9-9623-f56dea6f9ccf.png)
