### ISSUE TITLE
No scrolling menus for vehicles

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#515]
I can't scroll down to equip vehicles past the first top screen of the vehicle equipment menu. In cityscape, the slider doesn't allow to scroll left-right either, among the owned vehicles.

Soldier equipping did, however, scroll up/down properly.

Latest 375 build.
[375 No Scrolling Menus.zip](https://github.com/OpenApoc/OpenApoc/files/2865934/375.No.Scrolling.Menus.zip)

**Comment by FilmBoy84** [comment]
Confirmed bug on W10 x64 under a clean build (not appveyor) @FranciscoDA
