### ISSUE TITLE
[BUG] No transportation "hostile organisation" but TransStellar is neutral

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#520]
Only lifetree is hostile and none of the orders were passed through them. Transfers, Megapol armor, etc need to be manually gathered or transported by tubes.
[377 PublicTransportOnStrike.zip](https://github.com/OpenApoc/OpenApoc/files/2870352/377.PublicTransportOnStrike.zip)

**Comment by BeornTB** [comment]
Update: I tried buying out Lifetree and TransStellar, nothing changed. Transportation is incorrectly still blocked.

**Comment by FranciscoDA** [comment]
Transtellar has -76.5 relationship with megapol in your save. OpenApoc requires that the ferry organization is not hostile towards the supplier nor the buyer.

**Comment by FilmBoy84** [comment]
Closing issue as things are basically working as intended
Why would two hostile orgs work together to fulfill an order for a third party (X-COM)?

**Comment by BeornTB** [comment]
Gotcha. Seems odd that they would go off on such wrong footing within 3 days.
