### ISSUE TITLE
unexplained seizure of corporations by aliens

### ISSUE THREAD

**Issue by DemoNicanT** [OpenApoc/OpenApoc#524]
Here is my problem. I successfully repel alien attacks in buildings. Shoot down their ships. The aliens do not even dare to leave the portal, but organizations still fall under the control of the aliens. And in the end, on the 9th day, half the organizations are already against me. What am I doing wrong. Help me figure it out. And maybe this is a bug? Because in the original game this did not happen.

**Comment by FranciscoDA** [comment]
These are some of the less obvious mechanics you might have missed:
 * Not all buildings infested with aliens raise alarms. You can fight every alien spotting but they may be spreading anyways
 * If a ship crashlands and selfdestructs before you pick it up, then the surviving aliens will occupy nearby buildings
 * Escaped/surviving aliens flee towards nearby buildings after a battle

**Comment by makus82** [comment]
Demo nice bugreport 
also pls add separate report about ur 2x monitor and navigation problem

**Comment by makus82** [comment]
Also Demo for your problem u can use debug system by hotkeys here look pls
https://github.com/OpenApoc/OpenApoc/blob/master/README_HOTKEYS.txt
you can track aliens by F1 and then F4 at City map

**Comment by FilmBoy84** [comment]
@FranciscoDA I did not think aliens spreading between buildings or the full alien life cycle had been implemented into OpenApoc yet?

The OG had them spreading, and a limited alien life cycle, but the full unlocked life cycle has not existed since Beta1 and Beta2 of the OG

Has this changed? Does OpenApoc now include the full cycle, if so can you point me towards the PRs? Im interested in looking at the code

**Comment by FranciscoDA** [comment]
@FilmBoy84 
Here is alien growth code: https://github.com/OpenApoc/OpenApoc/blob/master/game/state/city/building.cpp#L788
And here is alien movement: https://github.com/OpenApoc/OpenApoc/blob/master/game/state/city/building.cpp#L841

However, I don't know if they are faithful to the mechanics in the original Apocalypse

**Comment by FilmBoy84** [comment]
Brilliant thanks Flacko
Just scanning over it appears to reveal it's rather different to OG
And a long way from being the full alien life cycle (Beta1)

Ill have a detailed look over coming weeks

**Comment by FilmBoy84** [comment]
Im going to close this issue as the implementation of some movement and growth mechanisms, albeit different from OG are already included in OpenApoc

Additionally, Makus' roadmap to 1,0 already lists full OG functionality as to be done
Ive already spoken elsewhere about implementing full-alien life cycle too

As this issue is effectively duplicating stuff elsewhere on the tracker, im closing for now

**Comment by makus82** [comment]
Pls lets be open lets Demo make some tests

**Comment by DemoNicanT** [comment]
I thank everyone for the advice, but I still don’t understand much, for example, I can’t find an effective way to search for newcomers by organization, just fly around ALL buildings, indecency, I understand that you have shoveled most of the game mechanics, but now I’m perfect I do not understand how to effectively track adversaries, oh yeah, the alien tracking diagram does not work, but I think about it and you already know.

**Comment by DemoNicanT** [comment]
![default](https://user-images.githubusercontent.com/48145651/53688822-fe0b1180-3d5a-11e9-9160-2941589e2c84.jpg)

As I expected, I cleared out all the buildings of the Megapol and checked the nearby buildings, but still the Megapol was captured, which is a kind of curse

**Comment by FranciscoDA** [comment]
Please, attach saves before and after aliens take over megapol

**Comment by makus82** [comment]
U use this ? 
https://github.com/OpenApoc/OpenApoc/issues/524#issuecomment-468941827

**Comment by FranciscoDA** [comment]
I've been looking at the code and I found this: https://github.com/OpenApoc/OpenApoc/blob/master/game/state/gamestate.cpp#L1104
It seems that once an organization becomes infiltrated, there's always a chance it may get taken over, even if you cleanse their buildings of aliens

**Comment by makus82** [comment]
hope its not like 50%?)

**Comment by DemoNicanT** [comment]
> Please, attach saves before and after aliens take over megapol

i cannot send save file here, hmmmm.............

**Comment by DemoNicanT** [comment]
> Please, attach saves before and after aliens take over megapol

https://yadi.sk/d/HZypJuBK8aU55Q Here the save before  taking over Osiron ( sorry they dont need Megapol for know)))
https://yadi.sk/d/4FqzHc_wGZCjwA And after.

**Comment by makus82** [comment]
just RMB and send to zip and then attach)

**Comment by DemoNicanT** [comment]
> hope its not like 50%?) looks like temporary action before cycle will finish

Osiron was 21% and Megapol was 4%

**Comment by DemoNicanT** [comment]
> Please, attach saves before and after aliens take over megapol


[before and after taking Osiron.zip](https://github.com/OpenApoc/OpenApoc/files/2923876/before.and.after.taking.Osiron.zip)

**Comment by FranciscoDA** [comment]
Yeah, I don't see anything wrong. Osiron gets taken over in ~20 minutes.

Each organization is rolled every 125 minutes. The chances of getting taken over grow with the `infiltrationValue` of the organization (every 2 points of infiltration increases the chance by 1%).

Currently infiltration only grows as aliens "grow": most aliens infiltrate by 1 or 2 when they grow inside a building (for example: anthropods infiltrate 2, brainsuckers 1, etc.). Also, the infiltration is affected multiplicatively by the function of the building they grow in and the `infiltrationSpeed` of the organization (for example: slums and criminal gangs are more likely to be infiltrated)

I don't think there's anything wrong with OpenApoc. That is, unless someone can prove that the aforementioned multipliers are wrong and provide with the correct ones.

I recommend you use the Cityscape debugging tools like Makus mentioned so you can clean your city of aliens before they get a chance to grow. Here are the aliens in the "6756756" savegame you attached:
![](https://i.imgur.com/mwhiIOT.png)

**Comment by DemoNicanT** [comment]
> Yeah, I don't see anything wrong. Osiron gets taken over in ~20 minutes.
> 
> Each organization is rolled every 125 minutes. The chances of getting taken over grow with the `infiltrationValue` of the organization (every 2 points of infiltration increases the chance by 1%).
> 
> Currently infiltration only grows as aliens "grow": most aliens infiltrate by 1, 2 or 3 when they grow inside a building (for example: anthropods infiltrate 2, brainsuckers 1, psimorph 3 etc.): this is their `infiltrationSpeed`. Also, this is affected multiplicatively by the function of the building they grow in and the `infiltrationSpeed` of the organization (for example: slums and criminal gangs are more likely to be infiltrated)
> 
> I don't think there's anything wrong with OpenApoc. That is, unless someone can prove that the aforementioned multipliers are wrong and provide with the correct ones, but that's unlikely since these values are extracted from the vanilla Apocalypse data.
> 
> I recommend you use the Cityscape debugging tools like Makus mentioned so you can clean your city of aliens before they get a chance to grow. Here are the aliens in the "6756756" savegame you attached:
> ![](https://camo.githubusercontent.com/7da7086e64d9a09ebd21a9015fc83c228fbe2a4e/68747470733a2f2f692e696d6775722e636f6d2f6d776869494f542e706e67)
> Have fun :P

воистину права поговорка век живи век учись, кажется я начинаю понимать обновленную механику этой игры.

**Comment by makus82** [comment]
yep use F1 and then F4 on map of the city

**Comment by makus82** [comment]
so urs 2x monitor navigation problem no longer uppears?

**Comment by FranciscoDA** [comment]
I guess the problem has been addressed and we can close this now

**Comment by DemoNicanT** [comment]
> I guess the problem has been addressed and we can close this now
Yes, problem solved
