### ISSUE TITLE
Crash while manage scientists, soldiers, engineers

### ISSUE THREAD

**Issue by Dago73** [OpenApoc/OpenApoc#532]
The following mistakes occur again and again and lead to crashes regularly.
1. Scientists are "caught" in the large laboratories. If I remove all scientists from a laboratory, there will always be residuals left over. If I then add 10 scientists / technicians, the 10 limit is exceeded and it comes to crash.
2. The transfer of scientists / soldiers / technicians between the bases will cause crashes when I try to transfer those two to the bases.
3. If the error of item 1 is present, the program crashes if I want to dismantle the lab / workshop.
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/2972648/openapoc_log.txt)

**Comment by makus82** [comment]
Welcome and ty Dago73! very detailed report

**Comment by Dago73** [comment]
Shall i send the last savegame? Than you can see the Problem

**Comment by Atrosha** [comment]
You may give the stack trace of crashes.

**Comment by Dago73** [comment]
I am sorry. My english is not as good as it should be. What do you mean whith stack trace?

**Comment by FranciscoDA** [comment]
It seems this is the same as #505
Can you close this and add a link (as a comment) in #505 to this issue?

**Comment by Atrosha** [comment]
Upload the saves if you can't manage to use debugger. I'll do it.

**Comment by Dago73** [comment]
I often get this error:
"No agent matching ID "AGENT_44"
Than the game crashes, because the "limp along" wont function

**Comment by Dago73** [comment]
[saves.zip](https://github.com/OpenApoc/OpenApoc/files/2972669/saves.zip)

Here the last 3 Saves

**Comment by Dago73** [comment]
Problem starts at Base 2 - Biochemie Lab

**Comment by Dago73** [comment]
It seems this is the same as #505

**Comment by FilmBoy84** [comment]
Please see #505 Im referring to this Issue there and closing it here
Many thanks for the report Dago <3
