### ISSUE TITLE
Scroll buttons in main menu invisible till u press on it

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#538]
Scroll buttons in main menu invisible till u press on it
![image](https://user-images.githubusercontent.com/11581207/54753098-dfc16480-4be8-11e9-91c1-9a1d345e0647.png)

**Comment by makus82** [comment]
...but maybe its needed that way)

**Comment by FranciscoDA** [comment]
This will require some image editing since we don't have graphics for buttons in "normal" state (ie: not pressed)

**Comment by makus82** [comment]
i can edit image
