### ISSUE TITLE
[MISSING AT TRANSIFEX] List of strings that missing at transifex

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#547]
_And suggested translation to russian_

**Whole, almost, debriefing screen**
- [x] DEBRIEFING > БОЕВОЙ ОТЧЁТ
- [x] БРИФИНГ ЗАДАНИЯ (MISSION BRIEFING) > БОЕВОЙ ИНСТРУКТАЖ 
- [x] ITEM ПОКАЗАТЕЛИ
- [x] Combat rating Боевой рейтинг
- [x] Unit Brainsucked Объект отмозгососен
- [x] Casualty penalty Штраф за потери
- [x] Leadership bonus Премия за лидерство
- [x] Live Aliens captured Пленных инопланетян
- [x] Equipment captured Захвачено амуниции
- [x] Equipment lost Потери амуниции
- [x] Mission performance Результат миссии
- [x] РЕЗУЛЬТАТИВНОСТЬ > РЕЗУЛЬТАТЫ (coz its used in others screen)

![image](https://user-images.githubusercontent.com/11581207/54832407-c392f580-4cc4-11e9-85c2-5b59af6f4f23.png)

**main menu**
- [x] Exit Battle  > Выйти из боя
- [x] OpenApoc Features > Особенности OpenApoc
- [x] More options  > Больше настроек
- [x] Give all research  > Дать все исследования
- [x] Skirmish Mode  > Режим перестрелки
- [x] Agent arrived at base  > Агент прибыл на базу
- [x] Transfer arrived at base  > Прибыл груз с другой базы
- [x] Crash recovery arrived at base  > Потерпевший крушение эвакуирован на базу

![image](https://user-images.githubusercontent.com/11581207/54752653-99b7d100-4be7-11e9-9c79-6d08c06e3708.png)

**Comment by Atrosha** [comment]
Imho лучше не "посылки прибыли на базу", а "груз прибыл на базу"

**Comment by makus82** [comment]
Уже есть такой посмотри на скрине) 
груз это то что ты заказал и тебе притарабанили вроде 
а трансфер это твое барахло с другой базы

**Comment by makus82** [comment]
> Imho лучше не "посылки прибыли на базу", а "груз прибыл на базу"

Уже есть такой посмотри на скрине)
груз это то что ты заказал и тебе притарабанили вроде
а трансфер это твое барахло с другой базы

**Comment by Atrosha** [comment]
Прибыл груз с другой базы.

**Comment by Skin36** [comment]
close ?

**Comment by makus82** [comment]
![image](https://user-images.githubusercontent.com/11581207/54872239-c6c3d980-4dc9-11e9-80a1-e7b920293fcc.png)

![image](https://user-images.githubusercontent.com/11581207/54872280-2e7a2480-4dca-11e9-82ac-98576ff42ac6.png)
