### ISSUE TITLE
CONCEPT Suggestion just for stats look little better

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#551]
I moved the separation between titles and indicators to the center of the info block and this gave more room for possible problems with long words in translations. Added 2 pixels to the distance between stat names and indicators

![statssuggest](https://user-images.githubusercontent.com/11581207/54968281-bd31a180-4f82-11e9-8959-4428088357a7.png)

![statssuggest3](https://user-images.githubusercontent.com/11581207/54968505-a0e23480-4f83-11e9-875b-b3561263200f.png)

![statssuggest4](https://user-images.githubusercontent.com/11581207/54969145-cd974b80-4f85-11e9-8282-d74d07b508d0.png)

![statssuggest2](https://user-images.githubusercontent.com/11581207/54968064-fe758180-4f81-11e9-96c0-f54b6677f08c.png)

**Comment by makus82** [comment]
![statssuggest5](https://user-images.githubusercontent.com/11581207/54977260-6ee1ca00-4fa5-11e9-90b1-98c4bf8d1aac.png)
![statssuggest6](https://user-images.githubusercontent.com/11581207/54977261-6ee1ca00-4fa5-11e9-8739-a2c99811fda7.png)

**Comment by Atrosha** [comment]
> ![statssuggest4](https://user-images.githubusercontent.com/11581207/54969145-cd974b80-4f85-11e9-8282-d74d07b508d0.png)

That looks better then others, but it needs your representation with a some trained agent.

**Comment by makus82** [comment]
i think this better choice) 
https://user-images.githubusercontent.com/11581207/54968505-a0e23480-4f83-11e9-875b-b3561263200f.png

big and align by both sides so no empty places)

**Comment by Atrosha** [comment]
Нет.

Сейчас объясню почему...

Смотри, у нас получается 3 клеточки минимум с текущим набором, с твои - будет 4 пикселя минимум полоска. т.е. урежутся чутку возможности, и не понятно, где там значение, а где пустое место.

**Comment by makus82** [comment]
На счет областей где например ранен человек или стамина низкая это можно сохранить как есть 
тоесть показывать чуть другим цветом

**Comment by Atrosha** [comment]
Оно не в высоту не хватает, а в длинну. Будет 4 пикселя занимать минимальная полоска, а так - три. Та полоска, что нам показывает пустое место, она сейчас не учитавается, а если будет прямоугольник, то меньше на единицу будет, потому что справа, или как ты хочешь слева будет граница. Понял? Это достаточно критично.

**Comment by makus82** [comment]
ну по бокам можно убрать .. да тогда тот вариант с нижней 1px полоской подходит

**Comment by makus82** [comment]
also in vanilla more pale colors of skill bars...

**Comment by makus82** [comment]
or somthing like that
![statssuggest3](https://user-images.githubusercontent.com/11581207/57584798-2431f800-74e8-11e9-8daf-65d52b7e65cd.png)
![statssuggest4](https://user-images.githubusercontent.com/11581207/57584799-2431f800-74e8-11e9-8c31-d7259434770b.png)

**Comment by Atrosha** [comment]
IMNSHO much better with big screen resolutions

![Screenshot from 2019-05-12 19-54-18](https://user-images.githubusercontent.com/37053399/57585368-dd480080-74ef-11e9-92b8-565bb5c43744.png)

**Comment by makus82** [comment]
уже смотрится круче ) ляпота

**Comment by makus82** [comment]
наблюдение, линия и текст не выровняны по нижней стороне и плюс линия скила не 6 пикселей ну или не во всю ширину не заглавных букв текста

понимаю что это WIP

**Comment by Atrosha** [comment]
по мне так норм или поднять на одну линию вверх и добавить толщины?

**Comment by makus82** [comment]
![image](https://user-images.githubusercontent.com/11581207/57585477-66ac0280-74f1-11e9-8eeb-1eed227bda00.png)

**Comment by Atrosha** [comment]
![Screenshot from 2019-05-12 20-19-10](https://user-images.githubusercontent.com/37053399/57585630-48470680-74f3-11e9-8069-934540a6b219.png)

**Comment by makus82** [comment]
ну если еще желание есть просто глянь как у меня сделано) 
срезать бы 2 пикселя сверху чтоб линия скила была  по основной линии не заглавных букв

**Comment by makus82** [comment]
...хотя где стамина оно как раз по верхеней стороне как нужно 
а по нижней стороне ушло на 2 пикселя за линию

**Comment by makus82** [comment]
Спасибо, приятно посмотреть на свой дизайн в работе)

**Comment by makus82** [comment]
а еще вопрос: выровнять текст по левой стороне на сколько сложно?

**Comment by Atrosha** [comment]
не слодно, но не нужно. Слишком радикально будет.

**Comment by makus82** [comment]
> не сложно, но не нужно. Слишком радикально будет.

совсем нет, процесс запущен и дизайн это когда все гармонично и устойчиво
правая сторона линий скилов выровнена по правому краю а левая сторона будет иметь 
такое большое пустое, кривое пространство ? не логично
