### ISSUE TITLE
Ground vehicles cannot have more than 1 weapons

### ISSUE THREAD

**Issue by JohnSmith25** [OpenApoc/OpenApoc#555]
I tried to do some modifications such as modifying the Griffon AFV to have 2 weapon slots, yet for some reason OpenApoc won't let me, I can however give it another general equipment slot. The log doesn't mention any warning or error for this vehicle. You can test it for yourself by just loading the mod as it contains the changes and you start out with the griffon. 
[testmod_common.zip](https://github.com/OpenApoc/OpenApoc/files/3103499/testmod_common.zip)
<img src="https://user-images.githubusercontent.com/14570163/56502812-e7d83100-6513-11e9-8226-f335064e0dd4.png" width="340" height="340" />
<img src="https://user-images.githubusercontent.com/14570163/56502813-e7d83100-6513-11e9-8e31-fadd84034e1e.png" width="340" height="340" />

**Comment by makus82** [comment]
our main goal now is to finish vanila mechanics first
just for info

**Comment by JohnSmith25** [comment]
> our main goal now is to finish vanila mechanics first
> just for info

> Key Features
>
>    Unlimited modding capabilities, which was not possible in the original

I'm already aware that OpenApoc is not completely finished and I observed this project for quite some time. But for anyone else that is responsible for updating the UFOpedia wiki page should also change this one https://www.ufopaedia.org/index.php/Info_%28OpenApoc%29 as it doesn't mention that it needs to finish 1.0 first before the other goals are targeted, obviously it does mention that it needs more programmers. Thus the mods priority should be lowered or at least not "heavily advertised" as it gives the impression right now. I am not familiar with C let alone C++ so I cannot help this project with coding stuff as I am in learning process myself.

**Comment by makus82** [comment]
> > our main goal now is to finish vanila mechanics first
> > just for info
> 
> > Key Features
> > Unlimited modding capabilities, which was not possible in the original
> 
> I'm already aware that OpenApoc is not completely finished and I observed this project for quite some time. But for anyone else that is responsible for updating the UFOpedia wiki page should also change this one https://www.ufopaedia.org/index.php/Info_%28OpenApoc%29 as it doesn't mention that it needs to finish 1.0 first before the other goals are targeted, obviously it does mention that it needs more programmers. Thus the mods priority should be lowered or at least not "heavily advertised" as it gives the impression right now. I am not familiar with C let alone C++ so I cannot help this project with coding stuff as I am in learning process myself.

yes ty Alex will do (about wiki update)

**Comment by JonnyH** [comment]
It looks like the attached XML is wrong - you need to wrap the new weapon slot in a new <entry> node.

e.g. (in vehicle_types.xml under <equipment_layout_slots>)
not:
<entry>
 <type>VehicleWeapon</type>
  .... Description of first slot
  <type>VehicleWeapon</type>
  .... Description of first slot
</entry>
  

but instead:
<entry>
 <type>VehicleWeapon</type>
  .... Description of first slot
</entry>
<entry>
  <type>VehicleWeapon</type>
  .... Description of first slot
</entry>

As the serializer for openapoc only creates a new object describing a slot for each <entry> node, so the first example here (and in the attached .xml) only creates a single object and loads it with the data, it doesn't create a second slot object as desired. I believe currently it only loads the first of each description tag it finds, and ignores any subsequent tags of the same name.

**Comment by JohnSmith25** [comment]
Yes thanks for looking at it JohnnyH I fixed it now. I should have took a closer look at the </entry> enclose, this is how it looks now the position/size is crude but it works at least. 
```
      <entry>
          <type>VehicleWeapon</type>
          <align_x>Centre</align_x>
          <align_y>Top</align_y>
          <bounds>
            <p0>
              <x>6</x>
              <y>6</y>
            </p0>
            <p1>
              <x>10</x>
              <y>10</y>
            </p1>
          </bounds>
		  </entry>
		  <entry>
          <type>VehicleWeapon</type>
		  <align_x>Centre</align_x>
          <bounds>
            <p0>
              <x>12</x>
              <y>6</y>
            </p0>
            <p1>
              <x>14</x>
              <y>14</y>
            </p1>
          </bounds>
        </entry>
```
Ingame:
<img src="https://user-images.githubusercontent.com/14570163/56520435-b4fa6100-6544-11e9-908b-9d78daaaaa42.png"  width="240" height="240" />

<img src="https://user-images.githubusercontent.com/14570163/56520438-b592f780-6544-11e9-918f-9b8a53c94326.png" width="240" height="240" />

**Comment by FilmBoy84** [comment]
Issue fixed, closing this issue :)
