### ISSUE TITLE
CONCEPT of diplomacy interface, WIP (work in progress), for possible future mod for OpenApoc

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#564]
_Just my photoshop concept WIP (work in progress) of diplomacy interface for possible future mod for OpenApoc_

You can add your ideas or feedback by writing here or download PSD or image and edit or draw on it

![diplomacy3](https://user-images.githubusercontent.com/11581207/56860761-c7402900-69a2-11e9-9e52-85f6b2d11fe3.png)
[diplomacy3.zip](https://github.com/OpenApoc/OpenApoc/files/3124717/diplomacy3.zip)

**Comment by makus82** [comment]
![diplomacy_open](https://user-images.githubusercontent.com/11581207/56861376-d0cc8f80-69a8-11e9-99bc-bb379eb330ec.png)
[diplomacy_open.zip](https://github.com/OpenApoc/OpenApoc/files/3124759/diplomacy_open.zip)

**Comment by FilmBoy84** [comment]
Would love to see an implementation of the old diplomacy tables
Great PS work as always
Can you move this to the forums as i have done for the alien lifecycle so we can continue discussion?
