### ISSUE TITLE
macOS: Crash when starting a new game in Novice difficulty

### ISSUE THREAD

**Issue by ashenomo** [OpenApoc/OpenApoc#567]
I tried running OpenApoc and immediately starting a new game in Novice difficulty. All attempts on macOS 10.14.4. Built and linked with ASan and UBSan (`set(CMAKE_CXX_FLAGS "-O1 -g -fsanitize=address,undefined")`)

The game crashes (https://pastebin.com/e0JALSqY) with `2019-04-28 22:15:53.662 OpenApoc[45021:727052] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'`

Starting a game in any other difficulty works okay.

**Comment by JonnyH** [comment]
The exception appears to be occuring in the SDL dialog stuff trying to show the error:
"E 13552027840 void OpenApoc::GameState::fillPlayerStartingProperty(): City map has no buildings with valid base layouts"

While failing to show the error in a useful way is a bug, that error suggests that your data files have somehow got messed up (or not loaded correctly).

Has the data extraction target run successfully?

**Comment by JonnyH** [comment]
PR #570 may help with the crash - but then it'll just show the error and abort :)

**Comment by ashenomo** [comment]
Oops - this was due to me accidentally renaming the directory data/difficulty1_patch/gamestate to something else and not noticing (the wonders of Yubikey OTP accidentally triggering 😞 ).
Data extraction target was still completing successfully though - issue was only fixed after a clean build.

**Comment by JonnyH** [comment]
Yeah, the build dependencies for the source data is hard to setup for optional directory trees like that - so a clean rebuild of the data extraction target is probably best if you ever modify them.
