### ISSUE TITLE
When starting a new game, agents #3 and #4 don't have any equipment

### ISSUE THREAD

**Issue by ashenomo** [OpenApoc/OpenApoc#573]
Among the 12 agents initially provided, the ones in positions 3 and 4 in the Equip Agents screen have no armor or equipment. Seen on macos on all difficulty levels.
![Screen Shot 2019-04-30 at 22 41 23](https://user-images.githubusercontent.com/49964989/56965906-1f408080-6b99-11e9-9d7a-fb36ab64a3de.png)

**Comment by FranciscoDA** [comment]
These are actually agents 10 and 11 they appear in slots 2 and 3 because they are sorted lexicographically. They dont have any starting equipment defined in gamestate_common so they spawn with nothing. Btw, in vanilla there are only 10 starting agents so maybe we should remove them.

**Comment by makus82** [comment]
yes we should, its, i think, added for testing purposes

**Comment by FilmBoy84** [comment]
Resolved in #1174
