### ISSUE TITLE
Bug in translation

### ISSUE THREAD

**Issue by altiereslima** [OpenApoc/OpenApoc#576]
Even with the translated game there are English.

![image](https://user-images.githubusercontent.com/18044879/57043616-7cdad880-6c3e-11e9-9e38-a52d59c7b310.png)
![image](https://user-images.githubusercontent.com/18044879/57043691-b0b5fe00-6c3e-11e9-9fd6-22b2c03b3303.png)

![image](https://user-images.githubusercontent.com/18044879/57043784-ebb83180-6c3e-11e9-95e8-e009907019e5.png)
![image](https://user-images.githubusercontent.com/18044879/57043827-0e4a4a80-6c3f-11e9-9fb1-f86152499859.png)
![image](https://user-images.githubusercontent.com/18044879/57044688-beb94e00-6c41-11e9-9b10-06214caa2f5f.png)

**Comment by makus82** [comment]
yes ty @altiereslima its known bug and WIP problem)

**Comment by makus82** [comment]
and also not all language files at github repository up to date
so you can tranlate it at transifex  https://www.transifex.com/x-com-apocalypse/
and then downlaod .po file ...
its need to translate .po file (in data\languages) then compile it to .mo file (po2mo.net) and put it in my case to data\languages\ru_RU\LC_MESSAGES\ufo_string.mo
by replace
