### ISSUE TITLE
git

### ISSUE THREAD

**Issue by KobaWhite** [OpenApoc/OpenApoc#578]
:~/temp/OpenApoc-master$ git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git

cant understand how to resolve this

**Comment by makus82** [comment]
dont know about ur problem but google give many results) 
https://www.google.com/search?q=fatal%3A+not+a+git+repository+(or+any+of+the+parent+directories)%3A+.git

**Comment by JonnyH** [comment]
How did you clone the source code?

You need to use 'git clone' (or a UI tool that wraps that), not just download the source package from the github website
