### ISSUE TITLE
OpenApoc crashes (during geoscape and tactical)

### ISSUE THREAD

**Issue by ARKMAN30** [OpenApoc/OpenApoc#579]
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/3148649/openapoc_log.txt)

Maybe a sound issue on specific PC or specific sound card? X-Fi titanium...

**Comment by ARKMAN30** [comment]
Finally solved by unchecking tooltips........

**Comment by ARKMAN30** [comment]
.... so it obviously crashes before tooltip should apear on the screen.

**Comment by makus82** [comment]
So its after any tooltips popup? or in some particular screen?

**Comment by makus82** [comment]
you use saves i think 
so pls attach save also in zip

**Comment by JonnyH** [comment]
What revision are you using? I can't find v0_1_451_gcf7fc374

"cf7fc374" matches no sha in git, and the current master is v0.1-448 (not 451) according to my git...

I'm asking as there was a recent crash fix related to tooltips in pr #561

**Comment by makus82** [comment]
@ARKMAN30 pls check it now at new latest build

**Comment by JonnyH** [comment]
I haven't been able to repro this - I'll close it on the assumption it was fixed in #561 - please reopen if necessary
