### ISSUE TITLE
Cannot equip left hand armor :D 

### ISSUE THREAD

**Issue by ARKMAN30** [OpenApoc/OpenApoc#580]

**Comment by makus82** [comment]
Heya @ARKMAN30 pls describe more detail or record video 
if not i will close this

**Comment by ARKMAN30** [comment]
I can equip all parts of armor on agent except the left hand part. It can be picked up and dragged bud at the point it shoud attach on the arm after releasing mouse button it don´t attach and stays in the bottom selection. Looks like missing offset for this part on the soldiers body. I can post video later today if you want.

**Comment by FranciscoDA** [comment]
This is the same as #371 and #569

**Comment by makus82** [comment]
try recall after what exact time its started
also attach save wich it in zip

**Comment by Paddywhacker** [comment]
This bug goes back at least 6 months.  It is present in OpenApoc-v0.1-325-g3a182f0c.

**Comment by makus82** [comment]
i close this then Francisco point on first issue on this topic
