### ISSUE TITLE
Bug "trying to launch already-launched vechicle"

### ISSUE THREAD

**Issue by Erydian** [OpenApoc/OpenApoc#582]
Hi
after loading, the game  crashes with a message like in the header. adding a log 
PC ver OpenApoc-v0.1-451-gcf7fc374
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/3168985/openapoc_log.txt)

**Comment by makus82** [comment]
upload save pls in zip

**Comment by Erydian** [comment]
I added a save file
[save_asas.zip](https://github.com/OpenApoc/OpenApoc/files/3169264/save_asas.zip)

**Comment by Atrosha** [comment]
At first it raises an error

![Screenshot from 2019-05-11 19-54-49](https://user-images.githubusercontent.com/37053399/57572709-110b2380-7427-11e9-81b4-04335e658ff9.png)

After selecting "skip" option in error message dialog game rises next

![Screenshot from 2019-05-11 19-55-07](https://user-images.githubusercontent.com/37053399/57572712-2718e400-7427-11e9-92e5-c77e8c52a225.png)

After selecting "skip" option in error message dialog geme crashes

I attached gdb's stack trace:
[582_gdb_stacktrace.txt](https://github.com/OpenApoc/OpenApoc/files/3169273/582_gdb_stacktrace.txt)

**Comment by emptyVoid** [comment]
Should be fixed by #669 (save game is no longer valid).

**Comment by FilmBoy84** [comment]
Closing as requested by emptyVoid
If the problem returns, please create a new issue and reference this as appropriate
