### ISSUE TITLE
Another tooltip related crash

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#584]
While surveying Equip Agent screen on current master branch

[gdb_stacktrace.txt](https://github.com/OpenApoc/OpenApoc/files/3169869/gdb_stacktrace.txt)

**Comment by Atrosha** [comment]
I think it's similar or #565

**Comment by Atrosha** [comment]
It's just game version incompatibility with old savegame file. I closing the issue.

**Comment by JonnyH** [comment]
Should be fixed with #552
