### ISSUE TITLE
Chrysalis is a hostile unit but agents won't shoot.

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#594]
I noticed today that whenever I came across Chrysalis', my agents would not shoot at it even though it was seen as hostile. The little red dot showed that it was seen, and the agents would not even lift their weapons.

**Comment by FilmBoy84** [comment]
This is normal behaviour, as a chrysallis presents no threat we want X-COM to capture live if possible, so they should not shoot it

This was certainly the case in the EU/UK original release of the game

You should still be able to force agents to shoot however

**Comment by Quickmind01** [comment]
The Steam version still has the ability for agents to shoot the Chysalis, but I think the way it is now is better. If it's not harm, there's not sense in wasting ammo.
