### ISSUE TITLE
Camera Follow in Geoscape

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#600]
In the original (and currently the Steam version), if the Camera Follow button was selected, it would follow the craft only if that craft's tab was selected. For instance, if I was following my Interceptor, when I clicked on the Bases tab, the following would stop.

Also, if I followed my ship back to base, once it completely entered the base, I would be free to move the camera, even though Camera Follow was still activated. Currently in OpenAPOC, it stays on the craft until Camera Follow is deactivated. Is this intended?

This is more a question/suggestion than bug.

**Comment by makus82** [comment]
moved to Issue #941
