### ISSUE TITLE
[MOD CONCEPT] Aliens from first X-COM: UFO Defense

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#603]
Just PS work, for now, how they can look in the game
![aliens-from-xcom1](https://user-images.githubusercontent.com/11581207/59465906-a9d0fc80-8e34-11e9-829f-4b45c01e40a5.png)

**Comment by Paddywhacker** [comment]
Does the code structure permit expanding the number of various objects such as character types, without having to completely re-factor it?  How about organisations?

**Comment by makus82** [comment]
@Paddywhacker Good question)

**Comment by JonnyH** [comment]
It should be possible to add a completely new AgentType without modifying the code
