### ISSUE TITLE
Zoom button in message history didn't load

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#604]
A construction vehicle was destroyed while I was running at Ultra Fast, and when I tried to zoom on the incident, the camera wouldn't move. When looking at the Message History, this event didn't have a zoom button, even though it was a single-line message. The game auto-paused when this occurred.

**Comment by makus82** [comment]
wow strange, any save or screen?

**Comment by makus82** [comment]
btw you can just play in window mode and press ALT PRNTSCRN  then just select window with issue editor and CTRL V  and its upload scrn

**Comment by FilmBoy84** [comment]
I cannot replicate this nor find any examples in the current game so closing

If the issue reoccurs please make a new issue with the savegame, a screenshot and any video you can provide and reference this issue
