### ISSUE TITLE
Advanced Labs Scientist List Columns of 6

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#606]
When adding scientists to the Advanced Bio and Quantum labs, the scientists are placed in columns of 6 rather than 5. This causes one scientist to be mostly off screen.
[save_Advanced Labs Scientists.zip](https://github.com/OpenApoc/OpenApoc/files/3293168/save_Advanced.Labs.Scientists.zip)

![image](https://user-images.githubusercontent.com/51022165/59552478-1b03d300-8f4d-11e9-92e1-ca816f32e535.png)

**Comment by Paddywhacker** [comment]
This was introduced in version 0.0.399, the previous version, 0.0.396 was good.
