### ISSUE TITLE
Alien Containment List

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#608]
In my alien containment, there are two entries for Dead Skeletoids and Dead Micronoid Aggregates. Brainsucker pods are also listed and take 80% space.
[save_Stream Test.zip](https://github.com/OpenApoc/OpenApoc/files/3293375/save_Stream.Test.zip)

**Comment by Quickmind01** [comment]
Perhaps the pods are bugged in the Sell menu, but they are taking 80% containment space. Also, the Dead Skeletoid and Dead Micronoid are still listed in the alien containment, but are grayed out since 0 are left.

**Comment by makus82** [comment]
i get this )) 999%
![image](https://user-images.githubusercontent.com/11581207/59554608-2dfabf80-8fae-11e9-846e-c221e167d3e4.png)

**Comment by FilmBoy84** [comment]
Confirmed, brainsucker pods should NOT be in the alien containment and take a stupid amount of space there

RELATED ISSUES #369 AND #370

Here's just one example of how empty i have to keep my alien containment
![image](https://user-images.githubusercontent.com/33913088/63095429-1ebed080-bf63-11e9-9f68-404392e07ba0.png)
