### ISSUE TITLE
All civilians in all Alien Rescue missions are Hostile

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#616]
After alien rescue mission in Transstellar apartments the relationship with that corporation changed to "Unfriendly" and after that subj with any other corporation's Alien rescue mission.

I think its related to #305

**Comment by FilmBoy84** [comment]
Updating issue 305 with this, and closing this issue as otherwise we end up with references to many, many, related bugs all over the place

Thanks for the report atrosha, good catch... <3
