### ISSUE TITLE
Its possible to add minecraft like F3 overlay for output bacgkround information?

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#620]
Its possible to add minecraft like F3 overlay for output bacgkround information for debug?
for example binded at F1 in OpenApoc

where will be for ex:

- -Number of music track playing now
- -Build version
- -How many memory game use
- -In future maybe (list of mods)
- Link for Bag reporting
- Link for Github and discord and forum links

Statistic

- -Location name where you at current moment (Cityscape or Name of the battlescape map etc)
- -Current date and time and number of week
- -How many agents die
- -How many aliens killed
- -How many civilians killed
- -How many humans guards killed
- -How many building raids finished
- -How many Ufo Crash mission finished
- -How many research completed
- -Your funds (and how many you spent money )

Debug

- -How many aliens right now in the city
- -How many UFOs fly in game right now
- -Game fase (where somthing for u not available )
- -List of names orgs and amount of they
- 
- -Some random funny frase)

![image](https://user-images.githubusercontent.com/11581207/59962708-aa7f2800-94f1-11e9-9026-a839a6a52d4c.png)

**Comment by makus82** [comment]
![screenshotF3overlay](https://user-images.githubusercontent.com/11581207/59981605-954beb80-960e-11e9-8a81-b1e4ceed8a6e.png)

**Comment by JonnyH** [comment]
While I'd like some method of adding useful debug info to some kind of live overlay/output, it doesn't make sense to do it "up front" - when working on something and debugging something, adding specific useful output may be useful, but trying to figure out what is useful in advance is hard, and having "non-useful" info there just adds work, more code to maintain and break, and adds visual clutter.

It feels most of the listed info isn't /really/ for debugging, more as a weird stats overlay - there are already stats pages in the original (if not yet implemented in openapoc) and better "in-game" places to add such things.

**Comment by makus82** [comment]
just write what first come to mind
yes its need to think what need to be output

**Comment by makus82** [comment]
Also maybe that info will be intrested for testers so they no need describe many thing
they just turn on overlay and screen and send in bugreport....

**Comment by makus82** [comment]
And also many screenshots will uploaded in internet with our basic info (websites)

**Comment by JonnyH** [comment]
I suspect the log file we generate will contain all that info and more, and be more useful as it can be extracted after a crash or similar.

Adding this in advance as a "Feature" is probably putting the cart before the horse, new useful debug info will come from the natural process of debugging problems - so long as people are willing to cleanup their debugging "hacks" and what they found useful to push upstream.

Debugging info isn't a feature, it's an ongoing process :)

And I doubt many people will take screenshots of openapoc with some nasty-looking text smeared over the screen....
