### ISSUE TITLE
Cityscape Debug R Command Crash

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#626]
When using the Repair command in Cityscape (R-key), the game crashes with the attached error. I did have damaged terrain and buildings so there should have been things to repair.

![image](https://user-images.githubusercontent.com/51022165/59980898-aa4e5d80-95c1-11e9-9da9-b71420182429.png)

**Comment by JonnyH** [comment]
Was this a result of force-destroying something (ctrl-alt-shift click)? As that doesn't seem to handle the bottom z=1 tiles, which /should/ be immortal - instead it seems to put them in a bad state that causes them to be repaired while not destroyed - causing a the same error as seen here.

If it's from a different source of destruction, it may be a different issue - but we should probably handle "weird" uses of debug tools anyway :)

**Comment by Quickmind01** [comment]
I really can't recall. I would imagine it was from me using debug commands to destroy, but I can test more later.
