### ISSUE TITLE
Alien Battleship Stuck

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#629]
5 UFOs entered the map, however, the Battleship seemed to be stuck on the gate? I was able to knock it down with a debug command, but even destroying the building next to it didn't free it. Attacking it with craft did not help, either. The other UFOs went to it and just hovered next to it until I attacked.
[save_Battleship Stuck.zip](https://github.com/OpenApoc/OpenApoc/files/3327847/save_Battleship.Stuck.zip)

**Comment by Paddywhacker** [comment]
I tried your saved game in OpenApoc versions right back to OpenApoc-v0.1-325-g3a182f0c and the ship remained stuck, so it is a long-standing issue that has just been uncovered.

**Comment by Quickmind01** [comment]
Update: "Shot down" a battleship while it was stuck. I completed the mission and the UFO remained. It did not self destruct even though the game called for it.

W 899062075500 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): CLICKED VEHICLE Alien Battleship 2 at {98.5,85.5,8.5}
W 899067391900 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission RestartNextMission
W 899072286700 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission Crash landing {98,85,2}
W 899080319300 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission SelfDestruct in 2021280 ticks
W 899786907700 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): CLICKED VEHICLE Alien Battleship 2 at {98.5,85.5,8.5}
W 899793202300 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission RestartNextMission
W 899803302100 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission Crash landing {98,85,2}
W 899810294700 bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission SelfDestruct in 2021280 ticks

**Comment by FilmBoy84** [comment]
This also applies to Mothership too
It appears large craft are affected

**Comment by FilmBoy84** [comment]
This issue is still not resolved as reported by @Proselyte-Arcturus using a build from the past week (at time of writing). Giving it a bump
