### ISSUE TITLE
Assertion error when replacing item in hand on a specific agent

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#643]
With the unit Alice Taylor, if I replace the toxi-gun with another item and click OK, the game crashes and gives the attached error. It only seems to be her so far, though I didn't test any non-hybrids as I thought it was a mind bender issue. I will update later with a clip from my stream, but the test ends at about 46 minutes into the stream.

![Assertion Error](https://user-images.githubusercontent.com/51022165/61578836-5a7c8c80-aac2-11e9-9097-0ffe0c8322be.jpg)
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/3413602/openapoc_log.txt)

**Comment by Quickmind01** [comment]
[save_Stream Test - New Battle.zip](https://github.com/OpenApoc/OpenApoc/files/3413626/save_Stream.Test.-.New.Battle.zip)
 Forgot to upload save.

**Comment by Quickmind01** [comment]
I later tested in a different mission by changing Alice Taylor's equipment in the mission setup screen. The battle loaded fine, but when I selected her group (Team 2), the game crashed with the same error. So something seems to be up with this particular agent and NOT having a toxi-gun in her right hand.

**Comment by makus82** [comment]
great work Q , great stream https://www.twitch.tv/quickmind

**Comment by Quickmind01** [comment]
Here is a link to the video showing some testing I did. Essentially, this one agent is the only one with this issue. https://www.twitch.tv/videos/456100905

**Comment by JonnyH** [comment]
This seems to be due to the accuracy bar drawing - it's 50 pixels wide, but doesn't clamp. The selected agent and gun happens to end up with a real accuracy of 52, so tries to write to beyond the bounds of the image when drawing that weapons' accuracy indicator.
