### ISSUE TITLE
Request: Zoom and rotate the camera in Cityscape and Battlescape

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#668]
Would add so much to the game.  A "reset camera" command would be a useful addition, too.

**Comment by makus82** [comment]
Zoom and rotate the camera ? but its not 3d its 2d srites
and zoom will be not really good

**Comment by FilmBoy84** [comment]
It is possible, but would require an entirely new set of sprites for every angle of view

This would be tens of thousands of new drawings

Even if you take the method the original devs use of creating a 3D model and then using scripts to pull the required sprites with the correct lighting from it, you are still looking at hundreds of models that then have to be "captured" as sprites

Going to add the feature request and won't fix labels to this before closing and archiving

If we ever get to a post 1.0 state maybe someone will pick up the monumental task of getting all the new graphics together... But if they are doing that we may as well be looking at an OpenTTD style "OpenGFX" situation whereas OpenApoc could become none-dependent on original graphics

**Comment by Paddywhacker** [comment]
OK, no free rotation, but how about zooming?  Currently we can only zoom by changing the resolution in config.

**Comment by makus82** [comment]
well its possible i think make somthing like zoom tool little programm in windows 
but im not programmer 

https://www.sevenforums.com/attachments/software/331338d1486629779t-how-zoom-specific-applications-window-mag.jpg

**Comment by makus82** [comment]
somthing like that?
![openapoc-zoom200](https://user-images.githubusercontent.com/11581207/62410558-bfba9c80-b5ef-11e9-95cd-413a385c7e5f.png)

**Comment by makus82** [comment]
![openapoc-zoom-city-200](https://user-images.githubusercontent.com/11581207/62410646-25f3ef00-b5f1-11e9-8a39-73a5f02e32e3.png)

**Comment by makus82** [comment]
so i will reopen till Jonny somthing to say about zoom
