### ISSUE TITLE
Last build loading time problem 6c0ce2e4

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#680]
- in window or in fullscreen its take many more time to start new game (like its loading 2-4 times over and over) ~10 seconds
- and mission loading also time increased  ~26 seconds
- and time superspeed is getting big freezes 

im overwritten on top of an existing game. But before this there were no problems
and also remove all old strings in config

**Comment by JonnyH** [comment]
I don't see any difference in the loading time on my machine.

Any chance you can post an example save that shows a large difference?

**Comment by makus82** [comment]
after update with screenshot numbering 
all goes normal
