### ISSUE TITLE
[Alien Dimension] UFOs do not search for crashsite and explode. X-COM Craft become stuck.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#682]
Raided alien zone and downed UFO didn't explode, so I tried investigating one with a crewed annihilator, but it then froze and wouldn't move, even when the other ships returned to the portal.
[save_Stuck in zone.zip](https://github.com/OpenApoc/OpenApoc/files/3473746/save_Stuck.in.zone.zip)

**Comment by makus82** [comment]
you use old save and with latest build?

**Comment by Paddywhacker** [comment]
No, version is OpenApoc-x64-v0.1-563-g6c0ce2e4 and game started with this one, I think, or maybe 555.

**Comment by FilmBoy84** [comment]
Can confirm this, for some reason the Alien Ships are not crashing correctly
Firstly the Battleship is stuck, hovering, above the umbilical to the left... It should search for a place to crash, fall and explode, removing itself from the map

I also attacked an escort ship that flew in front of the stuck annihilator, this crashed, but did not explode and become removed

The remaining bomber is targetable, but the annihilator will not persue

There appears to be several things at play here

* Alien Ships do not search correctly or thoroughly for a crash site
* Alien Ships do not explode and remove themselves from the map on contact with the dimension floor
* Craft path-finding has some issues if pursuing a craft that cannot crash (which leads to them becoming stuck)

@Paddywhacker can you please provide a copy of the log segment made from just before you downed that battleship till you attempting to land next to it please?

Sadly, whilst I can open the savegame and see the results of what happened, knowing what caused it to try and replicate is not possible as it is AFTER the event.

**Comment by Paddywhacker** [comment]
Here is a zipped save before the event and again after the event.  I used to know where the log file was located, but cannot find it now.  Does the log now go to stdout rather than a file?
[saves.zip](https://github.com/OpenApoc/OpenApoc/files/3476224/saves.zip)

**Comment by JonnyH** [comment]
The log goes to the user's writeable directory, which on windows10 is c:\users\YOUR_USERNAME\appdata\roaming\openapoc

Or the equivalent on other OSs

**Comment by Paddywhacker** [comment]
Thanks.  Here it is
[log.txt](https://github.com/OpenApoc/OpenApoc/files/3479101/log.txt)
