### ISSUE TITLE
No agent matching id AGENT 11

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#691]
This is possibly related to #368 and #505 but appeared AFTER a combat mission and several days after a transfer done through the HIRE screen (scientist moved to another base in same transaction as hire and fire some others, see example below as openapoc allows this all in one go, unlike OG)

![image](https://user-images.githubusercontent.com/33913088/62939178-8b519800-bdc8-11e9-9a90-59c3674d0648.png)

On leaving a tac mission i am immediately presented with the following
![image](https://user-images.githubusercontent.com/33913088/62938824-be475c00-bdc7-11e9-82fd-a22bd3a9eab3.png)
![image](https://user-images.githubusercontent.com/33913088/62938846-c8695a80-bdc7-11e9-8e69-208c4d3d27ca.png)

On clicking OK the game presents the following further error
![image](https://user-images.githubusercontent.com/33913088/62938946-ffd80700-bdc7-11e9-9121-c131a1a33ad2.png)
Then crashes, unable to perform a backtrace :(

One agent died in the mission, this was one of the agents provided at game start
This may be relevant?

**Comment by JonnyH** [comment]
Yeah, that error saying "No ${OBJECT_TYPE} object matching ID ${X} found" is pretty much the last gasp before we know we're going to crash, as it's due to a StateRef<> pointing to something that no longer exists.

I'll try to get a similar situation and see if I can repro....

**Comment by Quickmind01** [comment]
Received this error out of the blue while producing Disruptor Left Arm armor:

I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::City::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,const class OpenApoc::GroundVehicleTileHelper &,bool,bool,bool,bool): Trying to route from rs 543 to rs 623
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::City::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,const class OpenApoc::GroundVehicleTileHelper &,bool,bool,bool,bool): No more road segments to expand after 430 iterations
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::City::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,const class OpenApoc::GroundVehicleTileHelper &,bool,bool,bool,bool): Surprisingly, no nodes to expand! Closest path ends at 543
W void __cdecl OpenApoc::StateRef<class OpenApoc::ResearchTopic>::resolve(void) const: ResearchTopic object has invalid prefix - expected "RESEARCH_" ID "MANUFACTURE_DISRUPTOR_ARMOR_(LEFT_ARM)"
E class std::shared_ptr<class OpenApoc::Agent> __cdecl OpenApoc::Agent::get(const class OpenApoc::GameState &,const class OpenApoc::UString &): No agent matching ID "AGENT_2787"
  0x0,000,7FF,636,05E,502 +0x140695445038338x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,05E,942 +0x140695445039426x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,045,E06 +0x140695444938246x

  0x0,000,7FF,636,280,979 PHYSFS_writeSLE64+0x500873x

  0x0,000,7FF,636,0EC,8B0 PHYSFS_writeSLE64+0x18446744073708397504x

  0x0,000,7FF,636,278,E02 PHYSFS_writeSLE64+0x469266x

  0x0,000,7FF,636,223,51E PHYSFS_writeSLE64+0x118830x

  0x0,000,7FF,636,221,FE3 PHYSFS_writeSLE64+0x113395x

  0x0,000,7FF,636,224,5E5 PHYSFS_writeSLE64+0x123125x

  0x0,000,7FF,636,11D,109 PHYSFS_writeSLE64+0x18446744073708596249x

  0x0,000,7FF,636,043,12A PHYSFS_writeSLE64+0x18446744073707703354x

  0x0,000,7FF,636,01F,C4E PHYSFS_writeSLE64+0x18446744073707558750x

  0x0,000,7FF,636,467,115 PHYSFS_writeSLE64+0x2493477x

  0x0,000,7FF,636,207,B10 PHYSFS_writeSLE64+0x5664x

  0x0,000,7FF,B31,027,974 BaseThreadInitThunk+0x20x

  0x0,000,7FF,B31,C9A,271 RtlUserThreadStart+0x33x

E void __cdecl OpenApoc::StateRef<class OpenApoc::Agent>::resolve(void) const: No Agent object matching ID "AGENT_2787" found
  0x0,000,7FF,636,05E,502 +0x140695445038338x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,05E,942 +0x140695445039426x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,045,E06 +0x140695444938246x

  0x0,000,7FF,636,0EC,9AE +0x140695445621166x

  0x0,000,7FF,636,278,E02 PHYSFS_writeSLE64+0x469266x

  0x0,000,7FF,636,223,51E PHYSFS_writeSLE64+0x118830x

  0x0,000,7FF,636,221,FE3 PHYSFS_writeSLE64+0x113395x

  0x0,000,7FF,636,224,5E5 PHYSFS_writeSLE64+0x123125x

  0x0,000,7FF,636,11D,109 PHYSFS_writeSLE64+0x18446744073708596249x

  0x0,000,7FF,636,043,12A PHYSFS_writeSLE64+0x18446744073707703354x

  0x0,000,7FF,636,01F,C4E PHYSFS_writeSLE64+0x18446744073707558750x

  0x0,000,7FF,636,467,115 PHYSFS_writeSLE64+0x2493477x

  0x0,000,7FF,636,207,B10 PHYSFS_writeSLE64+0x5664x

  0x0,000,7FF,B31,027,974 BaseThreadInitThunk+0x20x

  0x0,000,7FF,B31,C9A,271 RtlUserThreadStart+0x33x

E class std::shared_ptr<class OpenApoc::Agent> __cdecl OpenApoc::Agent::get(const class OpenApoc::GameState &,const class OpenApoc::UString &): No agent matching ID "AGENT_2787"
  0x0,000,7FF,636,05E,502 +0x140695445038338x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,05E,942 +0x140695445039426x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,045,E06 +0x140695444938246x

  0x0,000,7FF,636,280,979 PHYSFS_writeSLE64+0x500873x

  0x0,000,7FF,636,0EC,8B0 PHYSFS_writeSLE64+0x18446744073708397504x

  0x0,000,7FF,636,278,E17 PHYSFS_writeSLE64+0x469287x

  0x0,000,7FF,636,223,51E PHYSFS_writeSLE64+0x118830x

  0x0,000,7FF,636,221,FE3 PHYSFS_writeSLE64+0x113395x

  0x0,000,7FF,636,224,5E5 PHYSFS_writeSLE64+0x123125x

  0x0,000,7FF,636,11D,109 PHYSFS_writeSLE64+0x18446744073708596249x

  0x0,000,7FF,636,043,12A PHYSFS_writeSLE64+0x18446744073707703354x

  0x0,000,7FF,636,01F,C4E PHYSFS_writeSLE64+0x18446744073707558750x

  0x0,000,7FF,636,467,115 PHYSFS_writeSLE64+0x2493477x

  0x0,000,7FF,636,207,B10 PHYSFS_writeSLE64+0x5664x

  0x0,000,7FF,B31,027,974 BaseThreadInitThunk+0x20x

  0x0,000,7FF,B31,C9A,271 RtlUserThreadStart+0x33x

E void __cdecl OpenApoc::StateRef<class OpenApoc::Agent>::resolve(void) const: No Agent object matching ID "AGENT_2787" found
  0x0,000,7FF,636,05E,502 +0x140695445038338x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,05E,942 +0x140695445039426x

  0x0,000,7FF,636,045,EA0 +0x140695444938400x

  0x0,000,7FF,636,045,E06 +0x140695444938246x

  0x0,000,7FF,636,0EC,9AE +0x140695445621166x

  0x0,000,7FF,636,278,E17 PHYSFS_writeSLE64+0x469287x

  0x0,000,7FF,636,223,51E PHYSFS_writeSLE64+0x118830x

  0x0,000,7FF,636,221,FE3 PHYSFS_writeSLE64+0x113395x

  0x0,000,7FF,636,224,5E5 PHYSFS_writeSLE64+0x123125x

  0x0,000,7FF,636,11D,109 PHYSFS_writeSLE64+0x18446744073708596249x

  0x0,000,7FF,636,043,12A PHYSFS_writeSLE64+0x18446744073707703354x

  0x0,000,7FF,636,01F,C4E PHYSFS_writeSLE64+0x18446744073707558750x

  0x0,000,7FF,636,467,115 PHYSFS_writeSLE64+0x2493477x

  0x0,000,7FF,636,207,B10 PHYSFS_writeSLE64+0x5664x

  0x0,000,7FF,B31,027,974 BaseThreadInitThunk+0x20x

  0x0,000,7FF,B31,C9A,271 RtlUserThreadStart+0x33x

**Comment by Nekon475** [comment]
W void __cdecl OpenApoc::StateRef<class OpenApoc::ResearchTopic>::resolve(void) const: ResearchTopic object has invalid prefix - expected "RESEARCH_" ID "MANUFACTURE_DISRUPTOR_GUN"

[log.txt](https://github.com/OpenApoc/OpenApoc/files/5748335/log.txt)

[save_345.zip](https://github.com/OpenApoc/OpenApoc/files/5748339/save_345.zip)

**Comment by JonnyH** [comment]
@Nekon475 That issue doesn't seem to be related, so I pulled that out as #970

**Comment by EmeraldSundisk** [comment]
I'm running into an issue a lot like this myself. **I try to unpause the cityscape and it yields the following:**
![waithuh](https://user-images.githubusercontent.com/51142887/130369346-264898d6-adbf-4093-9e6a-56fba638d2bb.png)
![waitwhat](https://user-images.githubusercontent.com/51142887/130369345-c17957d6-d321-46a8-b30a-15ee80ac6f62.png)
**Then the game crashes. There are some things of note, although I'm unsure of their significance:**
-I currently have two bases.
-I've researched Disruptor Guns.
-Just prior to this, I had a base defense mission against the Cult of Sirius.

**In said base defense mission:**
-There were soldier casualties.
-I don't believe any scientists/engineers were killed, but some were injured. A few were directed out of the combat zone and may or may not have been the injured ones.
-It's likely some of the cult members were unconscious as opposed to dead.

[save.zip](https://github.com/OpenApoc/OpenApoc/files/7028119/save.zip)

**Comment by FilmBoy84** [comment]
Should be resolved by recent updates to master for new game starts

To resolve the issues already in this save, decompressing the save file and searching the XML files to remove whole references to "AGENT_11" and "AGENT_43"

**Comment by SaggerBB** [comment]
I've encountered the same error today multiple times. How do I decompress the savegame files to fix it?

**Comment by SaggerBB** [comment]
![error](https://github.com/OpenApoc/OpenApoc/assets/154738360/a9992c58-9c2f-4d3a-9114-adf3d87bb959)

The last time the error occured after loading a game and starting any time. After that, the issue also occured after loading other savegames (from different days of the same campaign)

**Comment by SaggerBB** [comment]
Ah, these are just zip-files. After searching all XML files I couldn't find any Agent_2 related data... so maybe another issue. I try to reproduce it.

**Comment by JonnyH** [comment]
If there is a save that immediately shows the issue after loading and unpausing, that would be pretty handy to see what has a reference.

And hopefully there's a log.txt file (might be the same folder as openapoc.exe) - that should have more info - hopefully exactly what it was trying to do when trying to look at the agent. Posting that and the save may be helpful

**Comment by SaggerBB** [comment]
I couldn't find any log.txt (only readme*.txt)

[save_Spiel 3.zip](https://github.com/OpenApoc/OpenApoc/files/13762077/save_Spiel.3.zip)

But here is the savegame. The issue appears directly after you start any timer.

**Comment by icarus7234** [comment]
I've played across several fresh installs in recent months (casual fan, after all), and AGENT_11 has been the death of many early games - it's still present today, in the current version. Typically this occurs in battles and I reload, but this time it's in the Geoscape and any time I unpause the game crashes to desktop.

Version 20240306. No mods.

![AGENT_11 CRASH](https://github.com/OpenApoc/OpenApoc/assets/5144006/235739b8-b7fb-429e-b74e-bca9d32ae2c8)

[Game 2-7.zip](https://github.com/OpenApoc/OpenApoc/files/14608914/Game.2-7.zip)

**Comment by Kurtsley** [comment]
Do you have a save from earlier in the playthrough? I would like to see who agent 11 was and why they are missing now.

**Comment by Kurtsley** [comment]
Also, did you have any agents die in battle before this error? Did you fire anyone?

**Comment by icarus7234** [comment]
> Do you have a save from earlier in the playthrough? I would like to see who agent 11 was and why they are missing now.

Many people did in fact die, yes. It wasn't going so well! As for firing, at some point earlier on in the save, yes, a few. An assortment of non-combat personal were let go, to thin the numbers out.

I can attach all 7 save files that I have from the current game.

[Game 2 - Saves 1-7.zip](https://github.com/OpenApoc/OpenApoc/files/14609141/Game.2.-.Saves.1-7.zip)

**Comment by Kurtsley** [comment]
Just to make sure, this game was started using a fairly current build of the game correct? There were some changes a couple months back that may  break old games.

**Comment by Kurtsley** [comment]
Agent 11 is a quantum physicist name John Brown. He exists in save 4, but is gone by save 5. I get the same crash loading save 5 after he is gone. Any idea what you did with him?

**Comment by icarus7234** [comment]
> Just to make sure, this game was started using a fairly current build of the game correct? There were some changes a couple months back that may break old games.

Yes, this game was started today on a fresh install that was made yesterday. It's my 2nd game on that install. The first had it's share of crashes, too, but these were usually in battles so I restarted them as mentioned. This is the first that's got me on the Geoscape, and will crash a moment after unpausing.

---

> Agent 11 is a quantum physicist name John Brown. He exists in save 4, but is gone by save 5. I get the same crash loading save 5 after he is gone. Any idea what you did with him?

At some point, I did fire a bunch of non-combatants, correct. It was in response to a base attack where I was caught short and took casualties: with 2 small squads but many non-combatants to manage, I purged any I wasn't using after the battle, but he may well have died in the attack, and I'm not sure which it might be. Either way, I did 'lose' and agent in this case, yes.

**Comment by icarus7234** [comment]
> Agent 11 is a quantum physicist name John Brown. He exists in save 4, but is gone by save 5. I get the same crash loading save 5 after he is gone. Any idea what you did with him?

In save 5 'John Brown' is assigned to a current 'research' project, but not on that project by save 6 - I don't know of a way to tell if this was before or after the base attack, but as there's only 5 'agents' in each research window in save 6, he is either dead or was fired, yes.

**Comment by icarus7234** [comment]
Seems to not be an isolated incident. New game, crashes on un-pausing - Agent_10 missing.

Fully aware of firing many unused Biochemists, Engineers and Physicists this time (low stats on game start, meant buying more later, and eventually purging unused people). Game didn't crash until I quit and came back to reload, now can't unpause without crashing.

[save_Game 4-15 DF 9.zip](https://github.com/OpenApoc/OpenApoc/files/14626034/save_Game.4-15.DF.9.zip) File that crashes.

[save_Game 4-14 DF 8.zip](https://github.com/OpenApoc/OpenApoc/files/14626082/save_Game.4-14.DF.8.zip) Previous file that doesn't crash.


![AGENT_10 CRASH](https://github.com/OpenApoc/OpenApoc/assets/5144006/7e6bdca8-1f6a-4dee-afed-444512dd5411)

**Comment by Kurtsley** [comment]
Can this be easily reproduced from a new game? If so, can I get a step by step method. That would be very helpful.

**Comment by icarus7234** [comment]
[It has happened in another game since this post, as stated here.](https://github.com/OpenApoc/OpenApoc/issues/691#issuecomment-2002291780)

In this case I'm very much aware of buying new technicians in each category to replace lower skilled ones, changing them over during an active research, then some time later doing a mass firing of several technicians from each category all at once. I've kept playing without issue until closing the game, and reloading, when the crash then occurs.

These people are all on base, and not in transfer or still arriving. They were manually swapped out, then fired later on, from memory (games a day or so old).

---

Started a new game before posting and tried a few quick hirings and firings, with active and inactive research, saving and reloading. It doesn't appear to replicate so easily from the start of the game right now with a fresh file.
