### ISSUE TITLE
Two gateways in UFOs so its relatively safe to go out safe for aliens 

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#698]
Two gateways in UFOs so its relatively safe to go out safe for aliens and all this and so that all the shots of agents sitting opposite the entrance do not fly inside the UFO, killing everything in its path

Два шлюза в НЛО, так что относительно безопасно инопланетяне могли выходить на улицу, и чтобы все выстрелы агентов, сидящих напротив входа, не летали внутрь НЛО, убивая все на своем пути

![image](https://user-images.githubusercontent.com/11581207/107852356-fbefcf80-6e18-11eb-9e52-e5ba01c5cf0d.png)

**Comment by Paddywhacker** [comment]
You mean, like an air lock?

**Comment by makus82** [comment]
yep

**Comment by makus82** [comment]
moved to Issue #941
