### ISSUE TITLE
Aliens should have own smoke grenade and not human)

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#699]
Aliens should have own smoke grenade and not human)

**Comment by Paddywhacker** [comment]
Another thing to research.
<sigh>

**Comment by makus82** [comment]
![mod_grenade](https://user-images.githubusercontent.com/11581207/89066646-7faf0680-d376-11ea-9894-91042bcaf321.png)
here some concept and i close this for later times =]

**Comment by makus82** [comment]
![grenadepop_sprite](https://user-images.githubusercontent.com/11581207/89118832-a45bc900-d4b1-11ea-9b2f-2298dc432eae.png)
sprite

**Comment by FilmBoy84** [comment]
You can already add this as a mod

Add the weapon under agent_equipment.xml
Add an appropriate entry (as per other alien equipment) under economy.xml
Add the grenade to the alien equipment spawns under difficulty0/1/2/3/4 equipment_sets_by_score.xml

It'll work straight away

You can also, optionally, add research and UFOpaedia entries for them in the relevant XML

**Comment by makus82** [comment]
that looking something like a start of great guide)
