### ISSUE TITLE
Suggestion: Fast-placing items on equip screen.

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#701]
The idea is when you have a piece of equipment selected, for instance, ammo, if you hold a key down (Alt?) and click to place the item in a slot, another of that same items gets placed into the cursor holder. This would allow for rapid placement of items on an agent. If there are no more of the item, then nothing happens after it gets placed. There could potentially be the quantity of that item left next to its icon so the player would more easily be able to see how many are left. This could be an alternative to making multiple templates for minor changes.

**Comment by makus82** [comment]
Just leave it here for others who can dont know

Agent Equipment:
* Usual selection controls apply, with option to de-select with right click as well
- [Shift] makes item auto-equip into first available slot, or auto-remove to base stores / ground
- [Ctrl] makes you remove clip when clicking on weapon
**- [1]...[0] applies equipment template to every selected agent**
**- [Ctrl] + [1]...[0] remembers current agent's equipment set as a template**

**Comment by makus82** [comment]
moved to Issue #941
