### ISSUE TITLE
Critical game error when abort rescue mission while vehicle are on fly (WTF, no player units found?)

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#713]
Right after new game start and first rescue mission alert I sent Valkyrie with agents to a mission. Agent assigned to a vehicle in the alert dialog window.

When I press "return to base" button to abort current vehicle assignment its shows "start mission" dialog with 0 agents assigned to a mission in building and mission starts when press "OK/Yes" dialog option.

Mission starts with no agents and error message pops up: "WTF, no player units found?"

After close error message dialog with "OK" option mission starts with UI and blank tactical view.

I attach gdb logs

[gdb_log.txt](https://github.com/OpenApoc/OpenApoc/files/3562245/gdb_log.txt)

**Comment by Atrosha** [comment]
Video to reproduce https://youtu.be/VqLGYlnoD7w

**Comment by makus82** [comment]
its last build?

**Comment by Atrosha** [comment]
Latest GitHub "master".

**Comment by Quickmind01** [comment]
I just replicated this on stream. This doesn't have to be a new game. When going to an alert mission, if you cancel the craft's route, it acts as if the craft made it to the mission and asks if you want to start with 0 units. This happens in build OpenApoc-v0.1-606-gd53c36dc.

**Comment by Atrosha** [comment]
@Quickmind01 can you add your issue's id to this report or mention it in your by add #713 in reply?
I can't find it in issues section.

**Comment by Quickmind01** [comment]
Do you want me to make a new issue for this? I added to this issue so as not to make a duplicate.

**Comment by Atrosha** [comment]
Of course not if you didn't bugreport earlier. But if you did mention this one in yours, plz.
