### ISSUE TITLE
[Battlescape] Go To Location and Restart Mission Loop and CTD

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#743]
Watch the log on the left, a unit somewhere on the map ends up stuck in a loop of trying to move to an unattainable location which leads to a CTD

https://youtu.be/3ZZp3vNLa7o

_May also include issues such as #635 in other instances_

**Comment by Quickmind01** [comment]
I am finding a similar issue in the Battleship mission. BATTLEUNIT_2925 and 2926 have both caused this.
[saves.zip](https://github.com/OpenApoc/OpenApoc/files/3612787/saves.zip)

The battleship.save file is closer to when unit 2926 has the infinite loop. 2925 seemed to have it right away in the other file, though killing the Psimorph seemed to fix it.

This is using OpenApoc-v0.2.0.2-16-g2f96387e and V7.1 EWM.

**Comment by emptyVoid** [comment]
Please close the issue (I've messed a bit with the issue closing pattern in PR).

**Comment by JonnyH** [comment]
I tend not to use the automatic "closes #number" thing in github, as I normally want the resulting build to be tested that it actually solves the original issue submitted - sometimes I /think/ I've solved an issue, but it only ends up being one possible way that issue can be caused, and didn't actually solve the original problem :)

But I suppose that does mean that the lack of reproduce-able testing would mean lots of issues may hang around in that zombie state of "probably fixed but still open", so a bit of fudging is needed.
