### ISSUE TITLE
Return to base command bugged in Alien Dimension

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#752]
When using the Return to Base command on your craft while in the alien dimension, it appears to tell them to go to some location to the left of the map. I did not follow the craft all the way to their destination, but they clearly weren't going back through the gates. I had to manually command them to go to the gates.

This was in build OpenApoc-v0.2.0.2-12-g8f8b94c1 with V6.1 EWM.

**Comment by FilmBoy84** [comment]
Second to this (and maybe the cause) there is a secret X-COM base in the Alien Dimension... This should not be there... Or at least not used as a base...

**Comment by Quickmind01** [comment]
Please see this video for demonstration on this issue: https://youtu.be/wp2x2ejY3eo
