### ISSUE TITLE
Organisation specific colored vehicles

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#774]
I would like an extra option that makes color differentiation in organizations vehicles. For example, only X-Com vehicles should be red, the other organizations could have any other colored vehicles. The police or Megapol should be blue like they are in vanilla, and the taxis should be yellow as in vanilla, but the more generic organizations should have a different color scheme than red, blue or yellow. Maybe grey or black?! You guys could probably find a suiting color for the other organizations in OpenApoc. I trust you guys can do it, it would be easier to differentiate between X-Com vehicles and other organizations vehicles. 🚗

**Comment by XCOM-HUB** [comment]
After watching through QuickMinds Let's Play OpenAPOC Superhuman - 1 video on YouTube, I realize making X-Coms Vehicles only red is a bad idea. Some Battlescape maps have a lot of red vehicles in them and that would make them X-Coms vehicles which wouldn't be logical. It's better and easier if you could have an option to choose a different color palette for all of X-Coms vehicles. That way the other organizations can keep their red coloured vehicles. 🚗

**Comment by makus82** [comment]
=] then X-Com can be like in SWAT colors black or haki colors 
and to keep tradition) police can be white or blue

**Comment by Atrosha** [comment]
Please, consider and this FR to insert in #941 roadmap.

**Comment by FilmBoy84** [comment]
@Atrosha I've added as requested to #941 

However, this is going to require a serious amount of re-spriting and changes to the code to support. Even if we adopt a palette shift method to save having to make sprites for each organisation; that's still going to be a massive amount of work.There are, literally, hundreds of vehicle sprites that would need updating as well as the code to support it..

That said, we need to re-do all the OG vehicle sprites at some point anyway; so could be another good excuse to do this 😀

**Comment by FilmBoy84** [comment]
Moved to Issue #941 so closing here to clear up the tracker.

**Comment by Artytoo** [comment]
With todays technology AI art would be able to colourize entire sprite sheets at a whim.

"Lunapic" is going to come into the conversation because of the amount of platforms it works across.

[Coding]
Do you want coloured fields?
Using gamma changes.
Using colour tint or shifts.

[Colour Splitting]
CYMK colour splitting.
RGB colour splitting.

Using "hue" changes.
