### ISSUE TITLE
Please, a utility to speed up reporting issues.

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#775]
Please produce a utility based, say, on the unix tail command that combines the last, say 500 lines of the log file with a saved game and any other files required and zips them up for easy upload to this forum.

Trying to edit a multi-megabyte file with notepad++ is difficult, and this would speed up the whole process.

**Comment by FilmBoy84** [comment]
Agreed, this would be useful if implemented, thanks for the suggestion paddywhacker

**Comment by makus82** [comment]
moved to Issue #941

**Comment by makus82** [comment]
Here some examples from gw2
![image](https://user-images.githubusercontent.com/11581207/110789344-6fe69180-8278-11eb-98b3-f6f924901cdd.png)
![image](https://user-images.githubusercontent.com/11581207/110789459-9278aa80-8278-11eb-9d49-808d5ac7ccd6.png)
![image](https://user-images.githubusercontent.com/11581207/110789524-a58b7a80-8278-11eb-9bf7-1204f9e145f0.png)
