### ISSUE TITLE
[interface] "Project too large", etc... message dialogues rises twice

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#786]
When I try to start construction of large item in small workshop the error message dialogue shows twice.

It's non critical interface bug.

**Comment by Atrosha** [comment]
Change research selection rises twice when click on child object of research list (labels, progress bars)

I think it's a bug with child control objects in `research_list`

**Comment by Atrosha** [comment]
Oh, no! @JonnyH plz open this issue. My PR doesn't fixing it.
Seems GitHub closes automatically 'coz it mentioned in PR.

**Comment by JonnyH** [comment]
Yeah, this is why I tend not to mention issue #numbers in the git commit message itself, but as a comment on github on that PR.
