### ISSUE TITLE
Game crashing when selecting squad

### ISSUE THREAD

**Issue by taehyoung1301** [OpenApoc/OpenApoc#801]
In real time battle selecting squad crashes the game.
Also, it was a second battle, in the first battle there was no errors.
[log.txt](https://github.com/OpenApoc/OpenApoc/files/3991006/log.txt)

**Comment by makus82** [comment]
Ty @taehyoung1301 save before bug i think will be useful here also

**Comment by taehyoung1301** [comment]
i wasn't able to upload it with .save so i zipped it.
[save_Good battle.zip](https://github.com/OpenApoc/OpenApoc/files/3991444/save_Good.battle.zip)

**Comment by makus82** [comment]
ofc that is right way, ty

**Comment by JonnyH** [comment]
So this crashes in "BattleView::createMotionInfo(BattleScanner &scanner)", it seems like we've somehow ended up with an invalid BattleScanner object here, with a NULL "scanner.holder.id"

**Comment by FilmBoy84** [comment]
Issue found and resolved by JonnyH and emptyVoid
Thanks both of you

**Comment by emptyVoid** [comment]
As I've mentioned in #823 -- the fix is not retroactive.

**Comment by makus82** [comment]
[save_newnew.zip](https://github.com/OpenApoc/OpenApoc/files/4680975/save_newnew.zip)
ok yes ur right so i load this game then just start time and wait till all enemies die out and all 4 agents out to cityscape and then start new mission in new building (CoS) and yes there no bug.

but intresting thing that after im finish that bug mission at cityscape whole CoS building go demolish to the ground.. how is this possible? is OA now end all raids this way?

**Comment by makus82** [comment]
[save_new4.zip](https://github.com/OpenApoc/OpenApoc/files/4680996/save_new4.zip)
here save right after bugged mission

**Comment by emptyVoid** [comment]
There's a setting `Successful raid collapses building` in `More options` which is enabled by default:
https://github.com/OpenApoc/OpenApoc/blob/53c13b59cb6d9d898ce42e223126ae0cc85b4429/framework/options.cpp#L373-L374

**Comment by makus82** [comment]
Dont notice that before ... thats radical way to prevent player raidspam building....
