### ISSUE TITLE
Make all ingame texts translateable - extract to files

### ISSUE THREAD

**Issue by andersand** [OpenApoc/OpenApoc#803]
"Somehow", he said.

**Comment by andersand** [comment]
JonnyH wrote:

Mark which strings are translate-able in the GameState, so we can extract them for the .po files for transifex

**Comment by andersand** [comment]
Done a little digging around in the data files and it seems it would be difficult to do something too automatic with this without risk of breaking the game. Seeing as the same value structures that sometimes store traslatable text also can hold special values. Like formatting rules or similar

**Comment by makus82** [comment]
we have most languages here https://www.transifex.com/x-com-apocalypse/apocalypse/
not all yet strings work or turn to translate-able but its the goal already

**Comment by makus82** [comment]
1. Translate/improve needed strings or make request for new language
2. Download your language file (wich .po ext.), then put .po file to the openapoc\data\languages\ by replace existing (or get it in game folder)
3. Then go to www.po2mo.net and convert .po file, then donload it and replace file in (for example) openapoc\data\languages\ru_RU\LC_MESSAGES, only choose your language
4. Now you will see you changes in the game

**Comment by makus82** [comment]
all answers was done im close it @andersand
