### ISSUE TITLE
Move main menu options from ingame to lanucher

### ISSUE THREAD

**Issue by andersand** [OpenApoc/OpenApoc#804]

**Comment by JonnyH** [comment]
I believe the 'main menu options' is just a dumb dump of all the options possible - with no thought on how they should be displayed or changed, or even if it makes sense for them to be displayed and changed, or really some internal-only debugging value that likely shouldn't be shown to the user, or something that probably should be in a mod (I'd see that as anything that actually affects gameplay).

**Comment by andersand** [comment]
maybe represent options with an xml structure then to categories etc?

**Comment by makus82** [comment]
moved to Issue #941
