### ISSUE TITLE
Cant capture ufos

### ISSUE THREAD

**Issue by Samspamman** [OpenApoc/OpenApoc#818]
When I send a team to a scout ufo they dont bring it back to the base the vehicle just sits above it. I am using a hovercar and have the bio transport module on said hovercar

**Comment by JonnyH** [comment]
How are you selecting to recover the UFO? I think we may use the 'attack vehicle' button, rather than the OG 'go to location'

**Comment by makus82** [comment]
need to check it out in OG

**Comment by makus82** [comment]
In OG if you have at hovercar agents you can recover UFO scouts even with no modules on it

**Comment by FilmBoy84** [comment]
Can confirm it works in OpenApoc and OG if you attack vehicle to board a downed UFO

Closing issue as nothing from the OP on it being resolved and i cannot replicate the problem... All appears as it should do...
