### ISSUE TITLE
[MOD] Put unique agents paperdoll with they faces over standart in eqipment screen (like in Xcom1)

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#820]
So this is mod suggestion from  Jan Sakra from our FB page
pls leave here your comments, suggestions, or your paperdoll art work for in mod use
![agent_papperdol](https://user-images.githubusercontent.com/11581207/77577885-43f3c400-6ee0-11ea-9b8d-0751bde817f8.png)

**Comment by makus82** [comment]
will close this to left this cool idea for later)

**Comment by FilmBoy84** [comment]
Can you move this to forums?
Always love your equip screen photoshops
And want to see lots of the features implemented :)
