### ISSUE TITLE
Time boost freezes, vehicles in the loop 

### ISSUE THREAD

**Issue by Rezistor87** [OpenApoc/OpenApoc#824]
I can't continue playing, time boost is stuck and log file is filled with a infinite loop (once the file even had 800mb).

Problem is above Govrm. apartments with

*Construction vehicle
*Rescue Transport

If I shoot them down, the game continues, time boost is   ##ok for a moment.
But there will be another and another and another.

(Sry for my ENG)

![image](https://user-images.githubusercontent.com/63288674/78876037-0e59e980-7a4f-11ea-9023-794d8d4f1742.png)

`W bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): CLICKED VEHICLE Construction Vehicle 84 at {26.0083,79.992,6.5}
W bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission GotoLocation {26,80,2}
W bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission RecoverVehicle VEHICLE_13528
W bool __cdecl OpenApoc::CityView::handleMouseDown(class OpenApoc::Event *): Mission GotoBuilding BUILDING_PARALLAX_TOWER
I void __cdecl OpenApoc::VehicleMission::start(class OpenApoc::GameState &,class OpenApoc::Vehicle &): Vehicle mission AttackVehicle VEHICLE_16734 checking state
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::TileMap::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,int,const class OpenApoc::CanEnterTileHelper &,bool,bool,bool,bool,float *,float): Trying to route from {25,79,3} to {26,79,3}
I void __cdecl OpenApoc::VehicleMission::start(class OpenApoc::GameState &,class OpenApoc::Vehicle &): Vehicle mission AttackVehicle VEHICLE_16734 checking state
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::TileMap::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,int,const class OpenApoc::CanEnterTileHelper &,bool,bool,bool,bool,float *,float): Trying to route from {25,80,3} to {26,79,3}
I bool __cdecl OpenApoc::Vehicle::popFinishedMissions(class OpenApoc::GameState &): Vehicle Construction Vehicle 82 mission "RestartNextMission" finished
I bool __cdecl OpenApoc::Vehicle::popFinishedMissions(class OpenApoc::GameState &): Vehicle Construction Vehicle 82 mission "GotoLocation {86,25,2}" starting
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::TileMap::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,int,const class OpenApoc::CanEnterTileHelper &,bool,bool,bool,bool,float *,float): Trying to route from {26,80,1} to {86,25,2}
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::TileMap::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,int,const class OpenApoc::CanEnterTileHelper &,bool,bool,bool,bool,float *,float): No more tiles to expand after 2 iterations
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::TileMap::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,int,const class OpenApoc::CanEnterTileHelper &,bool,bool,bool,bool,float *,float): Surprisingly, no nodes to expand! Closest path ends at {26,80,1}
I bool __cdecl OpenApoc::Vehicle::popFinishedMissions(class OpenApoc::GameState &): Vehicle Police Car 14 mission "RestartNextMission" finished
I bool __cdecl OpenApoc::Vehicle::popFinishedMissions(class OpenApoc::GameState &): Vehicle Police Car 14 mission "GotoLocation {26,40,1}" starting
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::City::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,const class OpenApoc::GroundVehicleTileHelper &,bool,bool,bool,bool): Trying to route from rs 653 to rs 48
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::City::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,const class OpenApoc::GroundVehicleTileHelper &,bool,bool,bool,bool): No more road segments to expand after 3 iterations
I class std::list<struct glm::vec<3,int,0>,class std::allocator<struct glm::vec<3,int,0> > > __cdecl OpenApoc::City::findShortestPath(struct glm::vec<3,int,0>,struct glm::vec<3,int,0>,const class OpenApoc::GroundVehicleTileHelper &,bool,bool,bool,bool): Surprisingly, no nodes to expand! Closest path ends at 653`

**Comment by makus82** [comment]
hey @Rezistor87 great report =]
uw try to save and then reopen Openapoc and load?
u can also upload here save in zip

**Comment by Rezistor87** [comment]
[save_4D.zip](https://github.com/OpenApoc/OpenApoc/files/4456508/save_4D.zip)

Here it is

**Comment by makus82** [comment]
hm yes log file fills fast i get 80mb till test 
also tanks somehow  cant find path to ufo

![image](https://user-images.githubusercontent.com/11581207/83320272-81612e80-a24e-11ea-8702-c8f041f7686f.png)

**Comment by FilmBoy84** [comment]
This appears resolved most likely by #1495 and other recent merges
