### ISSUE TITLE
ID error

### ISSUE THREAD

**Issue by Samspamman** [OpenApoc/OpenApoc#850]
I keep getting a error saying "E void __cdecl OpenApoc::StateRef<class OpenApoc::Vehicle>::resolve(void) const No Vehicle object matching ID "VEHICLE_31" found"

**Comment by Atrosha** [comment]
Please give more detailed report. Attach file `log.txt` from game folder, savegame file from `saves`, Add description and steps to reproduce. Take backtrace if you can.

**Comment by FilmBoy84** [comment]
As well as a save and log for us as Atrosha has requested

For anyone who picks this up please also note issues #333 which relates to UFOs

Also, similar errors for scientists in #368 #505 and affecting regular agents #691

**Comment by Samspamman** [comment]
Its the latest build
[log.txt](https://github.com/OpenApoc/OpenApoc/files/4568689/log.txt)
I'm not sure how to reproduce it
[save_Apoc.zip](https://github.com/OpenApoc/OpenApoc/files/4568697/save_Apoc.zip)
How do I backtrace ?

**Comment by makus82** [comment]
@Samspamman ty for detailed report =]

**Comment by Samspamman** [comment]
Will I need to use a new save if the issue is fixed?

**Comment by FilmBoy84** [comment]
When the error is fixed, generally you should start a new game as any bug reports you make from then on won't be muddied by previous issues

However, if you want to try with the old save you are welcome to, we would just not be able to provide further support until a new game was started to confirm the error

**Comment by emptyVoid** [comment]
@Samspamman, have you by chance started this game with some earlier build?

There's a construction vehicle being carried by some other vehicle according to save game, though the carrier is somehow missing from the save game.

```xml
	<entry>
		<key>VEHICLE_239</key>
		<value>
			<type>VEHICLETYPE_CONSTRUCTION_VEHICLE</type>
			<owner>ORG_GOVERNMENT</owner>
			<name>Construction Vehicle 23</name>
			...
			<city>CITYMAP_HUMAN</city>
			<position>
				<x>100.5</x>
				<y>44.5</y>
				<z>1.49378872</z>
			</position>
			<goalPosition>
				<x>100.5</x>
				<y>44.5</y>
				<z>1.99378872</z>
			</goalPosition>
                        ...
			<facing>4.71238899</facing>
			<direction>W</direction>
			<shadowDirection>W</shadowDirection>
			<health>6</health>
			<crashed>true</crashed>
			<fuelSpentTicks>32</fuelSpentTicks>
			<ticksAutoActionAvailable>428328036</ticksAutoActionAvailable>
			<homeBuilding>BUILDING_BABYLON_APARTMENTS</homeBuilding>
			<carriedByVehicle>VEHICLE_31</carriedByVehicle>
		</value>
	</entry>
```

**Comment by emptyVoid** [comment]
I've managed to reproduce the issue -- it happens if the carrier vehicle gets utterly destroyed (e.g. using [Ctrl]+[Alt]+[Shift]+[Right Click]) , the carried vehicle in turn gets stuck hanging in the air; and any save after the commotion becomes invalid.

**Comment by FilmBoy84** [comment]
Many thanks emptyVoid

Once the build at 
https://ci.appveyor.com/project/OpenApoc/openapoc/builds/32615232/artifacts
Is finished (appearing green) @Samspamman you should be able to update to this OpenApoc version and continue play

**Comment by Samspamman** [comment]
Ok thanks a ton.

**Comment by FilmBoy84** [comment]
Does it also happen with a new game @Samspamman

**Comment by Samspamman** [comment]
No just on the old one, but I've started a new one
