### ISSUE TITLE
[feature request] Give more realistic behavior to Civilians on Battlescape (Militia/Guards)

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#864]
Add to batllescape another faction - Militia - that always friendly to Civilians and lead them, but can attack aliens or x-com agents  or both, depends on relations. They goal and regular behavior will be defense the Civilians and convoy them from site to exit map and eliminate other hostile factions after evacuation.

It will be nice to give Militia poor starting equipment depends on organization they belong. E.g. policemen from Megapol buildings or security agents from Gravball stadium or from Mutants factories.

How to calculate mission overall score by casualties in militia troops:
1. like regular Civilians (**-** to score anyway).
2. by relations with aliens (**+** to score in case if relations with aliens are friendly).

**Comment by FilmBoy84** [comment]
You should already be able to make a start on doing this as a mod as we already have rudimentary support for new factions and unit types appearing on maps

VoidDweller on discord has already had some success adding new organisations over at discord, whilst he isn't around much any more, it might be worth sending him a private message?

You need to specify the new organisation in the relevant XML for gamestate
You need to specify the buildings that the organisation owns at each difficulty (until we have new maps this means removing ownership of at least one building in each map from another organisation)
You need to specify what units that organisation can spawn in both cityscape and tac missions
You need to specify which maps the units for that organisation can appear in
You need a UFOPaedia Organisation entry
You need funding for the Organisation to be specified
You need all relevent icons and sprites for the cityscape

To have the organisation appear on maps where they do not have ownership, you also need to specify a new guard type, in addition to the guards from other organisations, that has permission to spawn on all maps you want militia to spawn on

**Comment by Atrosha** [comment]
Militia trops belongs to the same organization when civilians are in which building alien infiltration mission is.

**Comment by FilmBoy84** [comment]
It should be possible to mod the civilian organisation to spawn guards then?

Take a look at the <guard_types_reinforcements> and <guard_types_human> keys for the civilian organisation in organisations.xml within the gamestate

This should allow you to spawn guard units with civilians if needed

AGENTTYPE_BUILDING_SECURITY is a good unit to use until you create one of your own (with the appropriate sprites and weapons)

**Comment by FilmBoy84** [comment]
If you put together a mod i'm more than happy to help with it where needed

My main focus at the moment is the EWM and HeadGrowsBack's wonderful new aliens, but more than happy to help you too where possible

**Comment by Atrosha** [comment]
I found the mention of `guard_type_reinforcements` in `battle.cpp`

https://github.com/OpenApoc/OpenApoc/blob/af5d180742778b415a6c386e10d7cf2cc713cf24/game/state/battle/battle.cpp#L2141

**Comment by FilmBoy84** [comment]
The original game had support for civilian guards/militia, as does openapoc :)

Currently you should not need to change code to add them so you should not need to use the source code or git repository to make any changes

Making a mod that modifies organisations.xml under `gamestate_patch` with a appropriately modified organisations.xml as i suggested above should be enough

**Comment by Atrosha** [comment]
> The original game had support for civilian guards/militia, as does openapoc :)

Hm... Okeeeey... things just doesn't implemented yet in both OG and OA.

**Comment by FilmBoy84** [comment]
Indeed, for the OG, you enable the unhooked functions with Apoc'd or Hex editor

OpenApoc does spawn them already under certain conditions (for example at corporate HQs when the aliens are hostile to both the organisation and X-COM)

Adding them to civilian organisation as well is fairly simple

**Comment by FilmBoy84** [comment]
In fact, J'Ordos' A-Patcher will also enable guards under OG as another route :)

http://www.strategycore.co.uk/files/a-patcher/

If you really want, i can make a basic mod structure that you can tweak in the next few days for a militia? But it will take me a little while

**Comment by Atrosha** [comment]
"It's nice to be important, but it's more important to be nice."

If modding part is simple, don't take it on.
It's need to advance of OA game mechanics (AI/behavior) to fit that anyway.

**Comment by FilmBoy84** [comment]
You've actually got me interested in fooling around with it now ha ha ha :D

Agreed, the AI does need some improvement, but we do at least have the UnitAI thread over at the forums for documenting how the final AI should work from an end-user view of things
http://openapoc.org/threads/task-unit-behavior.185/

**Comment by Atrosha** [comment]
Hehe... For now we can just add guards to a battlefield and see what happened. "Kucha Mala!" Rough-and-tumble!

**Comment by JonnyH** [comment]
Yes, I'd see this as a good example on something a mod should be able to do - and if that's not possible, change things so it becomes possible with a mod.

If the end result is to make the 'default' AI of each organisation modifiable, that's probably the real "issue" here. And less hardcoded stuff is better :)

**Comment by Atrosha** [comment]
I suggest dividing unit behavior not by organization, but by combat role: civilian, x-com agent, spitter, multiworm, guarding security, etc...

And make them moddable looking good. Also it will be nice to have an option to add combat role by mod.

**Comment by XCOM-HUB** [comment]
I always imagined the slums in the game to be full of gang members with guns and knives, shooting and stabbing at both aliens and X-Com agents alike. It would have been a really nice implementation to see hostile civilians/gang members whenever you do a mission in the slum areas. It adds another layer of suspense whenever you have to go alien-hunting in the ghetto 😄

**Comment by Atrosha** [comment]
@XCOM-HUB noice. With FilmBoy we imagined you suggestion and gang fights between criminal factions and Megapol raids on a hood with 50/25/25 chances. Small business is left - implement this in as a mod.

**Comment by XCOM-HUB** [comment]
Yes, please do! Just as the other organizations have security guards, the slums owned by criminal factions such as Diablo and Psyke should have gang members that kind of work the same way as security guards in law-abiding organizations. The gang members should, of course, be more aggressive than the law-abiding security guards. I really hope this will be implemented in OpenApoc.

**Comment by Atrosha** [comment]
Please, consider this FR to insert in #941 roadmap.

**Comment by FilmBoy84** [comment]
@Atrosha Updated as requested in #941
