### ISSUE TITLE
Cannot research alien buildings

### ISSUE THREAD

**Issue by Samspamman** [OpenApoc/OpenApoc#865]
I send the probe into one of the buildings and press the alien button but I get an error.
It isn't major since it doesn't crash my game but prevents me from winning the game.

E class std::shared_ptr<class OpenApoc::ResearchTopic> __cdecl OpenApoc::StateObject<class OpenApoc::ResearchTopic>::get(const class OpenApoc::GameState &,const class OpenApoc::UString &) No research topic matching ID "RESEARCH_UNLOCK_ALIEN_BUILDING_0"

**Comment by FilmBoy84** [comment]
Good catch, whilst the other buildings are labelled `RESEARCH_ALIEN_BUILDING_x` where `x` is a number

The entry for the first building is `RESEARCH_ALIEN_BUILDING`

Bumping to confirmed/validated status :)

**Comment by FilmBoy84** [comment]
It would probably be wise to make the research entry `RESEARCH_ALIEN_BUILDING_0` rather than change the game to look for `RESEARCH_ALIEN_BUILDING` simply so all entries conform to the same naming structure

**Comment by emptyVoid** [comment]
Can any of you attach a save game please?

**Comment by Samspamman** [comment]
[save_Better save - Copy.zip](https://github.com/OpenApoc/OpenApoc/files/4608189/save_Better.save.-.Copy.zip)
