### ISSUE TITLE
[MOD concept] Diversity: UFO crash missions

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#871]
### **Pls feel free to add more ideas to this concept in comments below =]**

![ufocrash](https://user-images.githubusercontent.com/11581207/82105079-1f6ada00-9722-11ea-898a-e5f9df047dbf.gif)

# == ██☰ UFO crash missions ==
 **Ⓜ Crash clearing missions can be random timers and triggers that can stop the timer. For instance:**

0. There may be several timers and some hidden ones, and some timers will need a trigger for it to appear.
1.  Kill all aliens
2.  Kill all Psimorph or Micronoid Aggregate or both because they increase the strength of the psi field (the psi field exhausts and lowers morale so Stamina and Bravery noticeably sag, first Stamina and then Bravery and Accuracy.)
3.  Capture the UFO control room and Destroy the UFO control system.
4.  At least 3 agents must penetrate the first level of UFOs and hold it.

**If the timer does not stop the mission will be:**
6.  failed and the UFO will fly away.
7.  The strength of the psi alien field intensify
8.  Aliens will begin a massive assault.
9.  is complicated by the arriving gangs of marauders.
10.  complicated by the arising cultists of Sirius.

 **Types of missions UFO crash should be more diverse, for example:**

1.  Landing a damaged ship is a very difficult task and sometimes a UFO can simply explode without coping with the landing (leaving nothing).
2.  A damaged UFO that has landed can be destroyed by the organization’s ship next to which the UFO fell.
3.  After an air battle and an emergency landing, the corpses of aliens who died during the air battle and landing scattered inside the UFO should remain (most aliens are alive).
4.  Ⓜ It may happen that a UFO will be visually badly damaged, and all that you find is a couple of units of unconscious survivors and a lot of corpses, or all will be dead.
5.  It may happen that it will be impossible to recover the UFO and the aliens will scatter into the nearest buildings, the UFO will remain empty or there will be only a few spitters and multiworms.
6.  Ⓜ Arriving on a mission to crash UFOs in slums, we can meet a team of numerous marauders of gang members (who will take aliens in number and leave a lot of corpses) who have already joined the battle from criminal organizations wishing to get alien technology, they can already be outside UFOs and kill several aliens, or already inside the UFOs and kill all aliens and share the prey (Use the weapons of aliens). It's up to you to either kill them or fly away.
7.  Ⓜ 2 criminal gangs fighting among themselves or a police squad pursuing a criminal gang may also encounter. Gang members attack in groups of 8-20 - Osiron groups are the largest, Psyke groups are the smallest.
8.  Ⓜ If a UFO crashed near an important public building on a mission, you will find the Security Guard squad holding back the alien forces from spreading.
9.  Ⓜ Arriving on a mission, we can meet the members of the Cult of Sirius who flew in hoping to make contact and help the aliens. It's not for nothing that UFOpaedia says "This represents a significant threat to X-COM because the cultists will do anything to assist the Aliens in their purpose, whatever that might be." Aliens will infect micronoids and supply the cultists with their weapons and will use them as cannon fodder. Cult members fight in groups of around 10.
10.  Ⓜ On a downed UFO, there may be sectoids for the rescue of which points will be awarded.
11.  Ⓜ On a downed UFO, there may be people captured from neighboring buildings for food and for the salvation of which points will be awarded.
12.  Ⓜ On the mission, there may simply be armed civilians belonging to some unregistered movements and not part of any corporations that are fighting against the total control of corporations (as private organizations, elevating a person over a person).
13. Next to the crashed UFO may appear a mission where aliens from UFO storm the building and security reflects the attack.
14. Around the crashed UFO can form dangerous abnormal zones (fire tornadoes, poison clouds, smoke, explosions) due to incorrect operation of the damaged ship.
15. UFO casing can be home to small insect-like creatures (eg Skincrawlers  or Swarm) that mend the casing and can be dangerous to humans by eating or replacing flesh.
16. Each crew of a UFO ship (types 3-7) can have 1-2 Micronoid Aggregate.
17. Each UFO crew (types 3-7) can have 2-6 Micronoid Headwrappers or Micronoid Mentor.
18. Micronoid Headwrappers or Micronoid Mentor are 1/6 Micronoid Aggregate which are located on the head of other aliens and can carry out psi control of both agents and their carriers.
19.  A combination of different types of the above changes.

# RU translation (original)

== ██☰ Миссии крушения НЛО==
 **Ⓜ У миссий по зачистке крушений могут быть случайные таймеры и триггеры которые смогут остановить таймер. Например:** 

0. Может быть несколько таймеров и некоторые скрытые и некоторым таймерам нужен будет триггер чтобы он появился.
1.  Убить всех пришельцев 
2.  Убить всех Psimorph или Micronoid Aggregate или обоих потому что они нагнетают силу пси-поля (пси-поле выматывает и сильнее понижает мораль поэтому Stamina and Bravery ощутимо проседают, сначала Stamina а после Bravery and Accuracy.)
3.  Захватить комнату управления НЛО и Разрушить систему управления НЛО.
4.  На первый уровень НЛО должны проникнуть минимум 3 агента и удерживать его. 

**Если таймер не остановить миссия будет:**
6.  провалена и НЛО улетит. 
7.  Сила Пси поля пришельцев усилиться
8.  Инопланетяне начнут массированный штурм.
9.  усложнена прилетевшими бандами мародеров.
10.  усложнена прилетевшими культистами Сириуса.

  **Типы миссий Крушение НЛО должно быть более разнообразные, например:** 
1.  Посадка поврежденного корабля очень сложная задача и иногда НЛО может просто взорваться не справившись с посадкой (ничего не оставив).
2.  Поврежденное НЛО которое приземлилось может быть уничтожено кораблем организации рядом с которым упало НЛО.
3.  После воздушного боя и аварийной посадки должно остаться трупы пришельцев, умерших во время воздушного боя и посадки, разбросанных внутри НЛО (большая часть инопланетян жива).
4.  Ⓜ Может случится так что НЛО будет визуально сильно повреждено, и все что вы найдете пару единиц выживших без сознания и масса трупов или все будут мертвы.
5.  Может случится так что НЛО будет уже невозможно восстановить и пришельцы разбегутся в ближайшие здания, НЛО останется пустое или будут только несколько спиттеров и мультичервей.
6.  Ⓜ Прибыв на миссию крушения НЛО в трущобах мы можем встретить уже вступивших в бой команду многочисленных мародеров членов банд (которые будут брать инопланетян числом и оставят после себя много трупов) из преступных организаций, желающих заполучить инопланетными технологиями, они уже могут быть либо снаружи НЛО и убить несколько инопланетян , либо уже внутри НЛО и убить всех инопланетян и делить добычу (Использовать оружие инопланетян). Вам решать, либо убить их либо улететь. 
7.  Ⓜ Так же могут столкнуться 2 преступные группировки сражающиеся между собой или отряд полиции преследующая преступную шайку. Gang members attack in groups of 8-20 - Osiron groups are the largest, Psyke groups are the smallest.
8.  Ⓜ Если НЛО разбилось рядом с важным государственным зданием на миссии вы обнаружите отряд Security Guard сдерживающие силы пришельцев от распространения.
9.  Ⓜ Прибыв на миссию мы можем встретить членов Культа Сириуса которые прилетели в надежде вступить в контакт и оказать помощь инопланетянам. Ведь не зря в UFOpaedia говориться "This represents a considerable threat to X-COM because the cultists will do anything to assist the Aliens in their purpose, whatever that might be". Инопланетяне заразят микроноидами и снабдят культистов своим оружием и будут использовать их как пушечное мясо. Cult members fight in groups of around 10.
10.  Ⓜ На сбитом НЛО могут оказаться сектоиды за спасение которых будут начислены баллы.
11.  Ⓜ На сбитом НЛО могут оказаться люди захваченные из соседних зданий для питания и за спасение которых будут начислены баллы.
12.  Ⓜ На миссии могут встречаться просто вооруженные гражданские люди  принадлежащие каким то не зарегистрированным движениям и не являющиеся частью никаких корпораций которые борются против тотального контроля корпораций (как частных организаций, возвышения человека над человеком).
13.  Рядом с разбившимся НЛО может появится миссия где инопланетяне из НЛО штурмуют здание а охрана отражает атаку.
14.  Вокруг разбившегося НЛО могут образовываться опасные аномальные зоны (огненный торнадо, отравленные облака, дым, взрывы) из за некорректной работы поврежденного корабля.
15.  Обшивка НЛО может быть домом для мелких насекомоподобных существ (Напр. Skincrawlers or Swarm) которые чинят "обшивку" и могут быть опасны для человека поедая или заменяя плоть.
16.  В каждом экипаже корабля НЛО (типы 3-7) могут быть 1-2 Micronoid Aggregate.
17.  В каждом экипаже корабля НЛО (типы 3-7) могут быть 2-6 Micronoid Headwrappers or Micronoid Mentor.
18.  Micronoid Headwrappers or Micronoid Mentor это 1/6 Micronoid Aggregate которые располагаются на голове др инопланетян и могут осуществлять пси контроль как агентов так и своих носителей.

19.  Сочетание разных типов выше перечисленных изменений.

**Comment by FilmBoy84** [comment]
Great ideas Makus
Would love to see these in a mod

The good news is, many of these are already possible by map editing as the original game was always meant to have a variety of mission types

Here's two "timed" UFO missions that work in the OG or OpenApoc

Fast Attack UFO
https://cdn.discordapp.com/attachments/402616863168659456/663150332649537586/fastattk.zip
Transport UFO
https://cdn.discordapp.com/attachments/402616863168659456/663150357643264033/transprt.zip

**Comment by makus82** [comment]
This is from https://www.ufopaedia.org/index.php/What_it_should_be._Design_doc_(Apocalypse)

**so pls feel free all to add more ideas to this concept**

**Comment by makus82** [comment]
Really good news @FilmBoy84 , thanks for the ifnormation. Much of the ideas were conceived so that it could be embodied in a game with less effort

This is from https://www.ufopaedia.org/index.php/What_it_should_be._Design_doc_(Apocalypse)

# **so pls feel free all to add more ideas to this concept**

**Comment by makus82** [comment]
Added 

1.  A mission may appear next to the crashed UFO where aliens storm the building and the guards reflect the attack.
2.  Around the crashed UFO can form dangerous abnormal zones (fire tornadoes, poison clouds, smoke, explosions) due to incorrect operation of the damaged ship.
3.  UFO casing can be home to small insect-like creatures (eg Skincrawlers) that mend the casing and can be dangerous to humans by eating or replacing flesh.
4.  Each crew of a UFO ship (types 3-7) can have 1-2 Micronoid Aggregate.
5.  Each UFO crew (types 3-7) can have 2-6 Micronoid Headwrappers.
6.  Micronoid Headwrappers are 1/6 Micronoid Aggregate which are located on the head of other aliens and can carry out psi control of both agents and their carriers.

1.  Рядом с разбившимся НЛО может появится миссия где инопланетяне штурмуют здание а охрана отражает атаку.
2.  Вокруг разбившегося НЛО могут образовываться опасные аномальные зоны (огненный торнадо, отравленные облака, дым, взрывы) из за некорректной работы поврежденного корабля.
3.  Обшивка НЛО может быть домом для мелких насекомоподобных существ (Напр. Skincrawlers) которые чинят "обшивку" и могут быть опасны для человека поедая или заменяя плоть.
4.  В каждом экипаже корабля НЛО (типы 3-7) могут быть 1-2 Micronoid Aggregate.
5.  В каждом экипаже корабля НЛО (типы 3-7) могут быть 2-6 Micronoid Headwrappers.
6.  Micronoid Headwrappers это 1/6 Micronoid Aggregate которые располагаются на голове др инопланетян и могут осуществлять пси контроль как агентов так и своих носителей.

**Comment by makus82** [comment]
@FilmBoy84 so this 2 timed missions mechanics is next:
player have 5 turns to get to the UFO and 5 turns to kills all who inside otherwise all go boom?
and there is checkpoints where u can disable explosives and get more time?

**Comment by makus82** [comment]
https://github.com/OpenApoc/OpenApoc/issues/880 related addition
