### ISSUE TITLE
Unable to start any research

### ISSUE THREAD

**Issue by McRayJason** [OpenApoc/OpenApoc#872]
Hi. I just started playing OpenApoc and right at the beginning I seem to not be able to start any research. When I click on a research in the research list, it doesnt highlight and even when i after click on OK, it does not get started.

Using the latest build (OpenApoc-x64-v0.2.0.2-212-ge77ca318)

**Comment by Atrosha** [comment]
Try this build: https://ci.appveyor.com/project/OpenApoc/openapoc/builds/32764429/artifacts

**Comment by makus82** [comment]
strange... 
Ty for report @McRayJason  
try if Atrosha build helps

**Comment by McRayJason** [comment]
Tested and the research works again. Do not have time to test it more currently, but at least I can select it and it does get started.

**Comment by makus82** [comment]
good then i close this @McRayJason
