### ISSUE TITLE
[MOD concept] Immersion: UFO crash missions

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#880]
![immmersion](https://user-images.githubusercontent.com/11581207/82648807-f1edc700-9c20-11ea-8f54-84aae8e6f880.png)

Immersion in the game will also help **quick pop up phrases** that agents or other characters will pronounce when they get into some kind of situation or interacting by clicking on the cursor as is done in fallout 2.

![fog](https://user-images.githubusercontent.com/11581207/82654333-38472400-9c29-11ea-9c67-c0ed4d171891.png)

This mod will help the player plunge into the atmosphere of the game even more with the help of **additional effects and sounds**. In the UFO crash mission (not only here but also on the city map), you can add meteorological and other phenomena taking into account the post-apocalyptic state of the earth’s atmosphere and to diversify the game:

- Fog - will affect visibility and accuracy. Motion scanners come in handy here.
- Rain - affects the speed of movement and accuracy, the agent can also slip and fall. Adding rain sounds and sometimes thunder sounds.
- A strong wind, will have its overlay with an animated sprite, will greatly affect the accuracy of shooting. Add the sounds of the wind.
- Storm - rain and heavy rain, thunderstorm, lack of lighting and visibility due to heavy cloud cover. Adding sounds of rain, strong wind and thunder.
- Add sounds of a living city (sounds of cars, sirens, gunfights, and working factories).
- Add the occasional sounds of a damaged UFO similar to creature moans.

Additional weather conditions:
- Snow (falling or falling, or both) the accuracy increases if the snow does not fall. Add snow sounds for step
- Icing (frozen snow after warming) movement is very limited and the risk for the agent to fall.
- Large hail
- Solar radiation or storms.
- Emissions of radiation (local)

![blood-hits](https://user-images.githubusercontent.com/11581207/82677719-1f526900-9c51-11ea-84ca-0c6873e9b8a5.png)

Nothing plunges more into the game than the sight of suffering and pain. A fight is never so clean. Aliens and people should not always die immediately, and sometimes shoot back with reduced accuracy (and you will have to finish them off so that they do not shoot or shut up). The wounded can moan for a long time, bleed and move a little, people can scream and call for help or swear using quick phrases. Puddles of blood under them can be added to corpses and wounded. When a bullet enters the body, add a small effect of tearing and scattering of blood and pieces of meat and clothing...

## Ru
Погружению в игру также помогут быстрые фразы которые агенты или другие персонажи будут произносить попав в какую то ситуацию или взаимодействуя нажимая курсором как это сделано в фаллаут 2. 

Этот мод поможет игроку погрузится в атмосферу игры еще больше при помощи дополнительных эффектов и звуков. В миссии по крушению НЛО (не только сюда но и на карту города) можно добавить Метеорологические и другие явления с учетом постапокалиптического состояния атмосферы земли и чтобы разнообразить игру:

- Туман - будет влиять на видимость и на точность стрельбы. Тут пригодятся сканеры движения.
- Дождь - влияет на скорость передвижения и на точность стрельбы, агент так же может подскользнутся и упасть. Добавление звуков дождя и иногда звуков грозы.
- Сильный ветер, будет иметь свой оверлей с анимированным спрайтом, будет сильно влиять на точность стрельбы. Добавить звуки ветра.
- Буря - дождь и сильный ливень, гроза, недостаток освещения и видимости из за сильной облачности . Добавление звуков ливня, сильного ветра и грозы.
- Добавить звуки живущего города (звуки машин, сирен, перестрелок, и работающих заводов).
- Добавить иногда возникающие звуки поврежденного НЛО похожие на стоны существа.

Дополнительные погодные условия:
- Снег (выпавший или падающий или оба) точность повышается если снег не падает.  Добавить звуки снега для шага.
- Оледенение (замерзший снег после потепления) передвижение сильно ограничено и риск для агента упасть.
- Град большого размера
- Солнечная радиация или бури.
- Выбросы радиации (локальные)

Ничто не погружает в игру больше чем вид страданий и боли. Бой никогда не бывает таким чистым. Инопланетяне и люди не должны всегда умирать сразу, а иногда отстреливаться с пониженной точностью (и вам придется добивать их чтобы они не стреляли или замолкли). Раненные могут долго стонать, истекать кровью и шевелится немного, люди могут кричать и звать на помощь или ругаться используя быстрые фразы. Трупам и раненным можно добавить лужи крови под ними. Когда пуля попадает в тело добавить небольшой эффект разрыва и разлетания крови и ошметков мяса и одежды...

**Comment by makus82** [comment]
![blood-hits](https://user-images.githubusercontent.com/11581207/82676839-b1597200-9c4f-11ea-9402-f4ab923c80df.png)

Nothing plunges more into the game than the sight of suffering and pain. A fight is never so clean. Aliens and people should not always die immediately, and sometimes shoot back with reduced accuracy (and you will have to finish them off so that they do not shoot or shut up). The wounded can moan for a long time, bleed and move a little, people can scream and call for help or swear using quick phrases. Puddles of blood under them can be added to corpses and wounded. When a bullet enters the body, add a small effect of tearing and scattering of blood and pieces of meat and clothing...

### Ru
Ничто не погружает в игру больше чем вид страданий и боли. Бой никогда не бывает таким чистым. Инопланетяне и люди не должны всегда умирать сразу, а иногда отстреливаться с пониженной точностью (и вам придется добивать их чтобы они не стреляли или замолкли). Раненные могут долго стонать, истекать кровью и шевелится немного, люди могут кричать и звать на помощь или ругаться используя быстрые фразы. Трупам и раненным можно добавить лужи крови под ними. Когда пуля попадает в тело добавить небольшой эффект разрыва и разлетания крови и ошметков мяса и одежды...

**Comment by JonnyH** [comment]
I think it makes sense to pull out "mod concepts" from the openapoc core issue tracker - as they're not really "issues" with openapoc itself :P

Perhaps keeping this sort of thing on the forums, or creating a new "mods" github repository, would help keep things tidier?
