### ISSUE TITLE
Ordered engines are not shown in the equipment window

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#892]
Ordered engines for phoenix cars are not shown in the equipment window but in the trading interface it is shown that it is on the base.

This situation was also at other start try when i start earlier a bit ..
And yes i wait some time and even half a day

at build ga76f1a5a

![image](https://user-images.githubusercontent.com/11581207/83325779-c0f04080-a277-11ea-8972-7f6ff602a609.png)

![image](https://user-images.githubusercontent.com/11581207/83325789-cea5c600-a277-11ea-982e-bc707650991f.png)

**Comment by FilmBoy84** [comment]
Metro power plus is a ROAD vehicle engine
It will not appear for flying vehicles like the hovercar
