### ISSUE TITLE
When ru language on skill number dont shown in lab screen

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#893]
When ru language on skill number dont shown in lab screen

![image](https://user-images.githubusercontent.com/11581207/83326233-e6327e00-a27a-11ea-903a-09e8fa1f58ab.png)

**Comment by FilmBoy84** [comment]
This looks like a forms issue

I suspect it's showing it, but, like many things under More Options for example, it's being pushed outside the edge of the box

Once i finish updating the forms and screens for 960p i'll fix this

In the meantime, ill also look at how i can change the existing form without breaking the OG look (or other languages)

If you want to play yourself, the form data is in **_researchscreen.form_**

**Comment by FilmBoy84** [comment]
![image](https://user-images.githubusercontent.com/33913088/83327492-41ad3d80-a274-11ea-9942-11758a5868b7.png)

For comparison with Romanised alphabet
The cyrillic one appears larger so fills the form more easily

**Comment by makus82** [comment]
yep i understand about longer russian but there can not only russian be that way
so this is issue with forms yes

**Comment by makus82** [comment]
to do text strings place in forms like maximum size possible in every form to prevent this...

**Comment by FilmBoy84** [comment]
Any language that is not native to the OG will have issues with the forms sadly

The screens were designed at 480p with English/German/French/Spanish/Italian in mind only

So any language using a characterset resulting in longer translations will inevitably go outside the bounds of the form

You may be able to get the forms to "wrap" text, but this will make a mess of the data each box shows in terms of formatting - but it will show all the info

It may be that until we get the 960p screens sorted a compromise will have to be made for Cyrillic translations and we ship a different version of the forms just for those languages as making a change to the forms to cater for Cyrillic will also alter Romanised languages

Alternatively, scaling of text to fit the box (which means we need to get true-type fonts implemented)

**Comment by makus82** [comment]
960p can be really big and there will be a lot empty space

**Comment by FilmBoy84** [comment]
That's one reason it's taking a while - Trying to keep the feel of the Original game and showing all the required data whilst allowing extra space for new data

Text scaling is one of the big issues we need to resolve - and that cannot be done until we implement True-Type font support (or similar)

After-all, don't we want to give modders the chance to have all the text in giant comic sans ha ha :D

**Comment by JonnyH** [comment]
All the forms should be replace-able by a mod - just create a matching file under the data/ directory and it'll override it.

Currently, all the forms use exact pixel positions - adding new controls to manage layout (e.g. tables and padding that can auto-expand based on content) likely makes sense.

I think going forward we are going to implement much of the language support as "mods" - as that allows us to (optionally) translate names contained in the gamestate xml (weapon names, vehicle names, building/organisation names etc.). Currently pushing all that through the global translate call is extremely fragile, and ends up tying together systems that should really be independent.

**Comment by makus82** [comment]
I suggest just delete this here and we good) 
![image](https://user-images.githubusercontent.com/11581207/88824501-19d44a80-d1cf-11ea-8619-93cb3898a49d.png)
