### ISSUE TITLE
game crashes after intro

### ISSUE THREAD

**Issue by thainlnguyen** [OpenApoc/OpenApoc#902]
v0.2.0.2-253-gb87734d1 
W class OpenApoc::SoundBackend *__cdecl `anonymous-namespace'::SDLRawBackendFactory::create(void) Creating SDLRaw sound backend (Might have issues!)
W __cdecl `anonymous-namespace'::SDLRawBackend::SDLRawBackend(void) Changing audio drivers is not currently implemented!
W __cdecl `anonymous-namespace'::SDLRawBackend::SDLRawBackend(void) Selecting audio devices not currently implemented! Selecting first available device.
W __cdecl `anonymous-namespace'::SDLRawBackend::SDLRawBackend(void) Audio output format: Channels 2, format: signed float LE 32bit, freq 22050, samples 492
W void __cdecl OpenApoc::Framework::setupModDataPaths(void) loading mod "base"
W void __cdecl OpenApoc::Framework::setupModDataPaths(void) Loaded modinfo for mod ID "org.openapoc.base"
W void __cdecl OpenApoc::Framework::setupModDataPaths(void) Appending data path "./data/mods/base/data"
W void __cdecl OpenApoc::Framework::run(class std::shared_ptr<class OpenApoc::Stage>) Over 5 frames behind - likely vsync limited?

**Comment by thainlnguyen** [comment]
hello,
found a log file with the following:

`I class OpenApoc::IFile __cdecl OpenApoc::FileSystem::open(const class OpenApoc::UString &) const: Failed to find "ui/loading.png"
I class std::shared_ptr<class OpenApoc::Image> __cdecl OpenApoc::DataImpl::loadImage(const class OpenApoc::UString &,bool): Failed to load image "ui/loading.png"
I class OpenApoc::IFile __cdecl OpenApoc::FileSystem::open(const class OpenApoc::UString &) const: Failed to find "ui/logo.png"
I class std::shared_ptr<class OpenApoc::Image> __cdecl OpenApoc::DataImpl::loadImage(const class OpenApoc::UString &,bool): Failed to load image "ui/logo.png"
`

is this a simple path issue?

**Comment by emptyVoid** [comment]
@thainlnguyen, does the issue manifest on a master build? (e.g. https://ci.appveyor.com/project/openapoc/openapoc/branch/master/artifacts)

**Comment by makus82** [comment]
v0.2.0.2-253-gb87734d1  here on top of i think

**Comment by makus82** [comment]
@thainlnguyen  did you launch seccusfuly before openapoc? maybe its somthing wrong with setup..

**Comment by emptyVoid** [comment]
> v0.2.0.2-253-gb87734d1 here on top of i think

Yeah, that confusion is addressed in #899.

**Comment by JonnyH** [comment]
If it failed to load ui/logo.png it can't find the data/ directory. Did you extract the whole package first? Is the data/ folder in the same directory as the openapoc.exe you're running?

**Comment by thainlnguyen** [comment]
hello y'all and thank you for getting back! i'm in california time so pardon me for the delayed response.

i did download both with same result/crash:
- v0.2.0.2-253-gb87734d1
- v0.2.0.2-248-gacd0d1c3 

this is the content of my OpenApoc_settings.conf:
```
[Framework]
CD=F:/open_apoc/OpenApoc-v0.2.0.2-248-gacd0d1c3/data/cd.iso
Data=F:/open_apoc/OpenApoc-v0.2.0.2-248-gacd0d1c3/data/mods
[Framework.Screen]
Fullscreen=0
Height=720
Width=1280
[Game]
Mods=base
```
OpenApoc path:
![folder_struc](https://user-images.githubusercontent.com/2974657/85360817-1a423d00-b4cf-11ea-8182-b22ee8b7996b.PNG)

OpenApoc ./data folder:
![image](https://user-images.githubusercontent.com/2974657/85360902-55447080-b4cf-11ea-8e85-eee975a987a1.png)

how do i proceed and thank you so much for your time!

**Comment by thainlnguyen** [comment]
oops...

**Comment by JonnyH** [comment]
`Data=F:/open_apoc/OpenApoc-v0.2.0.2-248-gacd0d1c3/data/mods`

I think the Framework.Data option should point at the parent data folder, not the mods folder within that (e.g that should be "F:/open_apoc/OpenApoc-v0.2.0.2-248-gacd0d1c3/data"

**Comment by thainlnguyen** [comment]
it works!

![image](https://user-images.githubusercontent.com/2974657/85369719-76fb2300-b4e2-11ea-9101-c823e6dedbb1.png)

thank you, sir!

**Comment by makus82** [comment]
@thainlnguyen ur welcome! feel free add more bugreports if u find some bugs =]
