### ISSUE TITLE
Icons of UFOs on map not should be circle red

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#906]
![image](https://user-images.githubusercontent.com/11581207/86483052-e0d5c100-bd5b-11ea-9462-8f0c5e4c8f4c.png)

Icons of UFOs on map not should be circle red but red square romb
![image](https://user-images.githubusercontent.com/11581207/86483135-0cf14200-bd5c-11ea-98f1-311e43fd1eef.png)

**Comment by FilmBoy84** [comment]
If i recall this is size related
So smaller UFOs use 
![image](https://user-images.githubusercontent.com/33913088/86535746-8747d080-beda-11ea-9901-ecf7d134a8a9.png)
Whereas larger UFOs use a red circle

**Comment by makus82** [comment]
nop in OG all ufo use https://user-images.githubusercontent.com/33913088/86535746-8747d080-beda-11ea-9901-ecf7d134a8a9.png
only really big use Big circle but not small circle

**Comment by makus82** [comment]
> If i recall this is size related
> So smaller UFOs use
> ![image](https://user-images.githubusercontent.com/33913088/86535746-8747d080-beda-11ea-9901-ecf7d134a8a9.png)
> Whereas larger UFOs use a red circle

nop in OG all ufo use 
 ![image](https://user-images.githubusercontent.com/33913088/86535746-8747d080-beda-11ea-9901-ecf7d134a8a9.png)
only really big use Big circle but not small circle

**Comment by FilmBoy84** [comment]
That's what i thought; Battleship and Mothership use big red circles
All other craft are only one tile in size so use the single tile
![image](https://user-images.githubusercontent.com/33913088/86537875-232d0880-beea-11ea-82e5-cd49aca1c492.png)

TBH what we should have is a large, four tile version of the red arrow for big UFOs and keep all red circles for ground vehicles only

I can only assume this was not done as a result of time constraints

**Comment by makus82** [comment]
im for left all as is) in OG

**Comment by FilmBoy84** [comment]
The big problem with the OG is that you cannot see which direction Large UFOs are heading from the map
It may be worth trying to fix this with a new icon...

**Comment by idshibanov** [comment]
Large UFO icon is a thing of preference. Personally, I like the big menacing circle, it fits.

**Comment by FilmBoy84** [comment]
[Directional Large Flyer Map Icons.zip](https://github.com/OpenApoc/OpenApoc/files/4966760/Directional.Large.Flyer.Map.Icons.zip)

Preview
![ne_largeflyer](https://user-images.githubusercontent.com/33913088/88301116-26066680-ccfc-11ea-94eb-3956223e547f.png)
![nn_largeflyer](https://user-images.githubusercontent.com/33913088/88301120-27379380-ccfc-11ea-94aa-069d07e79605.png)

**Comment by FilmBoy84** [comment]
Updated version including sectioned 8x8 sprites for map tiles
[Directional Large Flyer Map Icons.zip](https://github.com/OpenApoc/OpenApoc/files/4966899/Directional.Large.Flyer.Map.Icons.zip)

**Comment by FilmBoy84** [comment]
Directional Large Flyer Map Icons for OpenApoc
I've included "whole" icons that cover 2x2 tiles
As well as "part" icons for making all the forms on a per-tile basis of loading the sprites
Hopefully this way we are covered

I'm in agreement with ShellStorm - This should be an OPTIONAL fix

But it will help in later development and mods to identify Large Ground Vehicles from Large Flying Vehicles
![image](https://user-images.githubusercontent.com/33913088/88311266-91eecc00-cd08-11ea-8ede-2b2d5ef9c7a3.png)
[Directional Large Flyer Map Icons v2.zip](https://github.com/OpenApoc/OpenApoc/files/4967417/Directional.Large.Flyer.Map.Icons.v2.zip)

**Comment by makus82** [comment]
Fixed
