### ISSUE TITLE
It is not possible to have no selections of bases/craft/agents/scientists on the cityscape

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#907]
In Apoc OG was possible to select nothing
![image](https://user-images.githubusercontent.com/11581207/86574692-e2cb9a00-bf7e-11ea-9990-bce70934ba21.png)
In OA its always selected base 1

**Comment by FilmBoy84** [comment]
This is still a problem, and I cannot find a PR that fixes it (when we close an issue we really need to link the PR that fixes it too)

Selecting a base, vehicle or agent in the cityscape, then attempting to deselect them in either the map or regular view still keeps the last unit selected.

Moving to a none-unit tab, for example diplomacy, does not deselect the last unit either, as soon as you return to their tab, they are still selected

We still need to implement the OG mechanism for deselecting units and buildings

I am therefore reopening

**Comment by FilmBoy84** [comment]
Edit, further update, right-clicking an agent or vehicle portrait does deselect them

This does not apply to bases

**Comment by FilmBoy84** [comment]
Going back to the OG, you cannot deselect a base there either

Closing issue again :sweat_smile:

**Comment by FilmBoy84** [comment]
If we find the PR that resolved this, please link here...
