### ISSUE TITLE
[Cityscape] CTD when targetting UFO

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#929]
First UFO incursion, multiple vehicles selected. Target the first UFO, everything works. 5/6 vehicles have landing pads to takeoff.

2nd UFO comes into play, change all of them to the 2nd target, using the Target UFO button. Instant CTD.

[CTD Target UFO.zip](https://github.com/OpenApoc/OpenApoc/files/5017097/CTD.Target.UFO.zip)

**Comment by BeornTB** [comment]
I tried to replicate it, same savegame, but all I get is a vehicle ID CTD

https://i.imgur.com/1Hee3Q9.png

[CTD Vehicle ID.zip](https://github.com/OpenApoc/OpenApoc/files/5017104/CTD.Vehicle.ID.zip)

**Comment by Atrosha** [comment]
#931
