### ISSUE TITLE
CTD throwing a grenade - Incorrect Tile Coordinates

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#930]
https://i.imgur.com/5ayQ12u.png

RT combat. Soldier was halfway through moving into a square, paused, and I issued a command to throw a grenade on the same tile he was about to reach. It was plain ground, no elevator shenanigan. CTD upon unpausing.

Unfortunately, the save isn't any good (pre-combat). Hopefully the log will help.

[GrenadeThrow.zip](https://github.com/OpenApoc/OpenApoc/files/5019587/GrenadeThrow.zip)

**Comment by makus82** [comment]
Hey @BeornTB about screening you can just select error window and then press Alt+PrntScrn 
then just set cursir in issue text writing window  where u need it and press Ctrl+V and Prntscreen image will be uploaded =]

**Comment by makus82** [comment]
![image](https://user-images.githubusercontent.com/11581207/89286410-d197ab00-d65a-11ea-8483-48a84a627057.png)

**Comment by Istrebitel** [comment]
easy to reproduce, start superhuman campaingn, start skirmish in ufo, default settings and equipment, move 1st soldier to adjacent cell, immediately order a grenade throw (right click grenade, left click where he goes), when he arrives and throws it will bug out in one form or the other, it seems velocity is NAND for some reason. should be easy to fix
