### ISSUE TITLE
No Vehicle object matching ID "VEHICLE_19"

### ISSUE THREAD

**Issue by Lukewhale** [OpenApoc/OpenApoc#940]
Hi, I have been speaking to FilmBoy and he has ask me to log this and send save and log

[save_lukewhale.zip](https://github.com/OpenApoc/OpenApoc/files/5198244/save_lukewhale.zip)

[log.txt](https://github.com/OpenApoc/OpenApoc/files/5198253/log.txt)

All i done in the game was buy/sell and build base.
(Note) Sold ground units and bought hover bikes x4 , hover cars x4 and equip them with lasers and better engines. Change the name of soldiers and recruit new researchers/engineers. Dont this is this may have caused a issues but i moved all the researchers and engineers out of the base and then picked the highest skill level

Anything else just let me know.. Thank you   

OpenApoc error

class std::shared_ptr<class OpenApoc::vehicle> _cdecl OpenApoc::stateObject<class OpenApoc::Vehicle>::get(const class OpenApoc::GameState &,const class std::basic_string<char_traits<char>,class std::allocator<char> > &): No vehicle matching ID "VEHICLE_19"

void _cdecl OpenApoc::StateRef<class OpenApoc::vehicle>::resolve(void) const: No Vehicle object matching ID "VEHICLE_19" found

**Comment by FilmBoy84** [comment]
This is part of #931 So please see there too :)

**Comment by FilmBoy84** [comment]
Closing as referenced and a duplicate

**Comment by makus82** [comment]
Thx for report anyway L =]
