### ISSUE TITLE
[Cityscape] Transport vehicles do not leave the city

### ISSUE THREAD

**Issue by Jarskih** [OpenApoc/OpenApoc#953]
![bug1](https://user-images.githubusercontent.com/9105185/99463642-83bb6000-2936-11eb-950a-1b2aba0b7d9c.jpg)
![bug2](https://user-images.githubusercontent.com/9105185/99463645-8453f680-2936-11eb-87ac-96baeecbdd2b.jpg)

Error message: 
W struct OpenApoc::VehicleTargetHelper::AdjustTargetResult __cdecl OpenApoc::VehicleTargetHelper::adjustTargetToClosestFlying(class OpenApoc::GameState &,class OpenApoc::Vehicle &,struct glm::vec<3,int,0> &,const enum OpenApoc::VehicleTargetHelper::VehicleAvoidance) Target 96,0,12 was unreachable, found new closest target 96,2,6

**Comment by JonnyH** [comment]
Is this a new issue? I tweaked the mission code the other day (https://github.com/OpenApoc/OpenApoc/commit/5bc932eccfe9993d1f719995d82d857f746bc034 PR #952 ) and might have screwed something up....

**Comment by Jarskih** [comment]
This happened before I pulled the your changes so I think its unrelated. I couldn't reproduce this today anymore and it might have been related to something I was working on yesterday. Or it is some rare issue with pathfinding in turbo mode.

**Comment by JonnyH** [comment]
I think there's a current issue with if multiple vehicles (or agents) have a mission that requires to be on a specific tile it can get into a state where both arrive at the tile within one tick (or one set of update() processing, which means it's way more likely on turbo), but gets asked to move away by the other before it gets a chance to finish it's mission, then that one asks the second one to move before it can complete it's mission in a loop forever.

Pathfinding through other objects (and 'requesting' them to move) is a bit of a bug filled mess right now from my testing. Though the OG often behaved badly in similar situations too.

**Comment by FilmBoy84** [comment]
I can no longer replicate this issue with JonnyH's recent fixes, closing, unless we have it again, in which case, we can reopen it.
