### ISSUE TITLE
Difficulty SubMods still require archives. Use of folders causes a CTD

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#960]
The Modding Structure has been, for a while, able to read changes to the gamestate from a folder(s) specified by the modinfo.xml without the need to compress them into an archive. For Example, the current EWM has this:
![image](https://user-images.githubusercontent.com/33913088/99910760-c3dc6300-2ce7-11eb-9d17-5600860b09b5.png)

However, when dealing with SubMods and the GameState, for example when making changes to the difficulty XMLs, using folders and no archives will cause CTDs

As a result, the only option is to currently make changes in a folder such as "difficultyX~" where X is a number
Then compress them into an archive with no suffix and called "difficultyX" before they are read and applied
For example, again using the EWM, here
![image](https://user-images.githubusercontent.com/33913088/99910833-2c2b4480-2ce8-11eb-902a-c6184de16422.png)

Not exactly sure why this problem occurs with loading materials into the gamestate, but only with SubMods

**Comment by JonnyH** [comment]
I can't seem to repro this - downloading the latest EWM (cc3ac8f) - delete the difficultyX~ folders, moved the diffcultyX files to another folder then extracted them back to the submods/org.openapoc.mods.filmboy88.extendedweaponsmod (so there are the files "submods/org.whatever/difficulty0/gamestate.xml" etc. - it seemed to load fine.

**Comment by FilmBoy84** [comment]
Thanks for prompt response, will have a play in the morning and close if it's no longer happening following your method - I had just deleted the difficultyX~ folders, unzipped to "difficultyX" (as a folder)

I had not copied the archives out and the contents back in

**Comment by FilmBoy84** [comment]
This does appear to be no longer an issue, closing
