### ISSUE TITLE
 Game crashes when game clock is at 23:55:00, Monday, March 13, 2084

### ISSUE THREAD

**Issue by Jigerson** [OpenApoc/OpenApoc#965]
When this date and this time in the game comes, it freezes for a couple of seconds and then crashes.

[log.txt](https://github.com/OpenApoc/OpenApoc/files/5640028/log.txt)

**Comment by FilmBoy84** [comment]
Thanks for report Jigerson
Do you have a savegame just before this happens?

**Comment by FilmBoy84** [comment]
See also #969

**Comment by cTacuk7** [comment]
this might help, save file, 70 ingame minutes before crash
[save_STS.zip](https://github.com/OpenApoc/OpenApoc/files/5838299/save_STS.zip)

**Comment by FilmBoy84** [comment]
Brilliant, thanks for the save cTacuk7
