### ISSUE TITLE
Crash at the end of Day 21 (23:55)

### ISSUE THREAD

**Issue by tixiera** [OpenApoc/OpenApoc#969]
Everytime day 21 ends (23:55), I crash to desktop without an error. Here is the save game,

 I think it might be related to the solder Jane Green that seems linked to a marsec building. When I try to return it to base, there is a green line that links the my second base but she stays in that marsec building.

About that second base :

This is the second version, the one I built earlier got taken over (no defense) so I rebuilt it at the same spot. Maybe it's related to that?

[save_Marf2.zip](https://github.com/OpenApoc/OpenApoc/files/5748392/save_Marf2.zip)

**Comment by FilmBoy84** [comment]
Thanks for the report tixiera

For any dev picking this up, issue #965 may be related

**Comment by FilmBoy84** [comment]
Should be fixed by #975 
Closing
