### ISSUE TITLE
Game crashes at midnight every 7th day (And other [somewhat major] bugs to report)

### ISSUE THREAD

**Issue by XanthusAnon** [OpenApoc/OpenApoc#971]
_I understand this issue has been posted a few times prior. However I do not believe people are noting that this is happening EVERY 7th day not just specific dates for me._ 

**Issue #1:**
Every 7th night at midnight the game crashes, I suspect this is when the budget screen is meant to appear.
This began at the very beginning of my game which was started using version 0.0.356. Updated to 0.0.357 (v0.254-77) but it didn't fix the issue.
HOWEVER: To continue progressing through the game I have to downgrade the version of the game back to v0.2.0.2-256. This version appears to remain pretty much entirely stable. 
Once the game steps past the 7th midnight of each week I then reinstall the latest edition for the most stable behaviour and function.

**Issue #2:**
The game has sadly degraded gradually to the point I can't actually play it anymore. When loading the save you get 7 recurrent "VEHICLE_3046" errors, then it runs. It's been stable until I've gotten to the point I now need to re-enter the alien dimension after probing a while earlier. (Which brings me to)

**Issue #3:**
Upon entering the alien dimension I get four more vehicle ID errors then a CTD every time. Progression is now sadly impossible.

**Issue #4:** 
The town map has slowly been destroyed over time. Overnight (passed midnight) the landscape will show as repaired but no building is -actually- repaired as it will not allow further attacking, raiding or activity. Reloading a save after saving or going into another environment like a battle then back to the cityscape will reveal just how damaged the city is. Without it rebuilding, transport and purchasing has slowly become harder and harder to do (thankfully at this point nearly everything is made in house)

**Issue #5** 
As of the latest edition, alien ships will come through the portals, wiggle around for a moment then immediately leave without dropping anything off.

Please see the attached save file for the issues, I do hope some of these things do help.
(NOTE: This save has a transport about to head into the alien dimension, please redirect it if you do not want it to load the alien dimension after the end of the next night. An alien attack will happen after a few ingame hours after the transport goes in.

[save_New Arararr.zip](https://github.com/OpenApoc/OpenApoc/files/5758618/save_New.Arararr.zip)

**Comment by FilmBoy84** [comment]
Many thanks for the report
With regards to the EoD error, this is related to Issue #965 

I'll have to track down all the other issue numbers, but these have been reported before so will update with your info

**Comment by FilmBoy84** [comment]
Should be fixed by #975 
Closing
