### ISSUE TITLE
The alien activity graph is not showing

### ISSUE THREAD

**Issue by Connorisgameing** [OpenApoc/OpenApoc#972]
I can open the graph window but there are no faction buttons for me to click on, and so no way for me to see if anyone has had alien activity. This is a small bug but I would like to use the graphs, otherwise enjoying the mod.

![Capture](https://user-images.githubusercontent.com/41496469/104065383-e4d81500-51bc-11eb-80c3-19a14c646b94.PNG)

 I'm new to the classic x-coms but watched people play them some times, it nice to have community mods to work off the rough edges, no more dosbox artifacts and a nice 1920x1200 display with custom resolution support thank you for that. Will say I wish I could scale the UI up, but I've already seen the post on why that would be hard to implement.

Sorry for rambling but thanks for the hard work you put in to make this game more approachable in 2021.

**Comment by makus82** [comment]
if u click on piramid icon topright
u get partly working graphs

**Comment by makus82** [comment]
![image](https://user-images.githubusercontent.com/11581207/105766073-f44bb200-5f61-11eb-8dc4-faa62d41df65.png)
