### ISSUE TITLE
Game crashes on start; v0.254-61

### ISSUE THREAD

**Issue by Csimbi** [OpenApoc/OpenApoc#974]
Hello,
I just downloaded OpenApoc-v0.254-61-g9b4cdbf1.
My settings:
```
[Framework]
CD=./data/cd.iso
Data=./data
[Framework.Audio]
GlobalGain=20
MusicGain=20
SampleGain=20
[Framework.Screen]
Fullscreen=1
Height=800
Width=1280
[Game]
Mods=base
SkipIntro=1
[Notifications.City]
AgentArrived=1
AgentDiedCity=1
CargoArrived=1
NotEnoughAmmo=1
NotEnoughFuel=1
RecoveryArrived=1
TransferArrived=1
UfoSpotted=1
UnauthorizedVehicle=1
VehicleDestroyed=1
VehicleEscaping=1
VehicleHeavyDamage=1
VehicleLightDamage=1
VehicleLowFuel=1
VehicleModerateDamage=1
VehicleNoAmmo=1
VehicleRearmed=1
VehicleRefuelled=1
VehicleRepaired=1
[Options.Misc]
ActionMusic=1
AutoExecute=0
AutoScroll=1
ToolTipDelay=500

```

I start the launcher and then, the game.
This is the dialog that greets me:
https://i.postimg.cc/13jQ7fR0/XCOMAPOC.png
The error message is so long it won't fit on screen and I can't see the buttons, either.

I attached the log file, does it help?

Thanks for looking into it!

[log.txt](https://github.com/OpenApoc/OpenApoc/files/5854220/log.txt)

**Comment by JonnyH** [comment]
It looks like you've got the CD path setup incorrectly, as it's failing to load any files from it.

By default it looks to data/cd.iso, but can be changed in the config or the launcher app.

**Comment by Csimbi** [comment]
I have the CD in d:\GAMES\OpenApoc-v0.254-61-g9b4cdbf1\data\cd.iso
So, CD=./data/cd.iso should be correct.

**Comment by JonnyH** [comment]
I closed it as your log.txt has the line:

"Failed to add resource dir "./data/cd.iso", error: not found"

then all the errors fail to load any resources from the cd (IE we load the 'music' file as a quick sanity check, as in the line

"Failed to open "music" from the CD - likely the cd couldn't be loaded or paths are incorrect if using an extracted CD image"

Which was probably what was on the end of your super long dialog box.

Though that's probably the real issue - if the error messages aren't useful to users we need to fix that - feel free to open a bug about that. Maybe they need word-wrapping, or we need to be more clever about how we identify the function (as the mangled c++ name is super long and often not particularly useful, so could likely be shortened)

So either something has been named wrong or the permissions on that file disallow access by openapoc. It's super unlikely it's a bug in openapoc (though admittedly not impossible), as at that point we're just using the standard physfs "try to open file" functions. They're pretty battle tested, and the most likely answer is an issue with the file location/name (it has to match /exactly/, make sure you don't have any strange non-ascii characters in the name that make it /look/ like "cd.iso" while not actually being that), or OS permissions, but I think in windows 10 it's pretty difficult to end up with a situation where a user cannot access a file in a directory they created without actively trying and messing around with the ACLs manually.

**Comment by JonnyH** [comment]
BTW I realised I might be coming across as a bit short - it's hard to judge tone on the internet. I don't mean to say "We don't want to help", so much as "This doesn't really look like an openapoc bug, and the bugtracker isn't really the best place to help with stuff like that".

If you use discord we have a link in the readme, fast response is normally better than often-multiple-day turnaround on bugtrackers - I tend to only look at this when I have some time to work on openapoc, and it's a secondary side project at best, so may be weeks depending on how busy I am :)

**Comment by Csimbi** [comment]
Understood.
What is the correct way of using the GOG.com BIN/ISO file?
I rename the BIN to ISO - same error.
I rename the CUE to ISO - same error.
I just can't get it working.
OpenApoc-v0.2.0.2-52-g8486543f took the BIN renamed to ISO.
Thanks!

**Comment by FilmBoy84** [comment]
If using the installer, it will detect GOG automatically and do the work already
I assume you have been using the manual install?

Glad all is working now though

**Comment by JonnyH** [comment]
> Could this bug report be assigned as throwing a CD not found error instead of a palette error?
> Thanks!

We already do this - we actually test for the presence of the music file (as that's something not installed, so you can't accidently use an installed directory as that's missing some things) and if we can't the first error says:

"Failed to open "music" from the CD - likely the cd couldn't be loaded or paths are incorrect if using an extracted CD image"

Which is hopefully a little more useful than random failed-to-load-file messages. But you're right it could probably be more user-focused and less technical.

The problem is that message was probably off the side of the error box for you, so you couldn't see what the first one you clicked through actually said :P

**Comment by Csimbi** [comment]
Make sense, although I recall only one message box only (about the palette).
Then the game terminates without saying anything else.
