### ISSUE TITLE
Game crash after selecting a vehicle

### ISSUE THREAD

**Issue by jouki** [OpenApoc/OpenApoc#976]
Hi,
the game crashes in certain situations. I assume all those I've experienced will have the same root cause. I'm attaching a savefile with the following steps to replicate:
1) After loading the game simply resume the time in the tactic mission
2) Mission will end after a little while as there is no other enemy in the area.
3) Confirm the summary screen
4) You should see the selection of Valkyre leaving the Temple of Sirius. The game should be paused (I didn't test continuing the time)
5) Click on the Valkyre (on the main screen in the temple, not on UI or anywhere else)
![image](https://user-images.githubusercontent.com/1493141/106134635-195d4200-6167-11eb-8d77-945a339db5fa.png)
6) Game crashed

**Note**: It seems to be the problem with sort of layering as the problem occurs only when you click in the **center** of the rectangle - the corners work as expected I'd say.

[save_1.zip](https://github.com/OpenApoc/OpenApoc/files/5886816/save_1.zip)

I'm sorry if it's a duplicate already.
This type of crash happened to me several times already so it doesn't seem to be as rare as it might look like.
If anything else you need let me know I'll try to help

Cheers,
Jouki

**Comment by makus82** [comment]
@jouki Welcome n thx for detailed n pro like report =]

**Comment by EmperorLol** [comment]
Backing up the above issue with another save file of the easily replicable crash. Once the valkyrie emerges from the slum block, whether or not it's selected via the control bar, clicking on it creates an immediate CTD. 

[save_Overworld 2.zip](https://github.com/OpenApoc/OpenApoc/files/5888167/save_Overworld.2.zip)
