### ISSUE TITLE
CTD at midnight on 7th day 

### ISSUE THREAD

**Issue by EmperorLol** [OpenApoc/OpenApoc#977]
Sorry for having to reopen this issue, but it's still happening for me. Currently blocked my progress as it repeats whenever I reload. 
I also slowed the game down to standard speed just before it got there and it still crashed at exactly 00:00.

Save in question attached!
[save_Overworld 1.zip](https://github.com/OpenApoc/OpenApoc/files/5893854/save_Overworld.1.zip)

**Comment by idshibanov** [comment]
Tested your save on latest version (master branch), game doesn't crash. Can you try with a fresh build?

Bug happened originally because Temple of Humility building was razed to the ground.

**Comment by EmperorLol** [comment]
Yep, looks like the latest build fixed it. Turns out it was updated literally hours after I initially downloaded the game! Bad luck. 
Cheers!
