### ISSUE TITLE
[Geoscape] Quick access buttons for Biochem and Engineering from the control bar open Quantum Physics Lab

### ISSUE THREAD

**Issue by EmperorLol** [OpenApoc/OpenApoc#978]
Pretty simple, but see image below. Pressing the button with the beaker sends you to the Quantum Physics Lab, not the actual lab they're depicting and I expect supposed to be linked to. 
![Screenshot 2021-01-30 115027](https://user-images.githubusercontent.com/78159929/106355664-6836e300-62f1-11eb-84a9-a3ba4f639ee6.png)

**Comment by makus82** [comment]
Yep this button and two other similar buttons lead either to biochemistry as the first in the facilities list (if the game has recently begun) or leads to the last selected facility
