### ISSUE TITLE
No vehicle matching ID VEHICLE_7574

### ISSUE THREAD

**Issue by endy2qq** [OpenApoc/OpenApoc#988]
The error message 「No vehicle matching ID VEHICLE_7574」　occured when Load save file. Please check. Thank you verymuch all the time. Sorry for my terrible English
[Vehicle Error.zip](https://github.com/OpenApoc/OpenApoc/files/5943690/Vehicle.Error.zip)

**Comment by FilmBoy84** [comment]
Thanks for the report endy2qq

This appears to be related to issue #940 so closing here to continue work there
