### ISSUE TITLE
Agent number should be moved 1 or 2 pixel left not to touch the frame

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#993]
Agent number should be moved 1 or 2 pixel left not to touch the frame
![image](https://user-images.githubusercontent.com/11581207/107780787-d8148700-6d4f-11eb-8154-393c813ef49e.png)

**Comment by FilmBoy84** [comment]
Thanks for the report Makus
This should be a simple form correction providing it is present in all languages
Verified in English too
Updating Label

**Comment by makus82** [comment]
found this tab in forms but there no such element (agents number)
https://github.com/OpenApoc/OpenApoc/blob/70cbddfa109379441fc8509f3dd485c2ac1e5734/data/forms/city/tab2.form
