### ISSUE TITLE
Buy and Sell Vehicle screen scrollbar handles or bars all aligned in center

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#995]
Buy and sell Vehicle screen scrollbar handles or bars all aligned in center
and need mouseover to put this handles to true positions

but all other 3 Buy and Sell screens are good so i think something just missing in vehicle screen...
![image](https://user-images.githubusercontent.com/11581207/107851173-897af180-6e10-11eb-92cc-bd3214b1d96d.png)

**Comment by FilmBoy84** [comment]
Thanks for report Makus

This is related to the list of issues in #992 so referencing that here as well

**Comment by makus82** [comment]
Its actually stay hm

**Comment by FilmBoy84** [comment]
Resolved in #1156 

@makus82 good to have you back too man :smile:
